"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./DraftBoard.module.css";

type StatLine={season:number;games:number|null;fantasy_points:number;stats:Record<string,number>;source:string};
type Alternative={id:string;name:string;nflTeam:string|null;projectedPoints:number;pointsAboveReplacement:number|null;productionTier:number|null;liveExpectedPrice:number|null;productionLabel:string};
type FantasyAnalysis={label:string;sentiment:string;summary:string;rationale:string;risks:string[];sourceTitle:string;author:string|null;url:string;publishedAt:string};
type AnalystConsensus={action:"target"|"avoid"|"watch"|null;derivedAction:"target"|"avoid"|"watch"|null;override:"target"|"avoid"|"off"|null;tags:string[];positiveCount:number;negativeCount:number;independentOpinionCount:number;commonCase:string|null;mainConcern:string|null;sources:string[];aiSummary:{summary:string;sourceIds:string[];inputHash:string;promptVersion:string;model:string;generatedAt:string}|null};
type Player={id:string;name:string;position:string;nflTeam:string|null;status:string;salePrice:number|null;draftedBy:string|null;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;productionValue:number|null;productionLabel:string;productionTier:number|null;projectedPoints:number;pointsAboveReplacement:number|null;replacementPoints:number|null;positionRank:number|null;byeWeek:number|null;marketAdp:number|null;birthDate:string|null;yearsOfExperience:number|null;riskFlags:string[];alternatives:Alternative[];lastSeasonStatLine:StatLine|null;historicalStatLines:StatLine[];projectedStatLine:StatLine|null;fantasyAnalysis:FantasyAnalysis[];analystConsensus:AnalystConsensus};
type Team={id:string;name:string;owner:string;remainingBudget:number;openSlots:number;rosteredCount:number;maxBid:number};
type Sale={id:string;pick:number;player:string;team:string;price:number};
type RosterSlot={slotId:string;teamId:string;slotType:string;ordinal:number;eligiblePositions:string[];playerId:string|null;player:string|null;position:string|null;byeWeek:number|null;pricePaid:number|null;positionRank:number|null;pointsAboveReplacement:number|null;productionLabel:string|null};
type NominationOrderTeam={teamId:string;ordinal:number;team:string;owner:string;openSlots:number;completedAt:string|null;waiverPriority:number|null};
type Nomination=(Player&{nominationId:string;playerId:string;nominator:string|null;nominatorTeamId:string|null})|null;
type DraftData={draft:{status:string;stateVersion:number};players:Player[];teams:Team[];renegades:Team|null;teamRosters:Record<string,RosterSlot[]>;currentNomination:Nomination;recentSales:Sale[];nominationOrder:{teams:NominationOrderTeam[];nextTeamId:string|null};sheetSync:{configured:boolean;pending:number;failed:number;lastError:string|null};researchStatus:{summaryRefreshNeeded:boolean;pendingPlayerCount:number;pendingTakeawayCount:number;pendingSourceCount:number;lastSummaryGeneratedAt:string|null};localSaved:boolean};
type SortKey="rank"|"name"|"position"|"team"|"bye"|"adp"|"age"|"actualPoints"|"points"|"xpar"|"tier"|"tierLeft"|"drop"|"price"|"range";
type PoolView="undrafted"|"drafted"|"all";

const positions=["ALL","QB","RB","WR","TE","RB/WR","RB/WR/TE","K","DEF"];
const playerPositions=["QB","RB","WR","TE","K","DEF"];
const money=(value:number|null|undefined)=>value==null?"—":`$${Math.round(value)}`;
const number=(value:number|null|undefined)=>value==null?"—":value.toFixed(1);
const tierTone=(label:string)=>label==="Elite"?styles.tierElite:label==="Premium"?styles.tierPremium:label==="Starter"?styles.tierStarter:label==="Depth"?styles.tierDepth:styles.tierReplacement;
const tierLabel=(label:string)=>label==="Replacement"?"Bench":label;
const playerAge=(birthDate:string|null)=>{if(!birthDate)return null;const born=new Date(`${birthDate}T00:00:00Z`),today=new Date();let age=today.getUTCFullYear()-born.getUTCFullYear();if(today.getUTCMonth()<born.getUTCMonth()||(today.getUTCMonth()===born.getUTCMonth()&&today.getUTCDate()<born.getUTCDate()))age--;return age;};
const seasonPoints=(player:Player,season:number)=>player.historicalStatLines.find(line=>line.season===season)?.fantasy_points??null;

type StatColumn={key:string;label:string};
function statColumns(position:string):StatColumn[]{if(position==="QB")return[{key:"games",label:"GP"},{key:"passing_completions",label:"CMP"},{key:"passing_attempts",label:"ATT"},{key:"passing_yards",label:"PASS YDS"},{key:"passing_tds",label:"PASS TD"},{key:"passing_interceptions",label:"INT"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"},{key:"fantasy_points",label:"FANTASY PTS"}];if(position==="K")return[{key:"games",label:"GP"},{key:"field_goals_attempted",label:"FGA"},{key:"field_goals_made",label:"FGM"},{key:"extra_points_made",label:"XPM"},{key:"fantasy_points",label:"FANTASY PTS"}];if(position==="DEF")return[{key:"games",label:"GP"},{key:"sacks",label:"SACK"},{key:"interceptions",label:"INT"},{key:"fumble_recoveries",label:"FR"},{key:"defensive_tds",label:"DEF TD"},{key:"special_teams_tds",label:"ST TD"},{key:"safeties",label:"SFTY"},{key:"fantasy_points",label:"FANTASY PTS"}];return[{key:"games",label:"GP"},{key:"targets",label:"TGT"},{key:"receptions",label:"REC"},{key:"receiving_yards",label:"REC YDS"},{key:"yards_per_reception",label:"Y/R"},{key:"receiving_tds",label:"REC TD"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"},{key:"fantasy_points",label:"FANTASY PTS"}];}
function statValue(line:StatLine,column:string){if(column==="games")return line.games;if(column==="fantasy_points")return line.fantasy_points;if(column==="yards_per_reception"){const receptions=line.stats.receptions,yards=line.stats.receiving_yards;return receptions&&yards!=null?yards/receptions:null;}return line.stats[column]??null;}

export function DraftBoard(){
  const [data,setData]=useState<DraftData|null>(null);
  const [error,setError]=useState("");
  const [busy,setBusy]=useState(false);
  const [query,setQuery]=useState("");
  const [position,setPosition]=useState("ALL");
  const [poolView,setPoolView]=useState<PoolView>("undrafted");
  const [sort,setSort]=useState<SortKey>("price");
  const [ascending,setAscending]=useState(false);
  const [expandedId,setExpandedId]=useState<string|null>(null);
  const [drawerOpen,setDrawerOpen]=useState(false);
  const [rosterTeamId,setRosterTeamId]=useState("");
  const [draggedPlayerId,setDraggedPlayerId]=useState<string|null>(null);
  const [dropSlotId,setDropSlotId]=useState<string|null>(null);
  const [saleOpen,setSaleOpen]=useState(false);
  const [winner,setWinner]=useState("");
  const [salePrice,setSalePrice]=useState("");
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [nominationOrderOpen,setNominationOrderOpen]=useState(false);
  const [nominationOrderDraft,setNominationOrderDraft]=useState<string[]>([]);
  const [nominatorTeamId,setNominatorTeamId]=useState("");
  const [resetOpen,setResetOpen]=useState(false);
  const [resetConfirmation,setResetConfirmation]=useState("");
  const [preservePreferences,setPreservePreferences]=useState(true);

  const load=useCallback(async()=>{try{const response=await fetch("/api/draft",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"The board could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{const focusSearch=(event:KeyboardEvent)=>{if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"){event.preventDefault();document.getElementById("board-player-search")?.focus();}};window.addEventListener("keydown",focusSearch);return()=>window.removeEventListener("keydown",focusSearch);},[]);
  useEffect(()=>{if(data)setNominatorTeamId(data.currentNomination?.nominatorTeamId??data.nominationOrder.nextTeamId??"");},[data?.currentNomination?.nominationId,data?.currentNomination?.nominatorTeamId,data?.nominationOrder.nextTeamId]);

  async function act(action:object){setBusy(true);setError("");try{const response=await fetch("/api/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setSaleOpen(false);}catch(reason){setError(reason instanceof Error?reason.message:"The action was not saved.");}finally{setBusy(false);}}

  const drops=useMemo(()=>{const result=new Map<string,number>();if(!data)return result;for(const pos of playerPositions){const rows=data.players.filter(player=>player.position===pos&&player.status!=="sold"&&player.status!=="removed").sort((a,b)=>(b.pointsAboveReplacement??0)-(a.pointsAboveReplacement??0));rows.forEach((player,index)=>result.set(player.id,Math.max(0,(player.pointsAboveReplacement??0)-(rows[index+1]?.pointsAboveReplacement??0))));}return result;},[data]);
  const overallRanks=useMemo(()=>{const ranks=new Map<string,number>();if(!data)return ranks;[...data.players].filter(player=>player.status!=="removed").sort((a,b)=>(b.pointsAboveReplacement??0)-(a.pointsAboveReplacement??0)||b.projectedPoints-a.projectedPoints||a.name.localeCompare(b.name)).forEach((player,index)=>ranks.set(player.id,index+1));return ranks;},[data]);
  const tierLeft=useMemo(()=>{const result=new Map<string,{count:number;names:string[]}>();if(!data)return result;const available=data.players.filter(player=>player.status!=="sold"&&player.status!=="removed");for(const player of data.players){const remaining=available.filter(other=>other.position===player.position&&other.productionTier===player.productionTier).sort((a,b)=>b.projectedPoints-a.projectedPoints);result.set(player.id,{count:remaining.length,names:remaining.map(other=>other.name)});}return result;},[data]);

  const rows=useMemo(()=>{if(!data)return[];const displayPrice=(player:Player)=>player.status==="sold"?player.salePrice:player.liveExpectedPrice??player.expectedPrice;const rangeWidth=(player:Player)=>Math.max(0,(player.livePriceHigh??player.priceHigh??0)-(player.livePriceLow??player.priceLow??0));const values=(player:Player):Record<SortKey,string|number>=>({rank:overallRanks.get(player.id)??9999,name:player.name,position:player.position,team:player.nflTeam??"ZZZ",bye:player.byeWeek??99,adp:player.marketAdp??9999,age:playerAge(player.birthDate)??999,actualPoints:seasonPoints(player,2025)??-1,points:player.projectedPoints,xpar:player.pointsAboveReplacement??-1,tier:player.productionTier??9999,tierLeft:tierLeft.get(player.id)?.count??0,drop:drops.get(player.id)??-1,price:displayPrice(player)??-1,range:rangeWidth(player)});const inPool=(player:Player)=>poolView==="all"?player.status!=="removed":poolView==="drafted"?player.status==="sold":player.status!=="sold"&&player.status!=="removed";const inPosition=(player:Player)=>position==="ALL"||(position==="RB/WR"?["RB","WR"].includes(player.position):position==="RB/WR/TE"?["RB","WR","TE"].includes(player.position):player.position===position);return data.players.filter(player=>inPool(player)&&inPosition(player)&&player.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const av=values(a)[sort],bv=values(b)[sort];const compared=typeof av==="string"?av.localeCompare(String(bv)):Number(av)-Number(bv);return compared*(ascending?1:-1);});},[ascending,data,drops,overallRanks,poolView,position,query,sort,tierLeft]);

  function chooseSort(key:SortKey){if(sort===key)setAscending(value=>!value);else{setSort(key);setAscending(["rank","name","position","team","bye","adp","age","tier","tierLeft"].includes(key));}}
  function moveNominationOwner(index:number,direction:-1|1){setNominationOrderDraft(order=>{const target=index+direction;if(target<0||target>=order.length)return order;const next=[...order];[next[index],next[target]]=[next[target]!,next[index]!];return next;});}
  const sortMark=(key:SortKey)=>sort===key?(ascending?" ↑":" ↓"):"";
  const teams=useMemo(()=>[...(data?.teams??[])].sort((a,b)=>a.owner.localeCompare(b.owner)),[data]);
  const rosterTeam=data?.teams.find(team=>team.id===(rosterTeamId||data.renegades?.id))??data?.renegades??teams[0]??null;
  const roster=rosterTeam?data?.teamRosters[rosterTeam.id]??[]:[];
  const strength=useMemo(()=>teams.map(team=>{const slots=data?.teamRosters[team.id]??[];const unique=slots.filter(slot=>slot.playerId);const byPosition=(pos:string)=>unique.filter(slot=>slot.position===pos).reduce((sum,slot)=>sum+(slot.pointsAboveReplacement??0),0);return{team,total:unique.reduce((sum,slot)=>sum+(slot.pointsAboveReplacement??0),0),QB:byPosition("QB"),RB:byPosition("RB"),WR:byPosition("WR"),TE:byPosition("TE")};}).sort((a,b)=>b.total-a.total),[data,teams]);

  if(!data)return <main className={styles.loading}><p>{error||"Opening the draft board…"}</p><button onClick={()=>void load()}>Try again</button></main>;
  const nomination=data.currentNomination;
  const nextNominator=data.teams.find(team=>team.id===data.nominationOrder.nextTeamId);
  const activeNominationOrder=data.nominationOrder.teams.filter(team=>team.openSlots>0);
  const nextNominationIndex=Math.max(0,activeNominationOrder.findIndex(team=>team.teamId===data.nominationOrder.nextTeamId));
  const nominationTicker=activeNominationOrder.length?Array.from({length:Math.min(3,activeNominationOrder.length)},(_,offset)=>activeNominationOrder[(nextNominationIndex+offset)%activeNominationOrder.length]!).filter(Boolean):[];

  return <main className={styles.app}>
    <header className={styles.header}>
      <div className={styles.brand}><img src="/branding/rodman-renegades-logo.png" alt=""/><strong>Renegade Draft Board</strong></div>
      <span className={styles.saved}>● Local state saved</span>
      <span className={data.sheetSync.failed?styles.syncError:styles.saved}>● {data.sheetSync.failed?"Sheet sync needs attention":data.sheetSync.pending?"Sheet sync pending":"Sheet synced"}</span>
      <button className={styles.headerAction} onClick={()=>setSettingsOpen(true)}>Draft settings</button>
      {data.researchStatus.summaryRefreshNeeded&&<span className={styles.researchBadge} title={`${data.researchStatus.pendingTakeawayCount} new takeaways from ${data.researchStatus.pendingSourceCount} sources affect ${data.researchStatus.pendingPlayerCount} players. Existing AI summaries remain available.`}>New research available</span>}
      <div className={styles.spacer}/>
      <div className={styles.nominationTicker}><small>Up next</small>{nominationTicker.map((team,index)=><span className={`${styles.tickerOwner} ${index===0?styles.tickerNext:""}`} key={team.teamId}><b>{index+1}</b>{team.owner}</span>)}</div>
      <span className={styles.budget}>Budget <b>{money(data.renegades?.remainingBudget)}</b></span>
      <span className={styles.budget}>Max bid <b>{money(data.renegades?.maxBid)}</b></span>
    </header>

    {data.draft.status==="setup"&&<section className={styles.setupBanner}><div><small>DRAFT READY</small><strong>Start the 2026 draft to enable nominations and sales.</strong></div><button className={styles.primary} disabled={busy} onClick={()=>void act({type:"start"})}>{busy?"Starting…":"Start draft"}</button></section>}

    <section className={`${styles.nomination} ${nomination?styles.nominationActive:""}`}>
      {nomination?<>
        <div><small>CURRENT NOMINATION</small><strong>{nomination.name}</strong><span>{nomination.position} · {nomination.nflTeam??"FA"}</span></div>
        <Metric label="BYE" value={nomination.byeWeek==null?"—":String(nomination.byeWeek)}/><Metric label="xPTS" value={number(nomination.projectedPoints)}/><Metric label="xPAR" value={number(nomination.pointsAboveReplacement)}/><Metric label="xTIER" value={tierLabel(nomination.productionLabel)}/><Metric label="SCARCITY" value={`${tierLeft.get(nomination.id)?.count??0} left`}/><Metric label="DROP" value={number(drops.get(nomination.id))}/><Metric label="xPRICE" value={money(nomination.liveExpectedPrice??nomination.expectedPrice)}/><Metric label="RANGE" value={`${money(nomination.livePriceLow??nomination.priceLow)}–${money(nomination.livePriceHigh??nomination.priceHigh)}`}/>
        <label className={styles.nominatorControl}><small>NOMINATED BY</small><select aria-label="Nominated by" value={nominatorTeamId} disabled={busy} onChange={event=>{setNominatorTeamId(event.target.value);void act({type:"changeNominationOwner",nominatedByTeamId:event.target.value});}}>{teams.map(team=><option value={team.id} key={team.id}>{team.owner}</option>)}</select></label>
        <button className={styles.secondary} disabled={busy} onClick={()=>void act({type:"cancelNomination"})}>Cancel nomination</button>
        <button className={styles.primary} disabled={busy} onClick={()=>{setWinner(data.renegades?.id??teams[0]?.id??"");setSalePrice(String(nomination.liveExpectedPrice??nomination.expectedPrice??1));setSaleOpen(true);}}>Enter winner</button>
      </>:<><div><small>CURRENT NOMINATION</small><strong>No player nominated</strong><span>{nextNominator?`${nextNominator.owner} nominates next`:"Select a player below"}</span></div><label className={styles.nominatorControl}><small>NOMINATED BY</small><select aria-label="Choose nominating owner" value={nominatorTeamId} onChange={event=>setNominatorTeamId(event.target.value)}>{teams.map(team=><option value={team.id} key={team.id}>{team.owner}</option>)}</select></label><p>Choose a player row, review the details, then nominate from the expanded row.</p></>}
    </section>

    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.board}>
      <div className={styles.tools}><label className={styles.searchBox} htmlFor="board-player-search"><span>Search</span><input id="board-player-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name"/><kbd>/</kbd></label>{positions.map(pos=><button key={pos} className={position===pos?styles.filterActive:""} onClick={()=>setPosition(pos)}>{pos}</button>)}<div className={styles.poolFilters}>{(["undrafted","drafted","all"] as PoolView[]).map(view=><button key={view} className={poolView===view?styles.filterActive:""} onClick={()=>setPoolView(view)}>{view[0]!.toUpperCase()+view.slice(1)}</button>)}</div></div>
      <div className={`${styles.grid} ${styles.columns}`}><button title="Overall rank based on xPAR" onClick={()=>chooseSort("rank")}>xRank{sortMark("rank")}</button><button onClick={()=>chooseSort("position")}>Pos{sortMark("position")}</button><button onClick={()=>chooseSort("name")}>Player{sortMark("name")}</button><button onClick={()=>chooseSort("team")}>Team{sortMark("team")}</button><button onClick={()=>chooseSort("bye")}>Bye{sortMark("bye")}</button><button title="Blended Yahoo and ESPN average draft position" onClick={()=>chooseSort("adp")}>ADP{sortMark("adp")}</button><button onClick={()=>chooseSort("age")}>Age{sortMark("age")}</button><button title="Actual 2025 fantasy points" onClick={()=>chooseSort("actualPoints")}>2025 PTS{sortMark("actualPoints")}</button><button onClick={()=>chooseSort("points")}>xPTS{sortMark("points")}</button><button onClick={()=>chooseSort("xpar")}>xPAR{sortMark("xpar")}</button><button onClick={()=>chooseSort("tier")}>xTier{sortMark("tier")}</button><button title="How many players remain at this player's position and production tier" onClick={()=>chooseSort("tierLeft")}>Scarcity{sortMark("tierLeft")}</button><button onClick={()=>chooseSort("drop")}>DROP{sortMark("drop")}</button><button onClick={()=>chooseSort("price")}>xPRICE{sortMark("price")}</button><button title="Sort by the width of the expected price range" onClick={()=>chooseSort("range")}>xPRICE Range{sortMark("range")}</button></div>
      <div className={styles.playerList}>{rows.map(player=><div key={player.id} className={styles.playerGroup}>
        <button className={`${styles.grid} ${styles.playerRow} ${poolView==="all"&&player.status==="sold"?styles.draftedRow:""} ${expandedId===player.id?styles.selectedRow:""} ${nomination?.id===player.id?styles.nominatedRow:""}`} onClick={()=>setExpandedId(current=>current===player.id?null:player.id)}>
          <span className={styles.rankValue}>{overallRanks.get(player.id)??"—"}</span><span><i className={styles.positionBadge}>{player.position}</i></span><span className={styles.playerName}><strong>{player.name}{player.status==="sold"&&player.draftedBy&&<small className={styles.draftedOwner}> → {player.draftedBy}</small>}</strong>{player.analystConsensus.action&&<i className={`${styles.analysisFlag} ${styles[`analysis${player.analystConsensus.action[0]!.toUpperCase()+player.analystConsensus.action.slice(1)}`]}`} title={`Fantasy analyst consensus: ${player.analystConsensus.action}`}>{player.analystConsensus.action==="target"?"↑":player.analystConsensus.action==="avoid"?"↓":"•"}</i>}</span><span className={styles.teamText}>{player.nflTeam??"FA"}</span><span>{player.byeWeek??"—"}</span><span>{player.marketAdp==null?"—":Math.round(player.marketAdp)}</span><span>{playerAge(player.birthDate)??"—"}</span><b>{number(seasonPoints(player,2025))}</b><b>{number(player.projectedPoints)}</b><b className={`${styles.xparText} ${tierTone(player.productionLabel)}`}>{number(player.pointsAboveReplacement)}</b><span><i className={`${styles.tierBadge} ${tierTone(player.productionLabel)}`} title={player.productionTier?`Production Tier ${player.productionTier}`:"Production tier unavailable"}>{tierLabel(player.productionLabel)}</i></span><b title={(()=>{const supply=tierLeft.get(player.id);if(!supply?.names.length)return"No players remain in this position-tier";const shown=supply.names.slice(0,5),more=supply.names.length-shown.length;return `${shown.join(", ")}${more>0?` +${more} more`:""}`;})()}>{tierLeft.has(player.id)?`${tierLeft.get(player.id)!.count} left`:"—"}</b><b><i className={(drops.get(player.id)??0)>=5?styles.dropBadgeHigh:styles.dropBadge}>{number(drops.get(player.id))}</i></b><b className={styles.priceValue}>{money(player.status==="sold"?player.salePrice:player.liveExpectedPrice??player.expectedPrice)}</b><span className={styles.rangeText}>{money(player.livePriceLow??player.priceLow)}–{money(player.livePriceHigh??player.priceHigh)}</span>
        </button>
        {expandedId===player.id&&<PlayerDetails player={player} busy={busy} nominated={Boolean(nomination)||data.draft.status!=="active"} officiallyNominated={nomination?.id===player.id} onOverride={override=>void act({type:"fantasyAnalysisOverride",playerId:player.id,override})} onNominate={()=>void act({type:"nominate",playerId:player.id,...(nominatorTeamId?{nominatedByTeamId:nominatorTeamId}:{})})}/>} 
      </div>)}</div>
    </section>

    <section className={`${styles.drawer} ${drawerOpen?styles.drawerOpen:""}`} style={drawerOpen?{height:`min(55vh, ${106+roster.length*27}px)`}:undefined}>
      <button className={styles.drawerToggle} aria-expanded={drawerOpen} onClick={()=>setDrawerOpen(open=>!open)}>{drawerOpen?"Close tables":"Draft tables"}</button>
      {drawerOpen&&<div className={styles.drawerBody}>
        <section className={styles.drawerPanel}><h2>League Strength</h2><div className={styles.panelContent}><StrengthTable rows={strength}/></div></section>
        <section className={styles.drawerPanel}><h2 className={styles.rosterPanelHeader}><span>Team Rosters</span><select aria-label="View team roster" value={rosterTeam?.id??""} onChange={event=>setRosterTeamId(event.target.value)}>{teams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><small>Budget <b>{money(rosterTeam?.remainingBudget)}</b></small><small>Max bid <b>{money(rosterTeam?.maxBid)}</b></small></h2><div className={styles.panelContent}><RosterTable roster={roster} busy={busy} draggedPlayerId={draggedPlayerId} dropSlotId={dropSlotId} onDrag={setDraggedPlayerId} onDropTarget={setDropSlotId} onMove={(playerId,targetSlotId)=>rosterTeam&&void act({type:"reassignRosterSlot",teamId:rosterTeam.id,playerId,targetSlotId})}/></div></section>
        <section className={styles.drawerPanel}><h2>Draft History <span>{data.recentSales.length}</span></h2><div className={styles.panelContent}><History sales={data.recentSales} busy={busy} onUndo={sale=>{if(window.confirm(`Undo ${sale.player}'s pick?`))void act({type:"voidSale",saleId:sale.id});}}/></div></section>
      </div>}
    </section>

    {saleOpen&&nomination&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setSaleOpen(false);}}><section className={styles.modal}><small>FINAL SALE</small><h2>Record {nomination.name}</h2><label>Winning owner<select value={winner} onChange={event=>setWinner(event.target.value)}>{teams.map(team=><option value={team.id} key={team.id}>{team.owner} · {money(team.remainingBudget)} left</option>)}</select></label><label>Sale price<input type="number" min="1" value={salePrice} onChange={event=>setSalePrice(event.target.value)}/></label><div><button className={styles.secondary} onClick={()=>setSaleOpen(false)}>Cancel</button><button className={styles.primary} disabled={busy||!winner||!Number(salePrice)} onClick={()=>void act({type:"sale",winnerTeamId:winner,price:Number(salePrice)})}>Confirm sale</button></div></section></div>}
    {settingsOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setSettingsOpen(false);}}><section className={`${styles.modal} ${styles.settingsModal}`}><div className={styles.settingsHeading}><h2>Draft settings</h2><button aria-label="Close draft settings" onClick={()=>setSettingsOpen(false)}>×</button></div><nav className={styles.settingsMenu}><button onClick={()=>{setSettingsOpen(false);setNominationOrderDraft(data.nominationOrder.teams.map(team=>team.teamId));setNominationOrderOpen(true);}}><i>1</i><span><strong>Nomination order</strong><small>View or change the owner rotation</small></span><b>›</b></button><button disabled><i>2</i><span><strong>Draft strategy</strong><small>Strategy preferences will be managed here</small></span><em>Coming soon</em></button><button className={styles.settingsDangerItem} onClick={()=>{setSettingsOpen(false);setResetConfirmation("");setPreservePreferences(true);setResetOpen(true);}}><i>!</i><span><strong>Reset draft</strong><small>Back up and clear the current draft</small></span><b>›</b></button></nav></section></div>}
    {nominationOrderOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setNominationOrderOpen(false);}}><section className={`${styles.modal} ${styles.orderModal}`}><small>DRAFT ROTATION</small><h2>Nomination order</h2><div className={styles.orderList}>{nominationOrderDraft.map((teamId,index)=>{const team=data.nominationOrder.teams.find(item=>item.teamId===teamId);if(!team)return null;return <div className={`${styles.orderRow} ${data.nominationOrder.nextTeamId===teamId?styles.nextOwner:""}`} key={teamId}><b>{index+1}</b><span><strong>{team.owner}</strong><small>{team.completedAt?`Draft complete · waiver #${team.waiverPriority}`:data.nominationOrder.nextTeamId===teamId?"Next to nominate":`${team.openSlots} spots open`}</small></span><div><button disabled={index===0} onClick={()=>moveNominationOwner(index,-1)}>↑</button><button disabled={index===nominationOrderDraft.length-1} onClick={()=>moveNominationOwner(index,1)}>↓</button></div></div>;})}</div><div><button className={styles.secondary} onClick={()=>setNominationOrderOpen(false)}>Cancel</button><button className={styles.primary} disabled={busy} onClick={()=>void act({type:"updateNominationOrder",teamIds:nominationOrderDraft}).then(()=>setNominationOrderOpen(false))}>Save order</button></div></section></div>}
    {resetOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setResetOpen(false);}}><section className={styles.modal}><small>RECOVERABLE RESET</small><h2>Reset the draft?</h2><p className={styles.modalCopy}>This creates a timestamped backup, restores all budgets and roster slots, and clears the active draft history.</p><label className={styles.resetChoice}><input type="checkbox" checked={preservePreferences} onChange={event=>setPreservePreferences(event.target.checked)}/><span>Keep Renegades preferences</span></label><label>Type RESET to confirm<input value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)} placeholder="RESET"/></label><div><button className={styles.secondary} onClick={()=>setResetOpen(false)}>Cancel</button><button className={styles.danger} disabled={busy||resetConfirmation!=="RESET"} onClick={()=>void act({type:"resetDraft",confirmation:resetConfirmation,preservePreferences}).then(()=>setResetOpen(false))}>Reset draft</button></div></section></div>}
  </main>;
}

function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><small>{label}</small><strong>{value}</strong></div>}

function PlayerDetails({player,busy,nominated,officiallyNominated,onOverride,onNominate}:{player:Player;busy:boolean;nominated:boolean;officiallyNominated:boolean;onOverride:(override:"auto"|"target"|"avoid"|"off")=>void;onNominate:()=>void}){
  const sold=player.status==="sold",consensus=player.analystConsensus,age=playerAge(player.birthDate);
  return <div className={`${styles.details} ${officiallyNominated?styles.detailsNominated:""}`}>
    <header className={styles.detailPlayerHeader}>
      <div className={styles.detailPlayerIdentity}><h3>{player.name}</h3><p>{player.position} · {player.nflTeam??"FA"} · Bye {player.byeWeek??"—"}{age!=null?` · Age ${age}`:""}{player.yearsOfExperience!=null?` · ${player.yearsOfExperience} NFL season${player.yearsOfExperience===1?"":"s"}`:""}</p></div>
      <div className={styles.detailHeaderActions}>
        <div className={styles.overrideControls}><span>Analyst flag</span>{(["auto","target","avoid","off"] as const).map(value=><button key={value} disabled={busy} className={(value==="auto"&&consensus.override===null)||consensus.override===value?styles.overrideActive:""} onClick={()=>onOverride(value)}>{value==="off"?"Hide":value[0]!.toUpperCase()+value.slice(1)}</button>)}</div>
        <button className={styles.primary} disabled={busy||nominated||sold} onClick={onNominate}>{sold?`Drafted by ${player.draftedBy??"another team"}`:nominated?"Finish current nomination first":"Nominate player"}</button>
      </div>
    </header>
    <section className={`${styles.consensusCard} ${styles.detailConsensus}`} aria-label="Fantasy analysis" />
    <PlayerStatTable player={player}/>
  </div>
}

function PlayerStatTable({player}:{player:Player}){const columns=statColumns(player.position),history=[...(player.historicalStatLines??[])].sort((a,b)=>a.season-b.season),lines=[...history.map(line=>({line,projected:false})),{line:player.projectedStatLine,projected:true}];return <div className={styles.statTable}><table><thead><tr><th>Season</th>{columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{lines.map(({line,projected},index)=>line?<tr className={projected?styles.projectedStats:""} key={`${line.season}-${index}`}><th>{projected?`x${line.season}`:line.season}</th>{columns.map(column=>{const value=statValue(line,column.key);return <td key={column.key}>{value==null?"—":projected?Number(value).toFixed(1):Number.isInteger(value)?value:Number(value).toFixed(1)}</td>;})}</tr>:<tr key={`missing-${index}`}><th>Projection</th><td colSpan={columns.length}>No stat line available</td></tr>)}</tbody></table></div>}

type StrengthRow={team:Team;total:number;QB:number;RB:number;WR:number;TE:number};
function heatClass(rows:StrengthRow[],key:"QB"|"RB"|"WR"|"TE"|"total",value:number){if(value<=0)return styles.heatLowest;const values=rows.map(row=>row[key]).filter(item=>item>0),minimum=Math.min(...values),maximum=Math.max(...values);if(maximum===minimum)return styles.heatHighest;const score=(value-minimum)/(maximum-minimum);return score>=.8?styles.heatHighest:score>=.6?styles.heatHigh:score>=.4?styles.heatMiddle:score>=.2?styles.heatLow:styles.heatLowest;}
function StrengthTable({rows}:{rows:StrengthRow[]}){return <div className={`${styles.tableWrap} ${styles.strengthTable}`}><table><thead><tr><th>Rank</th><th>Owner</th><th>QB</th><th>RB</th><th>WR</th><th>TE</th><th>Total</th><th>MaxBid</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.team.id}><td>{index+1}</td><td><strong>{row.team.owner}</strong></td><td className={heatClass(rows,"QB",row.QB)}>{number(row.QB)}</td><td className={heatClass(rows,"RB",row.RB)}>{number(row.RB)}</td><td className={heatClass(rows,"WR",row.WR)}>{number(row.WR)}</td><td className={heatClass(rows,"TE",row.TE)}>{number(row.TE)}</td><td className={heatClass(rows,"total",row.total)}><strong>{number(row.total)}</strong></td><td>{money(row.team.maxBid)}</td></tr>)}</tbody></table></div>}

function RosterTable({roster,busy,draggedPlayerId,dropSlotId,onDrag,onDropTarget,onMove}:{roster:RosterSlot[];busy:boolean;draggedPlayerId:string|null;dropSlotId:string|null;onDrag:(id:string|null)=>void;onDropTarget:(id:string|null)=>void;onMove:(playerId:string,targetSlotId:string)=>void}){return <div className={styles.tableWrap}><table><thead><tr><th>Slot</th><th>Player</th><th>Pos</th><th>Bye</th><th>Paid</th><th>xPAR</th></tr></thead><tbody>{roster.map(slot=><tr key={slot.slotId} className={`${slot.playerId?styles.rosterDraggable:""} ${dropSlotId===slot.slotId?styles.dropTarget:""}`} draggable={Boolean(slot.playerId)&&!busy} onDragStart={event=>{if(!slot.playerId)return;onDrag(slot.playerId);event.dataTransfer.setData("text/plain",slot.playerId);}} onDragEnd={()=>{onDrag(null);onDropTarget(null);}} onDragOver={event=>{if(draggedPlayerId){event.preventDefault();onDropTarget(slot.slotId);}}} onDrop={event=>{event.preventDefault();const id=draggedPlayerId||event.dataTransfer.getData("text/plain");onDrag(null);onDropTarget(null);if(id)onMove(id,slot.slotId);}}><td>{slot.slotType.replaceAll("_","/")}</td><td><strong>{slot.player??""}</strong></td><td>{slot.position??""}</td><td>{slot.byeWeek??""}</td><td>{slot.pricePaid==null?"":money(slot.pricePaid)}</td><td>{slot.pointsAboveReplacement==null?"":number(slot.pointsAboveReplacement)}</td></tr>)}</tbody></table></div>}

function History({sales,busy,onUndo}:{sales:Sale[];busy:boolean;onUndo:(sale:Sale)=>void}){return <div className={styles.tableWrap}>{sales.length?<table><thead><tr><th>Pick</th><th>Player</th><th>Team</th><th>Price</th><th/></tr></thead><tbody>{sales.map(sale=><tr key={sale.id}><td>#{sale.pick}</td><td><strong>{sale.player}</strong></td><td>{sale.team}</td><td>{money(sale.price)}</td><td><button disabled={busy} onClick={()=>onUndo(sale)}>Undo pick</button></td></tr>)}</tbody></table>:<p>No completed sales yet.</p>}</div>}
