"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./DraftBoard.module.css";
import fullWriteupStyles from "./FullWriteupModal.module.css";
import {ResearchWriteup} from "../research/ResearchWriteup";

type StatLine={season:number;games:number|null;fantasy_points:number;stats:Record<string,number>;source:string};
type Alternative={id:string;name:string;nflTeam:string|null;projectedPoints:number;pointsAboveReplacement:number|null;productionTier:number|null;liveExpectedPrice:number|null;productionLabel:string};
type FantasyAnalysis={label:string;sentiment:string;summary:string;rationale:string;risks:string[];sourceTitle:string;author:string|null;url:string;publishedAt:string};
type PlayerNews={id:string;title:string;description:string|null;impact:string|null;author:string|null;createdAt:string|null;url:string|null};
type PlayerInjury={status:string|null;statusShort:string|null;injuryType:string|null;comment:string|null;updatedAt:string|null;probabilityOfPlaying:string|null;practiceReportInjuryType:string|null;practice:string[];irWeeks:number[]};
type AnalystConsensus={action:"target"|"avoid"|null;derivedAction:"target"|"avoid"|null;override:"target"|"avoid"|"off"|null;tags:string[];derivedTags:string[];tagOverrides:Record<string,boolean>;positiveCount:number;negativeCount:number;independentOpinionCount:number;pros:string[];cons:string[];commonCase:string|null;mainConcern:string|null;sources:string[];aiSummary:{cardSummary:string;fullWriteup:string|null;prosSummary:string|null;consSummary:string|null;sourceIds:string[];inputHash:string;promptVersion:string;model:string;generatedAt:string}|null};
type ResearchTag="sleeper"|"breakout"|"value"|"bust";
type DraftImpact={band:string;label:string;expectedEquityDelta:number;scenarioSupport:number;summary:string};
type AssistantNote={text:string;tone:"positive"|"negative"|"neutral";priority:number};
type SituationSignal={key:string;text:string;tone:"positive"|"negative"|"neutral";priority:number};
type TeamDepthChart={QB:string[];RB:string[];WR:string[];TE:string[]};
type UpcomingTarget={rank:number;playerId:string};
type Player={id:string;name:string;position:string;nflTeam:string|null;status:string;salePrice:number|null;draftedBy:string|null;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;productionValue:number|null;productionLabel:string;productionTier:number|null;projectedPoints:number;pointsAboveReplacement:number|null;replacementPoints:number|null;positionRank:number|null;byeWeek:number|null;marketAdp:number|null;birthDate:string|null;yearsOfExperience:number|null;riskFlags:string[];situationSignals:SituationSignal[];alternatives:Alternative[];injury:PlayerInjury|null;recentNews:PlayerNews[];teamDepthChart:TeamDepthChart|null;lastSeasonStatLine:StatLine|null;historicalStatLines:StatLine[];projectedStatLine:StatLine|null;fantasyAnalysis:FantasyAnalysis[];analystConsensus:AnalystConsensus;decisionCeiling?:number|null;decisionEdge?:number|null;draftImpact?:DraftImpact|null;decisionPlan?:{recommendedCeiling:number;committedCeiling:number}|null;championshipDecision?:{band:string;support:number;medianDelta:number;tiers:{from:number;to:number;band:string}[]}|null};
type Team={id:string;name:string;owner:string;remainingBudget:number;openSlots:number;rosteredCount:number;maxBid:number};
type Sale={id:string;pick:number;player:string;team:string;price:number};
type RosterSlot={slotId:string;teamId:string;slotType:string;ordinal:number;eligiblePositions:string[];playerId:string|null;player:string|null;position:string|null;byeWeek:number|null;pricePaid:number|null;positionRank:number|null;pointsAboveReplacement:number|null;productionLabel:string|null};
type NominationOrderTeam={teamId:string;ordinal:number;team:string;owner:string;openSlots:number;completedAt:string|null;waiverPriority:number|null};
type Nomination=(Player&{nominationId:string;playerId:string;nominator:string|null;nominatorTeamId:string|null})|null;
type DraftData={draft:{status:string;stateVersion:number};players:Player[];teams:Team[];renegades:Team|null;teamRosters:Record<string,RosterSlot[]>;currentNomination:Nomination;recentSales:Sale[];upcomingTargets:UpcomingTarget[];nominationOrder:{teams:NominationOrderTeam[];nextTeamId:string|null};sheetSync:{configured:boolean;pending:number;failed:number;lastError:string|null};researchStatus:{summaryRefreshNeeded:boolean;pendingPlayerCount:number;pendingTakeawayCount:number;pendingSourceCount:number;lastSummaryGeneratedAt:string|null};localSaved:boolean};
type SortKey="rank"|"name"|"position"|"team"|"bye"|"adp"|"age"|"actualPoints"|"points"|"xpar"|"tier"|"tierLeft"|"drop"|"price"|"range"|"value"|"equity"|"targetRank";
type PoolView="undrafted"|"drafted"|"all";

const positions=["ALL","QB","RB","WR","TE","RB/WR","RB/WR/TE","K","DEF"];
const playerPositions=["QB","RB","WR","TE","K","DEF"];
const money=(value:number|null|undefined)=>value==null?"—":`$${Math.round(value)}`;
const number=(value:number|null|undefined)=>value==null?"—":value.toFixed(1);
const tierTone=(label:string)=>label==="Elite"?styles.tierElite:label==="Premium"?styles.tierPremium:label==="Starter"?styles.tierStarter:label==="Depth"?styles.tierDepth:styles.tierReplacement;
const tierLabel=(label:string)=>label==="Replacement"?"Bench":label;
const impactLabel=(impact:DraftImpact|null|undefined)=>impact?({strong_pursue:"Great",lean_pursue:"Good",neutral:"Neutral",lean_pass:"Poor",strong_pass:"Bad"} as Record<string,string>)[impact.band]??impact.label.replace(" Add",""):"—";
const impactOrder=(impact:DraftImpact|null|undefined)=>impact?({strong_pursue:1,lean_pursue:2,neutral:3,lean_pass:4,strong_pass:5} as Record<string,number>)[impact.band]??99:99;
const equityLabel=(impact:DraftImpact|null|undefined)=>impact?`${impact.expectedEquityDelta>=0?"+":""}${(impact.expectedEquityDelta*100).toFixed(1)}%`:"—";
const playerAge=(birthDate:string|null)=>{if(!birthDate)return null;const born=new Date(`${birthDate}T00:00:00Z`),today=new Date();let age=today.getUTCFullYear()-born.getUTCFullYear();if(today.getUTCMonth()<born.getUTCMonth()||(today.getUTCMonth()===born.getUTCMonth()&&today.getUTCDate()<born.getUTCDate()))age--;return age;};
const contextDate=(value:string|null)=>{if(!value)return null;const parsed=new Date(`${value.replace(" ","T")}${value.includes("Z")||value.includes("+")?"":"Z"}`);return Number.isNaN(parsed.valueOf())?value:parsed.toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"});};
const injurySummary=(injury:PlayerInjury)=>{const probability=injury.probabilityOfPlaying==null?null:Number(injury.probabilityOfPlaying),probabilityLabel=probability==null||Number.isNaN(probability)?null:`${Math.round((probability<=1?probability*100:probability)*10)/10}% probability of playing`;return [injury.status,injury.injuryType??injury.practiceReportInjuryType,injury.comment,probabilityLabel,injury.practice.length?`Practice: ${injury.practice.join(" / ")}`:null,injury.irWeeks.length?`IR weeks: ${injury.irWeeks.join(", ")}`:null].filter(Boolean).join(" · ");};
const seasonPoints=(player:Player,season:number)=>player.historicalStatLines.find(line=>line.season===season)?.fantasy_points??null;

type StatColumn={key:string;label:string};
function statColumns(position:string):StatColumn[]{if(position==="QB")return[{key:"games",label:"GP"},{key:"passing_completions",label:"CMP"},{key:"passing_attempts",label:"ATT"},{key:"passing_yards",label:"PASS YDS"},{key:"passing_tds",label:"PASS TD"},{key:"passing_interceptions",label:"INT"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"},{key:"fantasy_points",label:"FANTASY PTS"}];if(position==="K")return[{key:"games",label:"GP"},{key:"field_goals_attempted",label:"FGA"},{key:"field_goals_made",label:"FGM"},{key:"extra_points_made",label:"XPM"},{key:"fantasy_points",label:"FANTASY PTS"}];if(position==="DEF")return[{key:"games",label:"GP"},{key:"sacks",label:"SACK"},{key:"interceptions",label:"INT"},{key:"fumble_recoveries",label:"FR"},{key:"defensive_tds",label:"DEF TD"},{key:"special_teams_tds",label:"ST TD"},{key:"safeties",label:"SFTY"},{key:"fantasy_points",label:"FANTASY PTS"}];return[{key:"games",label:"GP"},{key:"targets",label:"TGT"},{key:"receptions",label:"REC"},{key:"receiving_yards",label:"REC YDS"},{key:"yards_per_reception",label:"Y/R"},{key:"receiving_tds",label:"REC TD"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"},{key:"fantasy_points",label:"FANTASY PTS"}];}
function statValue(line:StatLine,column:string){if(column==="games")return line.games;if(column==="fantasy_points")return line.fantasy_points;if(column==="yards_per_reception"){const receptions=line.stats.receptions,yards=line.stats.receiving_yards;return receptions&&yards!=null?yards/receptions:null;}return line.stats[column]??null;}

export function DraftBoard(){
  const [data,setData]=useState<DraftData|null>(null);
  const [error,setError]=useState("");
  const [busy,setBusy]=useState(false);
  const [query,setQuery]=useState("");
  const [position,setPosition]=useState("ALL");
  const [poolView,setPoolView]=useState<PoolView>("undrafted");
  const [sort,setSort]=useState<SortKey>("price");
  const [ascending,setAscending]=useState(false);
  const [expandedId,setExpandedId]=useState<string|null>(null);
  const [drawerOpen,setDrawerOpen]=useState(false);
  const [rosterTeamId,setRosterTeamId]=useState("");
  const [draggedPlayerId,setDraggedPlayerId]=useState<string|null>(null);
  const [dropSlotId,setDropSlotId]=useState<string|null>(null);
  const [winner,setWinner]=useState("");
  const [salePrice,setSalePrice]=useState("");
  const [settingsOpen,setSettingsOpen]=useState(false);
  const [nominationOrderOpen,setNominationOrderOpen]=useState(false);
  const [nominationOrderDraft,setNominationOrderDraft]=useState<string[]>([]);
  const [nominatorTeamId,setNominatorTeamId]=useState("");
  const [resetOpen,setResetOpen]=useState(false);
  const [resetConfirmation,setResetConfirmation]=useState("");
  const [preservePreferences,setPreservePreferences]=useState(true);

  const load=useCallback(async()=>{try{const response=await fetch("/api/draft",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"The board could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{const focusSearch=(event:KeyboardEvent)=>{if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"){event.preventDefault();document.getElementById("board-player-search")?.focus();}};window.addEventListener("keydown",focusSearch);return()=>window.removeEventListener("keydown",focusSearch);},[]);
  useEffect(()=>{if(data)setNominatorTeamId(data.currentNomination?.nominatorTeamId??data.nominationOrder.nextTeamId??"");},[data?.currentNomination?.nominationId,data?.currentNomination?.nominatorTeamId,data?.nominationOrder.nextTeamId]);
  useEffect(()=>{const nomination=data?.currentNomination;if(!nomination){setWinner("");setSalePrice("");return;}setWinner("");setSalePrice(String(nomination.liveExpectedPrice??nomination.expectedPrice??1));},[data?.currentNomination?.nominationId]);

  async function act(action:object){setBusy(true);setError("");try{const response=await fetch("/api/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);}catch(reason){setError(reason instanceof Error?reason.message:"The action was not saved.");}finally{setBusy(false);}}

  const drops=useMemo(()=>{const result=new Map<string,number>();if(!data)return result;for(const pos of playerPositions){const rows=data.players.filter(player=>player.position===pos&&player.status!=="sold"&&player.status!=="removed").sort((a,b)=>(b.pointsAboveReplacement??0)-(a.pointsAboveReplacement??0));rows.forEach((player,index)=>result.set(player.id,Math.max(0,(player.pointsAboveReplacement??0)-(rows[index+1]?.pointsAboveReplacement??0))));}return result;},[data]);
  const overallRanks=useMemo(()=>{const ranks=new Map<string,number>();if(!data)return ranks;[...data.players].filter(player=>player.status!=="removed").sort((a,b)=>(b.pointsAboveReplacement??0)-(a.pointsAboveReplacement??0)||b.projectedPoints-a.projectedPoints||a.name.localeCompare(b.name)).forEach((player,index)=>ranks.set(player.id,index+1));return ranks;},[data]);
  const targetRanks=useMemo(()=>new Map((data?.upcomingTargets??[]).map(target=>[target.playerId,target.rank])),[data?.upcomingTargets]);
  const tierLeft=useMemo(()=>{const result=new Map<string,{count:number;names:string[]}>();if(!data)return result;const available=data.players.filter(player=>player.status!=="sold"&&player.status!=="removed");for(const player of data.players){const remaining=available.filter(other=>other.position===player.position&&other.productionTier===player.productionTier).sort((a,b)=>b.projectedPoints-a.projectedPoints);result.set(player.id,{count:remaining.length,names:remaining.map(other=>other.name)});}return result;},[data]);
  const rows=useMemo(()=>{if(!data)return[];const displayPrice=(player:Player)=>player.status==="sold"?player.salePrice:player.liveExpectedPrice??player.expectedPrice;const rangeWidth=(player:Player)=>Math.max(0,(player.livePriceHigh??player.priceHigh??0)-(player.livePriceLow??player.priceLow??0));const values=(player:Player):Record<SortKey,string|number>=>({rank:overallRanks.get(player.id)??9999,name:player.name,position:player.position,team:player.nflTeam??"ZZZ",bye:player.byeWeek??99,adp:player.marketAdp??9999,age:playerAge(player.birthDate)??999,actualPoints:seasonPoints(player,2025)??-1,points:player.projectedPoints,xpar:player.pointsAboveReplacement??-1,tier:player.productionTier??9999,tierLeft:tierLeft.get(player.id)?.count??0,drop:drops.get(player.id)??-1,price:displayPrice(player)??-1,range:rangeWidth(player),value:impactOrder(player.draftImpact),equity:player.draftImpact?.expectedEquityDelta??-999,targetRank:targetRanks.get(player.id)??9999});const inPool=(player:Player)=>poolView==="all"?player.status!=="removed":poolView==="drafted"?player.status==="sold":player.status!=="sold"&&player.status!=="removed";const inPosition=(player:Player)=>position==="ALL"||(position==="RB/WR"?["RB","WR"].includes(player.position):position==="RB/WR/TE"?["RB","WR","TE"].includes(player.position):player.position===position);return data.players.filter(player=>inPool(player)&&inPosition(player)&&player.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const av=values(a)[sort],bv=values(b)[sort];const compared=typeof av==="string"?av.localeCompare(String(bv)):Number(av)-Number(bv);return compared*(ascending?1:-1);});},[ascending,data,drops,overallRanks,poolView,position,query,sort,targetRanks,tierLeft]);

  function chooseSort(key:SortKey){if(sort===key)setAscending(value=>!value);else{setSort(key);setAscending(["rank","name","position","team","bye","adp","age","tier","tierLeft","value","targetRank"].includes(key));}}
  function moveNominationOwner(index:number,direction:-1|1){setNominationOrderDraft(order=>{const target=index+direction;if(target<0||target>=order.length)return order;const next=[...order];[next[index],next[target]]=[next[target]!,next[index]!];return next;});}
  const sortMark=(key:SortKey)=>sort===key?(ascending?" ↑":" ↓"):"";
  const teams=useMemo(()=>[...(data?.teams??[])].sort((a,b)=>a.owner.localeCompare(b.owner)),[data]);
  const rosterTeam=data?.teams.find(team=>team.id===(rosterTeamId||data.renegades?.id))??data?.renegades??teams[0]??null;
  const roster=rosterTeam?data?.teamRosters[rosterTeam.id]??[]:[];
  const strength=useMemo(()=>teams.map(team=>{const slots=data?.teamRosters[team.id]??[];const unique=slots.filter(slot=>slot.playerId);const byPosition=(pos:string)=>unique.filter(slot=>slot.position===pos).reduce((sum,slot)=>sum+(slot.pointsAboveReplacement??0),0);return{team,total:unique.reduce((sum,slot)=>sum+(slot.pointsAboveReplacement??0),0),QB:byPosition("QB"),RB:byPosition("RB"),WR:byPosition("WR"),TE:byPosition("TE")};}).sort((a,b)=>b.total-a.total),[data,teams]);

  if(!data)return <main className={styles.loading}><img src="/branding/rodman-renegades-logo.png" alt="Rodman Renegades"/><strong>Draft room loading</strong>{error&&<><p>{error}</p><button onClick={()=>void load()}>Try again</button></>}</main>;
  const nomination=data.currentNomination;
  const nominationBandNames=["Great","Good","Neutral","Poor","Bad"] as const,nominationBandKeys=["strong_pursue","lean_pursue","neutral","lean_pass","strong_pass"];
  const nominationPriceBands=nominationBandNames.map((label,index)=>{const tiers=nomination?.championshipDecision?.tiers.filter(tier=>tier.band===nominationBandKeys[index])??[];return{label,range:tiers.map(tier=>tier.from===tier.to?money(tier.from):`${money(tier.from)}–${money(tier.to)}`).join(", ")};}).filter(band=>band.range);
  const nextNominator=data.teams.find(team=>team.id===data.nominationOrder.nextTeamId);
  const activeNominationOrder=data.nominationOrder.teams.filter(team=>team.openSlots>0);
  const nextNominationIndex=Math.max(0,activeNominationOrder.findIndex(team=>team.teamId===data.nominationOrder.nextTeamId));
  const nominationTicker=activeNominationOrder.length?Array.from({length:Math.min(3,activeNominationOrder.length)},(_,offset)=>activeNominationOrder[(nextNominationIndex+offset)%activeNominationOrder.length]!).filter(Boolean):[];

  return <main className={styles.app}>
    <header className={styles.header}>
      <div className={styles.brand}><img src="/branding/rodman-renegades-logo.png" alt=""/><strong>Renegade Draft Board</strong></div>
      <span className={styles.saved}>● Local state saved</span>
      <span className={data.sheetSync.failed?styles.syncError:styles.saved}>● {data.sheetSync.failed?"Sheet sync needs attention":data.sheetSync.pending?"Sheet sync pending":"Sheet synced"}</span>
      <button className={styles.headerAction} onClick={()=>setSettingsOpen(true)}>Draft settings</button>
      <a className={styles.headerAction} href="/research" target="_blank" rel="noreferrer">Research wiki</a>
      {data.researchStatus.summaryRefreshNeeded&&<span className={styles.researchBadge} title={`${data.researchStatus.pendingTakeawayCount} new takeaways from ${data.researchStatus.pendingSourceCount} sources affect ${data.researchStatus.pendingPlayerCount} players. Existing AI summaries remain available.`}>New research available</span>}
      <div className={styles.spacer}/>
      <div className={styles.nominationTicker}><small>Up next</small>{nominationTicker.map((team,index)=><span className={`${styles.tickerOwner} ${index===0?styles.tickerNext:""}`} key={team.teamId}><b>{index+1}</b>{team.owner}</span>)}</div>
      <span className={styles.budget}>Budget <b>{money(data.renegades?.remainingBudget)}</b></span>
      <span className={styles.budget}>Max bid <b>{money(data.renegades?.maxBid)}</b></span>
    </header>

    {data.draft.status==="setup"&&<section className={styles.setupBanner}><div><small>DRAFT READY</small><strong>Start the 2026 draft to enable nominations and sales.</strong></div><button className={styles.primary} disabled={busy} onClick={()=>void act({type:"start"})}>{busy?"Starting…":"Start draft"}</button></section>}

    <section className={`${styles.nomination} ${nomination?`${styles.nominationActive} ${styles.nominationAligned}`:""}`}>
      {nomination?<>
        <PlayerStatHeaderRow player={nomination} rank={overallRanks.get(nomination.id)??null} drop={drops.get(nomination.id)??null} tierRemaining={tierLeft.get(nomination.id)?.count??0} targetRank={targetRanks.get(nomination.id)??null}/>
        <form className={styles.nominationActions} onSubmit={event=>{event.preventDefault();if(winner&&Number(salePrice)>0)void act({type:"sale",winnerTeamId:winner,price:Number(salePrice)});}}>{nominationPriceBands.length>0&&<div className={styles.priceLadderControl}><small>PRICE LADDER</small><div className={`${styles.priceLadder} ${styles.nominationPriceLadder}`} aria-label="Decision price ladder">{nominationPriceBands.map(band=><div className={styles[`price${band.label}`]} key={band.label}><span>{band.label}</span><b>{band.range}</b></div>)}</div></div>}<label className={styles.nominatorControl}><small>NOMINATED BY</small><TeamCombobox id="nominated-by-options" ariaLabel="Nominated by" nextFocusId="cancel-nomination" teams={teams} value={nominatorTeamId} disabled={busy} onChange={teamId=>{setNominatorTeamId(teamId);void act({type:"changeNominationOwner",nominatedByTeamId:teamId});}}/></label>
        <div className={styles.actionControl}><small>NOMINATION</small><button id="cancel-nomination" type="button" className={styles.secondary} disabled={busy} onClick={()=>void act({type:"cancelNomination"})}>Cancel</button></div>
        <label className={styles.saleControl}><small>WINNING OWNER</small><TeamCombobox id="winning-owner-options" ariaLabel="Winning owner" nextFocusId="winning-bid" teams={teams} value={winner} disabled={busy} onChange={setWinner}/></label>
        <label className={`${styles.saleControl} ${styles.bidControl}`}><small>WINNING BID</small><input id="winning-bid" aria-label="Winning bid" type="number" min="1" value={salePrice} disabled={busy} onFocus={event=>event.currentTarget.select()} onChange={event=>setSalePrice(event.target.value)}/></label>
        <div className={styles.actionControl}><small>SALE</small><button type="submit" className={styles.primary} disabled={busy||!winner||!Number(salePrice)}>Enter</button></div></form>
      </>:<><div><small>CURRENT NOMINATION</small><strong>No player nominated</strong><span>{nextNominator?`${nextNominator.owner} nominates next`:"Select a player below"}</span></div><p>Choose a player row, review the details, then nominate from the expanded row.</p></>}
    </section>

    {error&&<div className={styles.error}>{error}</div>}
    <section className={styles.board}>
      <div className={styles.tools}><label className={styles.searchBox} htmlFor="board-player-search"><span>Search</span><input id="board-player-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name"/><kbd>/</kbd></label>{positions.map(pos=><button key={pos} className={position===pos?styles.filterActive:""} onClick={()=>setPosition(pos)}>{pos}</button>)}<div className={styles.poolFilters}>{(["undrafted","drafted","all"] as PoolView[]).map(view=><button key={view} className={poolView===view?styles.filterActive:""} onClick={()=>setPoolView(view)}>{view[0]!.toUpperCase()+view.slice(1)}</button>)}</div></div>
      <div className={`${styles.grid} ${styles.columns}`}><button title="Overall rank based on xPAR" onClick={()=>chooseSort("rank")}>xRank{sortMark("rank")}</button><button onClick={()=>chooseSort("position")}>Pos{sortMark("position")}</button><button onClick={()=>chooseSort("name")}>Player{sortMark("name")}</button><button onClick={()=>chooseSort("team")}>Team{sortMark("team")}</button><button onClick={()=>chooseSort("bye")}>Bye{sortMark("bye")}</button><button title="Blended Yahoo and ESPN average draft position" onClick={()=>chooseSort("adp")}>ADP{sortMark("adp")}</button><button onClick={()=>chooseSort("age")}>Age{sortMark("age")}</button><button title="Actual 2025 fantasy points" onClick={()=>chooseSort("actualPoints")}>2025 PTS{sortMark("actualPoints")}</button><button onClick={()=>chooseSort("points")}>xPTS{sortMark("points")}</button><button onClick={()=>chooseSort("xpar")}>xPAR{sortMark("xpar")}</button><button onClick={()=>chooseSort("tier")}>xTier{sortMark("tier")}</button><button title="How many players remain at this player's position and production tier" onClick={()=>chooseSort("tierLeft")}>Scarcity{sortMark("tierLeft")}</button><button onClick={()=>chooseSort("drop")}>DROP{sortMark("drop")}</button><button onClick={()=>chooseSort("price")}>xPRICE{sortMark("price")}</button><button title="Sort by the width of the expected price range" onClick={()=>chooseSort("range")}>xPRICE Range{sortMark("range")}</button><button onClick={()=>chooseSort("value")}>xPrice Value{sortMark("value")}</button><button onClick={()=>chooseSort("equity")}>xEquity{sortMark("equity")}</button><button onClick={()=>chooseSort("targetRank")}>Target Rank{sortMark("targetRank")}</button></div>
      <div className={styles.playerList}>{rows.map(player=><div key={player.id} className={styles.playerGroup}>
        {expandedId!==player.id&&<button className={`${styles.grid} ${styles.playerRow} ${poolView==="all"&&player.status==="sold"?styles.draftedRow:""} ${nomination?.id===player.id?styles.nominatedRow:""}`} onClick={()=>setExpandedId(player.id)}>
          <span className={styles.rankValue}>{overallRanks.get(player.id)??"—"}</span><span><i className={styles.positionBadge}>{player.position}</i></span><span className={styles.playerName}><strong>{player.name}{player.status==="sold"&&player.draftedBy&&<small className={styles.draftedOwner}> → {player.draftedBy}</small>}</strong><ResearchIcons consensus={player.analystConsensus}/></span><span className={styles.teamText}>{player.nflTeam??"FA"}</span><span>{player.byeWeek??"—"}</span><span>{player.marketAdp==null?"—":Math.round(player.marketAdp)}</span><span>{playerAge(player.birthDate)??"—"}</span><b>{number(seasonPoints(player,2025))}</b><b>{number(player.projectedPoints)}</b><b className={`${styles.xparText} ${tierTone(player.productionLabel)}`}>{number(player.pointsAboveReplacement)}</b><span><i className={`${styles.tierBadge} ${tierTone(player.productionLabel)}`} title={player.productionTier?`Production Tier ${player.productionTier}`:"Production tier unavailable"}>{tierLabel(player.productionLabel)}</i></span><b title={(()=>{const supply=tierLeft.get(player.id);if(!supply?.names.length)return"No players remain in this position-tier";const shown=supply.names.slice(0,5),more=supply.names.length-shown.length;return `${shown.join(", ")}${more>0?` +${more} more`:""}`;})()}>{tierLeft.has(player.id)?`${tierLeft.get(player.id)!.count} left`:"—"}</b><b><i className={(drops.get(player.id)??0)>=5?styles.dropBadgeHigh:styles.dropBadge}>{number(drops.get(player.id))}</i></b><b className={styles.priceValue}>{money(player.status==="sold"?player.salePrice:player.liveExpectedPrice??player.expectedPrice)}</b><span className={styles.rangeText}>{money(player.livePriceLow??player.priceLow)}–{money(player.livePriceHigh??player.priceHigh)}</span><span><i className={`${styles.valueBadge} ${styles[`value${impactLabel(player.draftImpact)}`]??""}`}>{impactLabel(player.draftImpact)}</i></span><b className={styles.equityValue}>{equityLabel(player.draftImpact)}</b><b className={styles.targetRankValue}>{targetRanks.has(player.id)?`#${targetRanks.get(player.id)}`:"—"}</b>
        </button>}
        {expandedId===player.id&&(
          <PlayerDetails player={nomination?.id===player.id?nomination:player} rank={overallRanks.get(player.id)??null} targetRank={targetRanks.get(player.id)??null} team={data.renegades} teams={teams} nominatorTeamId={nominatorTeamId} onNominatorChange={setNominatorTeamId} roster={data.renegades?data.teamRosters[data.renegades.id]??[]:[]} drops={drops} tierRemaining={tierLeft.get(player.id)?.count??0} busy={busy} nominated={Boolean(nomination)||data.draft.status!=="active"} officiallyNominated={nomination?.id===player.id} onClose={()=>setExpandedId(null)} onOverride={override=>void act({type:"fantasyAnalysisOverride",playerId:player.id,override})} onTagOverride={(tag,override)=>void act({type:"fantasyAnalysisTagOverride",playerId:player.id,tag,override})} onNominate={()=>void act({type:"nominate",playerId:player.id,...(nominatorTeamId?{nominatedByTeamId:nominatorTeamId}:{})})}/>
        )}
      </div>)}</div>
    </section>

    <section className={`${styles.drawer} ${drawerOpen?styles.drawerOpen:""}`} style={drawerOpen?{height:`min(55vh, ${106+roster.length*27}px)`}:undefined}>
      <button className={styles.drawerToggle} aria-expanded={drawerOpen} onClick={()=>setDrawerOpen(open=>!open)}>{drawerOpen?"Close tables":"Draft tables"}</button>
      {drawerOpen&&<div className={styles.drawerBody}>
        <section className={styles.drawerPanel}><h2>League Strength</h2><div className={styles.panelContent}><StrengthTable rows={strength}/></div></section>
        <section className={styles.drawerPanel}><h2 className={styles.rosterPanelHeader}><span>Team Rosters</span><select aria-label="View team roster" value={rosterTeam?.id??""} onChange={event=>setRosterTeamId(event.target.value)}>{teams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><small>Budget <b>{money(rosterTeam?.remainingBudget)}</b></small><small>Max bid <b>{money(rosterTeam?.maxBid)}</b></small></h2><div className={styles.panelContent}><RosterTable roster={roster} busy={busy} draggedPlayerId={draggedPlayerId} dropSlotId={dropSlotId} onDrag={setDraggedPlayerId} onDropTarget={setDropSlotId} onMove={(playerId,targetSlotId)=>rosterTeam&&void act({type:"reassignRosterSlot",teamId:rosterTeam.id,playerId,targetSlotId})}/></div></section>
        <section className={styles.drawerPanel}><h2>Draft History <span>{data.recentSales.length}</span></h2><div className={styles.panelContent}><History sales={data.recentSales} busy={busy} onUndo={sale=>{if(window.confirm(`Undo ${sale.player}'s pick?`))void act({type:"voidSale",saleId:sale.id});}}/></div></section>
      </div>}
    </section>

    {settingsOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setSettingsOpen(false);}}><section className={`${styles.modal} ${styles.settingsModal}`}><div className={styles.settingsHeading}><h2>Draft settings</h2><button aria-label="Close draft settings" onClick={()=>setSettingsOpen(false)}>×</button></div><nav className={styles.settingsMenu}><button onClick={()=>{setSettingsOpen(false);setNominationOrderDraft(data.nominationOrder.teams.map(team=>team.teamId));setNominationOrderOpen(true);}}><i>1</i><span><strong>Nomination order</strong><small>View or change the owner rotation</small></span><b>›</b></button><button disabled><i>2</i><span><strong>Draft strategy</strong><small>Strategy preferences will be managed here</small></span><em>Coming soon</em></button><button className={styles.settingsDangerItem} onClick={()=>{setSettingsOpen(false);setResetConfirmation("");setPreservePreferences(true);setResetOpen(true);}}><i>!</i><span><strong>Reset draft</strong><small>Back up and clear the current draft</small></span><b>›</b></button></nav></section></div>}
    {nominationOrderOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setNominationOrderOpen(false);}}><section className={`${styles.modal} ${styles.orderModal}`}><small>DRAFT ROTATION</small><h2>Nomination order</h2><div className={styles.orderList}>{nominationOrderDraft.map((teamId,index)=>{const team=data.nominationOrder.teams.find(item=>item.teamId===teamId);if(!team)return null;return <div className={`${styles.orderRow} ${data.nominationOrder.nextTeamId===teamId?styles.nextOwner:""}`} key={teamId}><b>{index+1}</b><span><strong>{team.owner}</strong><small>{team.completedAt?`Draft complete · waiver #${team.waiverPriority}`:data.nominationOrder.nextTeamId===teamId?"Next to nominate":`${team.openSlots} spots open`}</small></span><div><button disabled={index===0} onClick={()=>moveNominationOwner(index,-1)}>↑</button><button disabled={index===nominationOrderDraft.length-1} onClick={()=>moveNominationOwner(index,1)}>↓</button></div></div>;})}</div><div><button className={styles.secondary} onClick={()=>setNominationOrderOpen(false)}>Cancel</button><button className={styles.primary} disabled={busy} onClick={()=>void act({type:"updateNominationOrder",teamIds:nominationOrderDraft}).then(()=>setNominationOrderOpen(false))}>Save order</button></div></section></div>}
    {resetOpen&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setResetOpen(false);}}><section className={styles.modal}><small>RECOVERABLE RESET</small><h2>Reset the draft?</h2><p className={styles.modalCopy}>This creates a timestamped backup, restores all budgets and roster slots, and clears the active draft history.</p><label className={styles.resetChoice}><input type="checkbox" checked={preservePreferences} onChange={event=>setPreservePreferences(event.target.checked)}/><span>Keep Renegades preferences</span></label><label>Type RESET to confirm<input value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)} placeholder="RESET"/></label><div><button className={styles.secondary} onClick={()=>setResetOpen(false)}>Cancel</button><button className={styles.danger} disabled={busy||resetConfirmation!=="RESET"} onClick={()=>void act({type:"resetDraft",confirmation:resetConfirmation,preservePreferences}).then(()=>setResetOpen(false))}>Reset draft</button></div></section></div>}
  </main>;
}

function PlayerStatHeaderRow({player,rank,drop,tierRemaining,targetRank,showResearch=false}:{player:Player;rank:number|null;drop:number|null;tierRemaining:number;targetRank:number|null;showResearch?:boolean}){return <div className={`${styles.grid} ${styles.playerStatHeaderRow}`}>
  <span className={styles.rankValue}>{rank??"—"}</span><span><i className={styles.positionBadge}>{player.position}</i></span><span className={styles.playerName}><strong>{player.name}</strong>{showResearch&&<ResearchIcons consensus={player.analystConsensus}/>}</span><span className={styles.teamText}>{player.nflTeam??"FA"}</span><span>{player.byeWeek??"—"}</span><span>{player.marketAdp==null?"—":Math.round(player.marketAdp)}</span><span>{playerAge(player.birthDate)??"—"}</span><b>{number(seasonPoints(player,2025))}</b><b>{number(player.projectedPoints)}</b><b className={`${styles.xparText} ${tierTone(player.productionLabel)}`}>{number(player.pointsAboveReplacement)}</b><span><i className={`${styles.tierBadge} ${tierTone(player.productionLabel)}`}>{tierLabel(player.productionLabel)}</i></span><b>{tierRemaining} left</b><b><i className={(drop??0)>=5?styles.dropBadgeHigh:styles.dropBadge}>{number(drop)}</i></b><b className={styles.priceValue}>{money(player.liveExpectedPrice??player.expectedPrice)}</b><span className={styles.rangeText}>{money(player.livePriceLow??player.priceLow)}–{money(player.livePriceHigh??player.priceHigh)}</span><span><i className={`${styles.valueBadge} ${styles[`value${impactLabel(player.draftImpact)}`]??""}`}>{impactLabel(player.draftImpact)}</i></span><b className={styles.equityValue}>{equityLabel(player.draftImpact)}</b><b className={styles.targetRankValue}>{targetRank==null?"—":`#${targetRank}`}</b>
</div>}

function TeamCombobox({id,ariaLabel,nextFocusId,teams,value,disabled=false,onChange}:{id:string;ariaLabel:string;nextFocusId:string;teams:Team[];value:string;disabled?:boolean;onChange:(teamId:string)=>void}){const selected=teams.find(team=>team.id===value),label=(team:Team)=>team.owner,[query,setQuery]=useState(selected?label(selected):""),[open,setOpen]=useState(false),normalized=query.trim().toLowerCase(),matches=teams.filter(team=>!normalized||team.owner.toLowerCase().includes(normalized)||team.name.toLowerCase().includes(normalized));useEffect(()=>{if(!open)setQuery(selected?label(selected):"");},[open,selected?.id]);function choose(team:Team){onChange(team.id);setQuery(label(team));setOpen(false);}function chooseFirst(){if(matches[0])choose(matches[0]);else{setQuery(selected?label(selected):"");setOpen(false);}}return <div className={styles.teamCombobox}><input aria-label={ariaLabel} role="combobox" aria-autocomplete="list" aria-expanded={open} aria-controls={id} autoComplete="off" disabled={disabled} value={query} onFocus={event=>{setOpen(true);event.currentTarget.select();}} onChange={event=>{setQuery(event.target.value);setOpen(true);}} onBlur={()=>chooseFirst()} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();chooseFirst();}else if(event.key==="Tab"){event.preventDefault();chooseFirst();window.requestAnimationFrame(()=>document.getElementById(nextFocusId)?.focus());}else if(event.key==="Escape"){setQuery(selected?label(selected):"");setOpen(false);}}}/>{open&&<div id={id} role="listbox">{matches.length?matches.map(team=><button type="button" tabIndex={-1} role="option" aria-selected={team.id===value} key={team.id} onMouseDown={event=>{event.preventDefault();choose(team);}}><strong>{team.owner}</strong></button>):<p>No matching owner</p>}</div>}</div>}

function ResearchIcons({consensus}:{consensus:AnalystConsensus}){const icons:{key:string;symbol:string;label:string;className?:string|undefined}[]=[];if(consensus.action==="target")icons.push({key:"target",symbol:"◎",label:"Target",className:styles.analysisTarget});if(consensus.action==="avoid")icons.push({key:"avoid",symbol:"×",label:"Avoid",className:styles.analysisAvoid});for(const tag of consensus.tags){const item=tag==="sleeper"?{symbol:"☾",label:"Sleeper",className:styles.analysisSleeper}:tag==="breakout"?{symbol:"⚡",label:"Breakout",className:styles.analysisBreakout}:tag==="value"?{symbol:"$",label:"Value",className:styles.analysisValue}:tag==="bust"?{symbol:"!",label:"Bust",className:styles.analysisBust}:null;if(item)icons.push({key:tag,...item});}return icons.length?<span className={styles.researchIcons}>{icons.map(icon=><i key={icon.key} className={`${styles.analysisFlag??""} ${icon.className??""}`} data-tooltip={icon.label} aria-label={`Research: ${icon.label}`}>{icon.symbol}</i>)}</span>:null}

function TeamDepthChartLine({team,depthChart}:{team:string|null;depthChart:TeamDepthChart|null}){if(!team||!depthChart)return null;return <div className={styles.teamDepthChart} title={`${team} fantasy depth chart`}><strong>{team}</strong>{(["QB","RB","WR","TE"] as const).map(group=><span key={group}><b>{group}:</b> {depthChart[group].join(", ")||"—"}</span>)}</div>}

function ResearchEditor({consensus,busy,large=false,onAction,onTag}:{consensus:AnalystConsensus;busy:boolean;large?:boolean;onAction:(override:"auto"|"target"|"avoid"|"off")=>void;onTag:(tag:ResearchTag,override:"auto"|"on"|"off")=>void}){const displayed=consensus.override==="off"?null:consensus.override??consensus.derivedAction,tags=new Set(consensus.tags),tagOptions:ResearchTag[]=["sleeper","breakout","value","bust"];return <div className={`${styles.researchEditor} ${large?styles.researchEditorLarge:""}`}><div>{(["target","avoid"] as const).map(value=>{const selected=displayed===value,suggested=consensus.derivedAction===value;return <button type="button" key={value} disabled={busy} aria-pressed={selected} className={`${value==="target"?styles.researchTarget:styles.researchAvoid} ${selected?styles.researchSelected:""}`} onClick={()=>onAction(selected?"off":value===consensus.derivedAction?"auto":value)}>{value[0]!.toUpperCase()+value.slice(1)}{large&&suggested&&<i aria-hidden="true"/>}</button>})}</div>{large&&<span aria-hidden="true"/>}<div>{tagOptions.map(tag=>{const selected=tags.has(tag),suggested=consensus.derivedTags.includes(tag);return <button type="button" key={tag} disabled={busy} aria-pressed={selected} className={selected?styles.researchTagSelected:""} onClick={()=>onTag(tag,selected?(suggested?"off":"auto"):(suggested?"auto":"on"))}>{tag[0]!.toUpperCase()+tag.slice(1)}{large&&suggested&&<i aria-hidden="true"/>}</button>})}</div></div>}

function PlayerDetails({player,rank,targetRank,team,teams,nominatorTeamId,onNominatorChange,roster,drops,tierRemaining,busy,nominated,officiallyNominated,onClose,onOverride,onTagOverride,onNominate}:{player:Player;rank:number|null;targetRank:number|null;team:Team|null;teams:Team[];nominatorTeamId:string;onNominatorChange:(teamId:string)=>void;roster:RosterSlot[];drops:Map<string,number>;tierRemaining:number;busy:boolean;nominated:boolean;officiallyNominated:boolean;onClose:()=>void;onOverride:(override:"auto"|"target"|"avoid"|"off")=>void;onTagOverride:(tag:ResearchTag,override:"auto"|"on"|"off")=>void;onNominate:()=>void}){
  const [fullWriteupOpen,setFullWriteupOpen]=useState(false);
  const sold=player.status==="sold",consensus=player.analystConsensus;
  const fullWriteup=consensus.aiSummary?.fullWriteup??"";
  const quickPros=consensus.aiSummary?.prosSummary??consensus.commonCase??"No clear upside case is captured in the current research.";
  const quickCons=consensus.aiSummary?.consSummary??consensus.mainConcern??"No specific downside case is captured in the current research.";
  const researchSources=[...new Map(player.fantasyAnalysis.map(source=>[source.url,source])).values()].map(source=>({url:source.url,title:source.sourceTitle}));
  const assumedPrice=Math.max(1,player.liveExpectedPrice??player.expectedPrice??1);
  const budgetAfter=Math.max(0,(team?.remainingBudget??0)-assumedPrice),openSlotsAfter=Math.max(0,(team?.openSlots??1)-1),futureMaxBid=Math.max(0,budgetAfter-Math.max(0,openSlotsAfter-1));
  const eligibleOpenSlots=roster.filter(slot=>!slot.playerId&&slot.eligiblePositions.includes(player.position));
  const likelySlot=eligibleOpenSlots.find(slot=>slot.slotType===player.position)??eligibleOpenSlots[0]??null;
  const reasoning=`At ${money(assumedPrice)}, ${player.name} adds ${number(player.pointsAboveReplacement)} xPAR at ${player.position}${likelySlot?` and fills your ${likelySlot.slotType.replaceAll("_","/")} slot`:""}. ${tierRemaining} player${tierRemaining===1?"":"s"} remain in this tier, with a ${number(drops.get(player.id))}-point drop to the next ${player.position}. You would retain ${money(budgetAfter)} and a future max bid of ${money(futureMaxBid)}.`;
  const recommendation=player.draftImpact?{label:player.draftImpact.label,support:player.draftImpact.scenarioSupport,equity:player.draftImpact.expectedEquityDelta}:null;
  const supportedPaths=recommendation?Math.round(recommendation.support*9):null;
  const walkaway=officiallyNominated?player.decisionPlan?.committedCeiling??player.decisionCeiling:player.decisionCeiling;
  const decisionExpectedPrice=player.liveExpectedPrice??player.expectedPrice;
  const decisionEdge=walkaway==null||decisionExpectedPrice==null?null:walkaway-decisionExpectedPrice;
  const assistantNotes:AssistantNote[]=[];
  const addNote=(text:string,tone:AssistantNote["tone"],priority:number)=>assistantNotes.push({text,tone,priority});
  if(likelySlot)addNote(`Fills your open ${likelySlot.slotType.replaceAll("_","/")} slot.`,"positive",100);
  else if(!sold)addNote(`Does not fill one of your currently open eligible roster slots.`,"negative",100);
  if(player.injury)addNote(`${player.injury.status||"Injury concern"}${player.injury.injuryType?`: ${player.injury.injuryType}`:""}.`,"negative",98);
  if(decisionEdge!=null&&decisionEdge>=3)addNote(`Your walk-away price is ${money(decisionEdge)} above the current expected price.`,"positive",95);
  else if(decisionEdge!=null&&decisionEdge<=-3)addNote(`The current expected price is ${money(Math.abs(decisionEdge))} above your walk-away price.`,"negative",95);
  if(tierRemaining<=3)addNote(`Only ${tierRemaining} ${player.productionLabel.toLowerCase()} ${player.position}${tierRemaining===1?" remains":"s remain"}.`,"positive",92);
  else if(tierRemaining>=8&&(drops.get(player.id)??0)<2)addNote(`Comparable ${player.position} production remains plentiful.`,"neutral",82);
  const cheaperAlternative=[...player.alternatives].filter(item=>item.liveExpectedPrice!=null&&decisionExpectedPrice!=null&&item.liveExpectedPrice<=decisionExpectedPrice-4).sort((a,b)=>(a.liveExpectedPrice??0)-(b.liveExpectedPrice??0))[0];
  if(cheaperAlternative)addNote(`${cheaperAlternative.name} offers similar-position production for about ${money((decisionExpectedPrice??0)-(cheaperAlternative.liveExpectedPrice??0))} less.`,"negative",90);
  else if(player.alternatives.length===0)addNote(`No close available alternative is currently identified.`,"positive",88);
  if(player.positionRank!=null&&player.positionRank<=12)addNote(`Ranks ${player.position}${player.positionRank}, placing him among the top options at the position.`,"positive",86);
  for(const signal of player.situationSignals??[])addNote(signal.text,signal.tone,signal.priority);
  const sameBye=player.byeWeek==null?0:roster.filter(slot=>slot.playerId&&slot.byeWeek===player.byeWeek).length;
  if(sameBye>=2)addNote(`Would give you ${sameBye+1} players sharing a Week ${player.byeWeek} bye.`,"negative",84);
  if(consensus.positiveCount>0&&consensus.negativeCount>0)addNote(`Fantasy outlook is mixed: ${consensus.positiveCount} positive and ${consensus.negativeCount} negative independent opinions.`,"neutral",80);
  else if(consensus.action==="target")addNote(`Fantasy research leans Target${consensus.tags.length?`, led by ${consensus.tags.join(" and ")} cases`:""}.`,"positive",80);
  else if(consensus.action==="avoid")addNote(`Fantasy research leans Avoid${consensus.tags.includes("bust")?" with a bust case attached":""}.`,"negative",80);
  if(recommendation&&recommendation.support>=6/9)addNote(`Buying at ${money(assumedPrice)} improves the projected roster in most tested paths.`,"positive",78);
  else if(recommendation&&recommendation.support<=3/9)addNote(`Buying at ${money(assumedPrice)} improves the projected roster in few tested paths.`,"negative",78);
  const displayedAssistantNotes=assistantNotes.sort((a,b)=>b.priority-a.priority).slice(0,6);
  return <div className={`${styles.details} ${officiallyNominated?styles.detailsNominated:""}`}>
    <header className={styles.detailPlayerHeader} role="button" tabIndex={0} title="Close player details" onClick={event=>{if(!(event.target as HTMLElement).closest("button, input, select"))onClose();}} onKeyDown={event=>{if((event.key==="Enter"||event.key===" ")&&event.target===event.currentTarget){event.preventDefault();onClose();}}}>
      <div className={styles.detailHeaderTop}>
        <PlayerStatHeaderRow player={player} rank={rank} drop={drops.get(player.id)??null} tierRemaining={tierRemaining} targetRank={targetRank} showResearch/>
        <div className={styles.detailHeaderActions}>
          <TeamDepthChartLine team={player.nflTeam} depthChart={player.teamDepthChart}/>
          {!officiallyNominated&&!sold&&<label className={styles.detailNominatorControl}><small>NOMINATED BY</small><TeamCombobox id={`detail-nominator-${player.id}`} ariaLabel="Choose nominating owner" nextFocusId={`nominate-${player.id}`} teams={teams} value={nominatorTeamId} disabled={busy||nominated} onChange={onNominatorChange}/></label>}
          <button id={`nominate-${player.id}`} className={styles.primary} disabled={busy||nominated||sold} onClick={onNominate}>{sold?"Drafted":nominated?"Nomination active":"Nominate"}</button>
        </div>
      </div>
    </header>
    {player.recentNews.length>0&&<section className={styles.playerNewsPanel}>
      <div className={styles.newsList}>{player.recentNews.slice(0,3).map(item=>{const update=item.impact??item.description;return <article key={item.id}><div className={styles.newsHeadline}>{item.url?<a href={item.url} target="_blank" rel="noreferrer">{item.title}</a>:<b>{item.title}</b>}<small>{item.createdAt?new Date(`${item.createdAt.replace(" ","T")}Z`).toLocaleDateString(undefined,{month:"numeric",day:"numeric"}):null}</small>{update&&<p>{update}</p>}</div></article>})}</div>
    </section>}
    <div className={styles.decisionSections}>
      <section className={styles.impactCard} style={{display:"flex",flexDirection:"column"}}><strong>Brief Summary</strong><p>{consensus.aiSummary?.cardSummary??consensus.commonCase??consensus.mainConcern??"No fantasy analysis is available for this player yet."}</p><ResearchEditor consensus={consensus} busy={busy} onAction={onOverride} onTag={onTagOverride}/>{consensus.aiSummary?.fullWriteup&&<button type="button" onClick={()=>setFullWriteupOpen(true)} style={{alignSelf:"flex-end",marginTop:"auto",padding:"8px 0 0",border:0,background:"transparent",color:"#176b9a",fontSize:10,fontWeight:800,cursor:"pointer"}}>Full writeup →</button>}</section>
      <section className={styles.reasoningCard}><strong>Value</strong>{recommendation&&supportedPaths!=null?<div className={styles.decisionSummary}><span className={styles.pathSupportText}>Improves your projected final roster in <b className={supportedPaths>=6?styles.pathSupportGood:supportedPaths<=3?styles.pathSupportBad:styles.pathSupportMixed}>{supportedPaths} of 9</b> tested paths.</span><dl><div><dt>xPRICE</dt><dd>{money(assumedPrice)}</dd></div><div><dt>xPRICE Range</dt><dd>{money(player.livePriceLow??player.priceLow)}–{money(player.livePriceHigh??player.priceHigh)}</dd></div><div><dt>Walk-away</dt><dd>{money(walkaway)}</dd></div><div><dt>xEquity</dt><dd>{`${recommendation.equity>=0?"+":""}${(recommendation.equity*100).toFixed(1)}%`}</dd></div></dl></div>:<p className={styles.previewLabel}>Preview at expected price; the full recommendation is calculated when the draft is active.</p>}<p>{reasoning}</p></section>
      <section className={styles.assistantNotesCard}>
        <strong>Player/Roster Notes</strong>
        <ul>{displayedAssistantNotes.map((note,index)=><li className={styles[`assistantNote${note.tone[0]!.toUpperCase()+note.tone.slice(1)}`]} key={`${note.text}-${index}`}><i aria-hidden="true"/><span>{note.text}</span></li>)}</ul>
      </section>
    </div>
    <PlayerStatTable player={player}/>
    {fullWriteupOpen&&consensus.aiSummary?.fullWriteup&&<div className={styles.modalBackdrop} onMouseDown={event=>{if(event.target===event.currentTarget)setFullWriteupOpen(false);}}><section className={fullWriteupStyles.dialog} role="dialog" aria-modal="true" aria-label={`${player.name} full writeup`}><ResearchWriteup variant="modal" name={player.name} positionPrice={`${player.position}${player.positionRank??"—"} - ${money(player.liveExpectedPrice??player.expectedPrice)} (${money(player.livePriceLow??player.priceLow)}–${money(player.livePriceHigh??player.priceHigh)})`} playerMeta={`${player.nflTeam??"Free agent"}${player.byeWeek?` · Bye ${player.byeWeek}`:""}${playerAge(player.birthDate)!=null?` · Age ${playerAge(player.birthDate)}`:""}`} controls={<ResearchEditor consensus={consensus} busy={busy} large onAction={onOverride} onTag={onTagOverride}/>} positiveCount={consensus.positiveCount} negativeCount={consensus.negativeCount} independentOpinionCount={consensus.independentOpinionCount} pros={quickPros} cons={quickCons} fullWriteup={fullWriteup} context={player.injury?<aside className={fullWriteupStyles.injuryContext}><strong>Injury:</strong><span>{injurySummary(player.injury)}</span><small>FantasyPros{contextDate(player.injury.updatedAt)?` · Updated ${contextDate(player.injury.updatedAt)}`:""}</small></aside>:null} sources={researchSources}/></section></div>}
  </div>
}

function PlayerStatTable({player}:{player:Player}){const columns=statColumns(player.position),history=[...(player.historicalStatLines??[])].sort((a,b)=>a.season-b.season),lines=[...history.map(line=>({line,projected:false})),{line:player.projectedStatLine,projected:true}];return <div className={styles.statTable}><table><thead><tr><th>Season</th>{columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{lines.map(({line,projected},index)=>line?<tr className={projected?styles.projectedStats:""} key={`${line.season}-${index}`}><th>{projected?`x${line.season}`:line.season}</th>{columns.map(column=>{const value=statValue(line,column.key);return <td key={column.key}>{value==null?"—":projected?Number(value).toFixed(1):Number.isInteger(value)?value:Number(value).toFixed(1)}</td>;})}</tr>:<tr key={`missing-${index}`}><th>Projection</th><td colSpan={columns.length}>No stat line available</td></tr>)}</tbody></table></div>}

type StrengthRow={team:Team;total:number;QB:number;RB:number;WR:number;TE:number};
function heatClass(rows:StrengthRow[],key:"QB"|"RB"|"WR"|"TE"|"total",value:number){if(value<=0)return styles.heatLowest;const values=rows.map(row=>row[key]).filter(item=>item>0),minimum=Math.min(...values),maximum=Math.max(...values);if(maximum===minimum)return styles.heatHighest;const score=(value-minimum)/(maximum-minimum);return score>=.8?styles.heatHighest:score>=.6?styles.heatHigh:score>=.4?styles.heatMiddle:score>=.2?styles.heatLow:styles.heatLowest;}
type StrengthSort="rank"|"owner"|"QB"|"RB"|"WR"|"TE"|"total"|"maxBid";
function StrengthTable({rows}:{rows:StrengthRow[]}){const [sort,setSort]=useState<StrengthSort>("rank"),[ascending,setAscending]=useState(true),ranks=new Map(rows.map((row,index)=>[row.team.id,index+1]));function chooseSort(key:StrengthSort){if(key===sort)setAscending(value=>!value);else{setSort(key);setAscending(key==="rank"||key==="owner");}}const sorted=[...rows].sort((a,b)=>{const value=(row:StrengthRow)=>sort==="rank"?(ranks.get(row.team.id)??999):sort==="owner"?row.team.owner:sort==="maxBid"?row.team.maxBid:row[sort];const av=value(a),bv=value(b),comparison=typeof av==="string"?av.localeCompare(String(bv)):Number(av)-Number(bv);return comparison*(ascending?1:-1)||a.team.owner.localeCompare(b.team.owner);}),header=(label:string,key:StrengthSort)=><button type="button" onClick={()=>chooseSort(key)}>{label}{sort===key?<span>{ascending?"↑":"↓"}</span>:null}</button>;return <div className={`${styles.tableWrap} ${styles.strengthTable}`}><table><thead><tr><th>{header("Rank","rank")}</th><th>{header("Owner","owner")}</th><th>{header("QB","QB")}</th><th>{header("RB","RB")}</th><th>{header("WR","WR")}</th><th>{header("TE","TE")}</th><th>{header("Total","total")}</th><th>{header("MaxBid","maxBid")}</th></tr></thead><tbody>{sorted.map(row=><tr key={row.team.id}><td>{ranks.get(row.team.id)}</td><td><strong>{row.team.owner}</strong></td><td className={heatClass(rows,"QB",row.QB)}>{number(row.QB)}</td><td className={heatClass(rows,"RB",row.RB)}>{number(row.RB)}</td><td className={heatClass(rows,"WR",row.WR)}>{number(row.WR)}</td><td className={heatClass(rows,"TE",row.TE)}>{number(row.TE)}</td><td className={heatClass(rows,"total",row.total)}><strong>{number(row.total)}</strong></td><td>{money(row.team.maxBid)}</td></tr>)}</tbody></table></div>}

function RosterTable({roster,busy,draggedPlayerId,dropSlotId,onDrag,onDropTarget,onMove}:{roster:RosterSlot[];busy:boolean;draggedPlayerId:string|null;dropSlotId:string|null;onDrag:(id:string|null)=>void;onDropTarget:(id:string|null)=>void;onMove:(playerId:string,targetSlotId:string)=>void}){return <div className={styles.tableWrap}><table><thead><tr><th>Slot</th><th>Player</th><th>Pos</th><th>Bye</th><th>Paid</th><th>xPAR</th></tr></thead><tbody>{roster.map(slot=><tr key={slot.slotId} className={`${slot.playerId?styles.rosterDraggable:""} ${dropSlotId===slot.slotId?styles.dropTarget:""}`} draggable={Boolean(slot.playerId)&&!busy} onDragStart={event=>{if(!slot.playerId)return;onDrag(slot.playerId);event.dataTransfer.setData("text/plain",slot.playerId);}} onDragEnd={()=>{onDrag(null);onDropTarget(null);}} onDragOver={event=>{if(draggedPlayerId){event.preventDefault();onDropTarget(slot.slotId);}}} onDrop={event=>{event.preventDefault();const id=draggedPlayerId||event.dataTransfer.getData("text/plain");onDrag(null);onDropTarget(null);if(id)onMove(id,slot.slotId);}}><td>{slot.slotType.replaceAll("_","/")}</td><td><strong>{slot.player??""}</strong></td><td>{slot.position??""}</td><td>{slot.byeWeek??""}</td><td>{slot.pricePaid==null?"":money(slot.pricePaid)}</td><td>{slot.pointsAboveReplacement==null?"":number(slot.pointsAboveReplacement)}</td></tr>)}</tbody></table></div>}

function History({sales,busy,onUndo}:{sales:Sale[];busy:boolean;onUndo:(sale:Sale)=>void}){return <div className={styles.tableWrap}>{sales.length?<table><thead><tr><th>Pick</th><th>Player</th><th>Team</th><th>Price</th><th/></tr></thead><tbody>{sales.map(sale=><tr key={sale.id}><td>#{sale.pick}</td><td><strong>{sale.player}</strong></td><td>{sale.team}</td><td>{money(sale.price)}</td><td><button disabled={busy} onClick={()=>onUndo(sale)}>Undo pick</button></td></tr>)}</tbody></table>:<p>No completed sales yet.</p>}</div>}
