import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

test("draft-room view and commands run against isolated local state",async()=>{
  const directory=mkdtempSync(join(tmpdir(),"renegade-draft-room-"));
  process.env.RENEGADE_DB_PATH=join(directory,"draft.sqlite");
  const {applyDraftAction,readDraftRoom,resetDraftRoom}=await import("../../src/server/draftStore.js");
  try{
    const setup=readDraftRoom();
    assert.equal(setup.players.length,602);
    assert.equal(setup.players.filter(row=>row.guidanceLevel==="modeled").length,294);
    assert.equal(setup.players.filter(row=>row.guidanceLevel==="limited").length,307);
    assert.equal(setup.players.filter(row=>row.guidanceLevel==="adp_only").length,1);
    const limited=setup.players.find(row=>row.guidanceLevel==="limited");
    assert.ok(limited?.projectedPoints!=null);
    assert.equal(limited?.expectedPrice,null);
    assert.equal(limited?.draftImpact,null);
    const adpOnly=setup.players.find(row=>row.guidanceLevel==="adp_only");
    assert.equal(adpOnly?.name,"Tyreek Hill");
    assert.equal(adpOnly?.projectedPoints,null);
    assert.equal(adpOnly?.expectedPrice,null);
    assert.equal(setup.teams.length,10);
    assert.equal(setup.renegades?.name,"Rodman Renegades");
    assert.deepEqual(setup.nominationOrder.teams.map(row=>row.owner),[...setup.nominationOrder.teams.map(row=>row.owner)].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:"base"})));
    assert.equal(setup.nominationOrder.nextTeamId,setup.nominationOrder.teams[0]?.teamId);
    assert.ok(setup.players.some(row=>row.marketAdp!==null));
    assert.ok(setup.players.some(row=>row.byeWeek!==null));
    for(const playerId of ["nfl:gsis:00-0039163","nfl:gsis:00-0040676","nfl:gsis:00-0030565"]){
      const player=setup.players.find(row=>row.id===playerId);
      assert.ok(player?.fantasyAnalysis.some((row:{label:string;author:string|null})=>row.label==="sleeper"&&row.author==="Justin Boone"));
    }
    const bucky=setup.players.find(row=>row.id==="nfl:gsis:00-0039361");
    assert.deepEqual(new Set(bucky?.fantasyAnalysis.map((row:{label:string})=>row.label)),new Set(["sleeper","avoid","value"]));
    assert.equal(setup.players.reduce((count,row)=>count+row.fantasyAnalysis.length,0),542);
    assert.ok(setup.players.filter(row=>row.analystConsensus.aiSummary).length>=173);
    assert.ok(setup.players.filter(row=>row.analystConsensus.aiSummary).every(row=>row.analystConsensus.aiSummary?.cardSummary&&row.analystConsensus.aiSummary.fullWriteup));
    assert.ok(setup.players.filter(row=>row.analystConsensus.aiSummary).every(row=>row.analystConsensus.aiSummary?.prosSummary&&row.analystConsensus.aiSummary.consSummary));
    const fantasyProsContextPointer=JSON.parse(readFileSync("data/processed/fantasypros_context/2026/latest.json","utf8"));
    const fantasyProsContext=JSON.parse(readFileSync(fantasyProsContextPointer.artifact,"utf8"));
    assert.ok(fantasyProsContext.metadata.injury_count>0);
    const vikings=setup.players.find(row=>row.nflTeam==="MIN");
    assert.ok(vikings?.teamDepthChart?.QB.length);
    assert.ok(vikings?.teamDepthChart?.RB.every((name:string)=>name!=="Max Bredeson"));
    const nabers=setup.players.find(row=>row.id==="nfl:gsis:00-0039337");
    assert.equal(nabers?.injury,null);
    assert.equal(nabers?.recentNews[0]?.id,"604027");
    assert.match(nabers?.recentNews[0]?.impact??"",/trending/i);
    assert.ok(setup.researchStatus.pendingPlayerCount>=0);
    assert.ok(setup.researchStatus.pendingTakeawayCount>=0);
    assert.ok(setup.researchStatus.pendingSourceCount>=0);
    assert.equal(setup.researchStatus.summaryRefreshNeeded,
      setup.researchStatus.pendingPlayerCount>0||setup.researchStatus.pendingTakeawayCount>0||setup.researchStatus.pendingSourceCount>0);
    assert.deepEqual(setup.draft.recoveryIssues,[]);

    const active=applyDraftAction({type:"start"});
    assert.equal(active.draft.status,"active");
    assert.ok(active.players.filter(row=>row.status==="available"&&row.guidanceLevel==="modeled").every(row=>row.draftImpact));
    assert.ok(active.players.filter(row=>row.status==="available"&&row.guidanceLevel!=="modeled").every(row=>row.draftImpact===null));
    const reversed=applyDraftAction({type:"updateNominationOrder",teamIds:[...active.nominationOrder.teams.map(row=>row.teamId)].reverse()});
    assert.equal(reversed.nominationOrder.teams[0]?.teamId,active.nominationOrder.teams.at(-1)?.teamId);
    const player=active.players.find(row=>row.status==="available"&&row.guidanceLevel==="modeled");
    assert.ok(player);
    const preferred=applyDraftAction({type:"playerPreference",playerId:player.id,preference:"avoid",premium:0,note:"test preference"});
    const avoided=preferred.players.find(row=>row.id===player.id)!;
    assert.equal(avoided.status,"available");
    assert.equal(avoided.preference,"avoid");
    assert.ok(avoided.strategyValue!<avoided.productionValue!);
    const analystPlayerId="nfl:gsis:00-0039163";
    const forcedAvoid=applyDraftAction({type:"fantasyAnalysisOverride",playerId:analystPlayerId,override:"avoid"});
    assert.equal(forcedAvoid.players.find(row=>row.id===analystPlayerId)?.analystConsensus.action,"avoid");
    const hidden=applyDraftAction({type:"fantasyAnalysisOverride",playerId:analystPlayerId,override:"off"});
    assert.equal(hidden.players.find(row=>row.id===analystPlayerId)?.analystConsensus.action,null);
    const automatic=applyDraftAction({type:"fantasyAnalysisOverride",playerId:analystPlayerId,override:"auto"});
    assert.equal(automatic.players.find(row=>row.id===analystPlayerId)?.analystConsensus.action,"target");
    assert.throws(()=>applyDraftAction({type:"fantasyAnalysisOverride",playerId:analystPlayerId,override:"watch"}));
    const tagged=applyDraftAction({type:"fantasyAnalysisTagOverride",playerId:analystPlayerId,tag:"bust",override:"on"});
    assert.ok(tagged.players.find(row=>row.id===analystPlayerId)?.analystConsensus.tags.includes("bust"));
    assert.equal(tagged.players.find(row=>row.id===analystPlayerId)?.analystConsensus.tagOverrides.bust,true);
    const resetTags=applyDraftAction({type:"fantasyAnalysisTagsReset",playerId:analystPlayerId});
    assert.equal(resetTags.players.find(row=>row.id===analystPlayerId)?.analystConsensus.tagOverrides.bust,undefined);
    const withTeamRule=applyDraftAction({type:"updateStrategy",strategy:{buildStyle:"balanced",riskTolerance:"balanced",byeWeekMode:"soft",maxSameBye:2,targetPremium:3,situations:[],teamPreferences:[{team:player.nflTeam!,position:player.position,preference:"prefer",adjustment:2,note:"test team preference"}],notes:""}});
    assert.equal(withTeamRule.strategy.teamPreferences.length,1);
    const nominated=applyDraftAction({type:"nominate",playerId:player.id});
    assert.equal(nominated.currentNomination?.playerId,player.id);
    assert.ok(nominated.currentNomination?.championshipDecision?.tiers.length);
    assert.equal(nominated.currentNomination?.draftImpact?.band,nominated.currentNomination?.championshipDecision?.band);
    assert.equal(nominated.currentNomination?.draftImpact?.expectedEquityDelta,nominated.currentNomination?.championshipDecision?.medianDelta);
    assert.ok(nominated.currentNomination?.competition.length);
    assert.ok(nominated.currentNomination?.alternatives.length);
    assert.ok(nominated.currentNomination?.decisionPlan);
    assert.ok(nominated.upcomingTargets.length);
    assert.ok(nominated.leaderboard.length===10);
    const corrected=applyDraftAction({type:"changeNominationOwner",nominatedByTeamId:active.renegades!.id});
    assert.equal(corrected.currentNomination?.nominatorTeamId,active.renegades!.id);
    const sold=applyDraftAction({type:"sale",winnerTeamId:active.renegades!.id,price:1});
    assert.equal(sold.recentSales.length,1);
    assert.equal(sold.renegades!.remainingBudget,199);
    assert.equal(sold.market.salesCount,1);
    assert.notEqual(sold.market.globalMultiplier,1);
    const recentSales=sold.recentSales as {id:string}[];
    const restored=applyDraftAction({type:"voidSale",saleId:recentSales[0]!.id});
    assert.equal(restored.recentSales.length,0);
    assert.equal(restored.renegades!.remainingBudget,200);
    assert.deepEqual(restored.draft.recoveryIssues,[]);
    const fallback=restored.players.find(row=>row.status==="available"&&row.guidanceLevel==="limited");
    assert.ok(fallback);
    const fallbackNomination=applyDraftAction({type:"nominate",playerId:fallback.id});
    assert.equal(fallbackNomination.currentNomination?.playerId,fallback.id);
    assert.equal(fallbackNomination.currentNomination?.championshipDecision,null);
    assert.equal(fallbackNomination.currentNomination?.decisionPlan,null);
    applyDraftAction({type:"cancelNomination"});
    const reset=resetDraftRoom({preservePreferences:true});
    const clean=readDraftRoom();
    assert.ok(existsSync(reset.backupPath));
    assert.equal(clean.draft.status,"setup");
    assert.equal(clean.draft.stateVersion,0);
    assert.equal(clean.recentSales.length,0);
    assert.equal(clean.players.find(row=>row.id===player.id)?.preference,"avoid");
  }finally{
    globalThis.__renegadeDraftService?.db.close();
    globalThis.__renegadeDraftService=undefined;
    rmSync(directory,{recursive:true,force:true});
  }
});
