"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Player={id:string;name:string;position:string;nflTeam:string|null;status:string;salePrice:number|null;draftedBy:string|null;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;productionValue:number|null;strategyValue:number|null;edge:number|null;liveEdge:number|null;adpEspn:number|null;adpYahoo:number|null;marketAdp:number|null;byeWeek:number|null;preference:"target"|"avoid"|null;preferencePremium:number|null;strategyReasons:string[];riskFlags:string[]};
type Team={id:string;name:string;owner:string;remainingBudget:number;openSlots:number;rosteredCount:number;maxBid:number};
type Sale={id:string;pick:number;player:string;team:string;price:number};
type DecisionBand="strong_pursue"|"lean_pursue"|"neutral"|"lean_pass"|"strong_pass";
type ChampionshipDecision={price:number;band:DecisionBand;medianDelta:number;support:number;equityLow:number;equityHigh:number;recommendedMax:number|null;evaluatedMax:number;marketHigh:number;stretchCeiling:number;extremeCeiling:number;tiers:{from:number;to:number;band:DecisionBand}[];rationale:{draftBecause:string;dontDraftBecause:string};modelStatus:"shadow";explanation:string};
type Nomination=Player&{playerId:string;nominator:string|null;ownerSignal:string|null;competition:{id:string;name:string;maxBid:number;signal:string|null}[];alternatives:Player[];championshipDecision:ChampionshipDecision|null};
type TeamPreference={team:string;position:"ALL"|"QB"|"RB"|"WR"|"TE"|"K"|"DEF";preference:"prefer"|"avoid";adjustment:number;note:string};
type Strategy={buildStyle:"balanced"|"stars_and_scrubs"|"value_first";riskTolerance:"conservative"|"balanced"|"aggressive";byeWeekMode:"ignore"|"soft"|"strict";maxSameBye:number;targetPremium:number;situations:string[];teamPreferences:TeamPreference[];notes:string};
type LeaderboardRow={rank:number;teamId:string;name:string;owner:string;championshipEquity:number;equityLow:number;equityHigh:number;projectedLineupPoints:number};
type RosterSlot={slotId:string;teamId:string;slotType:string;ordinal:number;eligiblePositions:string[];playerId:string|null;player:string|null;position:string|null;byeWeek:number|null;pricePaid:number|null;positionRank:number|null;pointsAboveReplacement:number|null;strength:"Elite"|"Strong"|"Starter"|"Depth"|null};
type NominationOrderTeam={teamId:string;ordinal:number;team:string;owner:string;openSlots:number;completedAt:string|null;waiverPriority:number|null};
type DraftRoomData={draft:{status:string;stateVersion:number;recoveryIssues:string[]};players:Player[];teams:Team[];renegades:Team|null;roster:RosterSlot[];teamRosters:Record<string,RosterSlot[]>;nominationOrder:{teams:NominationOrderTeam[];nextTeamId:string|null};currentNomination:Nomination|null;leaderboard:LeaderboardRow[];recentSales:Sale[];strategy:Strategy;market:{salesCount:number;globalMultiplier:number};sheetSync:{configured:boolean;pending:number;failed:number;succeeded:number;lastError:string|null};localSaved:boolean};
type SortKey="expected"|"edge"|"adp"|"bye"|"name";
type PoolView="undrafted"|"drafted"|"all";

const positions=["ALL","QB","RB","WR","TE","K","DEF"];
const decisionBands:DecisionBand[]=["strong_pursue","lean_pursue","neutral","lean_pass","strong_pass"];
const money=(value:number|null|undefined)=>value==null?"—":`$${value}`;
const signedMoney=(value:number|null|undefined)=>value==null?"—":`${value>=0?"+":"-"}$${Math.abs(value)}`;
const percent=(value:number|null|undefined)=>value==null?"—":`${(value*100).toFixed(1)}%`;
const bandLabel=(value:DecisionBand)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());

export function DraftRoom(){
  const [data,setData]=useState<DraftRoomData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [position,setPosition]=useState("ALL"),[sort,setSort]=useState<SortKey>("expected"),[ascending,setAscending]=useState(false),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null);
  const [poolView,setPoolView]=useState<PoolView>("undrafted");
  const [nominator,setNominator]=useState(""),[winner,setWinner]=useState(""),[price,setPrice]=useState(""),[saleOpen,setSaleOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
  const [resetOpen,setResetOpen]=useState(false),[resetConfirmation,setResetConfirmation]=useState(""),[preservePreferences,setPreservePreferences]=useState(true);
  const [leaderboardOpen,setLeaderboardOpen]=useState(false);
  const [nominationOrderOpen,setNominationOrderOpen]=useState(false),[nominationOrderDraft,setNominationOrderDraft]=useState<string[]>([]);
  const [strategyOpen,setStrategyOpen]=useState(false),[strategyDraft,setStrategyDraft]=useState<Strategy|null>(null),[situationsText,setSituationsText]=useState("");
  const [gmQuestion,setGmQuestion]=useState(""),[gmMessages,setGmMessages]=useState<{role:"user"|"assistant";text:string}[]>([]);
  const [rosterTeamId,setRosterTeamId]=useState(""),[draggedPlayerId,setDraggedPlayerId]=useState<string|null>(null),[dropSlotId,setDropSlotId]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch("/api/draft",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"The draft could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{if(data&&!data.currentNomination)setNominator(data.nominationOrder.nextTeamId??"");},[data?.currentNomination?.id,data?.nominationOrder.nextTeamId]);
  useEffect(()=>{const focus=(event:KeyboardEvent)=>{if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"){event.preventDefault();document.getElementById("player-search")?.focus();}};window.addEventListener("keydown",focus);return()=>window.removeEventListener("keydown",focus);},[]);
  async function act(action:object){setBusy(true);setError("");try{const response=await fetch("/api/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setSaleOpen(false);setPrice("");}catch(reason){setError(reason instanceof Error?reason.message:"The action was not saved.");}finally{setBusy(false);}}
  const available=useMemo(()=>{if(!data)return[];const inPool=(player:Player)=>poolView==="all"?player.status!=="removed":poolView==="drafted"?player.status==="sold":player.status!=="sold"&&player.status!=="removed";const displayPrice=(player:Player)=>player.status==="sold"?player.salePrice:player.liveExpectedPrice;const filtered=data.players.filter(player=>inPool(player)&&(position==="ALL"||player.position===position)&&player.name.toLowerCase().includes(query.toLowerCase()));const direction=ascending?1:-1;return filtered.sort((a,b)=>{if(sort==="name")return a.name.localeCompare(b.name)*direction;const av=sort==="edge"?a.liveEdge:sort==="adp"?a.marketAdp:sort==="bye"?a.byeWeek:displayPrice(a),bv=sort==="edge"?b.liveEdge:sort==="adp"?b.marketAdp:sort==="bye"?b.byeWeek:displayPrice(b);return ((av??9999)-(bv??9999))*direction;});},[ascending,data,poolView,position,query,sort]);
  function chooseSort(key:SortKey){if(sort===key)setAscending(value=>!value);else{setSort(key);setAscending(key==="name"||key==="adp"||key==="bye");}}
  function moveNominationOwner(index:number,direction:-1|1){setNominationOrderDraft(order=>{const next=[...order],target=index+direction;if(target<0||target>=next.length)return order;[next[index],next[target]]=[next[target]!,next[index]!];return next;});}
  function askAssistantGm(){const question=gmQuestion.trim();if(!question||!focus)return;const lower=question.toLowerCase();let answer:string;if(lower.includes("bye"))answer=`${focus.name} has a Week ${focus.byeWeek??"unknown"} bye. Your saved bye-week preference is already included as a soft adjustment in the recommendation.`;else if(lower.includes("alternative")||lower.includes("instead"))answer=data?.currentNomination?.alternatives.length?`The closest alternatives are ${data.currentNomination.alternatives.map(player=>`${player.name} around ${money(player.liveExpectedPrice)}`).join(", ")}.`:`Comparable alternatives will be calculated after the player is officially nominated.`;else if(lower.includes("budget")||lower.includes("max"))answer=`You have ${money(renegades?.remainingBudget)} remaining and a maximum legal bid of ${money(renegades?.maxBid)}. The recommended player ceiling is ${money(suggestedCeiling)}.`;else answer=championshipDecision?`${bandLabel(championshipDecision.band)} at the expected price. ${championshipDecision.explanation}`:`The current preview shows ${signedMoney(focus.liveEdge)} of live edge. Officially nominate the player for the full price ladder and room-pressure read.`;setGmMessages(messages=>[...messages,{role:"user",text:question},{role:"assistant",text:answer}]);setGmQuestion("");}
  const selected=data?.players.find(player=>player.id===selectedId)??available[0]??null;
  const focus=data?.currentNomination??selected;
  const renegades=data?.renegades;
  const rosterTeam=data?.teams.find(team=>team.id===(rosterTeamId||data.renegades?.id))??data?.renegades??data?.teams[0]??null;
  const displayedRoster=rosterTeam?data?.teamRosters[rosterTeam.id]??[]:[];
  const ownerTeams=useMemo(()=>[...(data?.teams??[])].sort((a,b)=>a.owner.localeCompare(b.owner,undefined,{sensitivity:"base"})),[data]);
  const need=useMemo(()=>{if(!data)return"";const open=data.roster.filter(slot=>!slot.player);const premium=open.find(slot=>["WR","RB","WR_RB","WR_RB_TE"].includes(slot.slotType));return premium?`${premium.slotType.replaceAll("_","/")} is the next roster priority.`:"Protect flexibility across the remaining open slots.";},[data]);
  const nflTeams=useMemo(()=>[...new Set(data?.players.map(player=>player.nflTeam).filter((team):team is string=>Boolean(team)))].sort(),[data]);
  if(!data)return <main className="loading"><img className="loading-logo" src="/branding/rodman-renegades-logo.png" alt="Rodman Renegades"/><p>{error||"Opening your draft room…"}</p><button onClick={()=>void load()}>Try again</button></main>;
  const championshipDecision=data.currentNomination?.championshipDecision??null;
  const suggestedCeiling=championshipDecision?.recommendedMax??(focus?Math.max(1,Math.round(focus.strategyValue??focus.productionValue??focus.liveExpectedPrice??1)):null);
  return <main className="draft-app">
    <header className="app-bar"><div className="wordmark"><img src="/branding/rodman-renegades-logo.png" alt="Rodman Renegades"/> <span>Renegade Draft Room</span></div><div className="save-state"><i/>Local state saved</div><div className="save-state" title={data.sheetSync.lastError??undefined}><i className={data.sheetSync.failed?"sync-error":data.sheetSync.pending?"sync-pending":""}/>{!data.sheetSync.configured?"Draft board setup needed":data.sheetSync.failed?"Draft board retry needed":data.sheetSync.pending?"Draft board pending":"Draft board synced"}</div>{data.sheetSync.configured&&(data.sheetSync.failed>0||data.sheetSync.pending>0)&&<button className="quiet-button" disabled={busy} onClick={()=>void act({type:"retrySync"})}>Retry sync</button>}<div className="app-spacer"/><div className="max-bid-indicator" title="Your remaining budget minus $1 for every roster spot that would remain after this purchase"><span>Max bid</span><strong>{money(renegades?.maxBid)}</strong></div><div className="draft-meta">2026 JUGG · Version {data.draft.stateVersion}</div><button className="quiet-button" onClick={()=>setLeaderboardOpen(true)}>League outlook</button><button className="quiet-button" onClick={()=>{setNominationOrderDraft(data.nominationOrder.teams.map(team=>team.teamId));setNominationOrderOpen(true);}}>Nomination order</button><button className="quiet-button" onClick={()=>{setStrategyDraft(data.strategy);setSituationsText(data.strategy.situations.join("\n"));setStrategyOpen(true);}}>Renegades Strategy</button><button className="quiet-button" onClick={()=>setHistoryOpen(true)}>Full history{data.recentSales.length?` (${data.recentSales.length})`:""}</button><button className="quiet-button" onClick={()=>{setResetConfirmation("");setPreservePreferences(true);setResetOpen(true);}}>Reset draft</button></header>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}
    {data.draft.recoveryIssues.length>0&&<div className="error-banner" role="alert">Recovery audit found a state mismatch. Draft actions are paused.</div>}
    {data.draft.status==="setup"&&<section className="setup-overlay"><div><span className="kicker">2026 draft is prepared</span><h1>Ready when the room is.</h1><p>294 players, 10 owners, budgets, rosters, and model outputs are loaded locally. Starting the draft creates the first auditable event.</p><button className="primary-button" disabled={busy} onClick={()=>void act({type:"start"})}>Start the 2026 draft</button></div></section>}
    <div className="workspace">
      <section className="player-pane">
        <div className="player-tools"><label className="search-box"><span>Search</span><input id="player-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name  /"/></label><div className="position-tabs" aria-label="Filter by position">{positions.map(item=><button key={item} className={position===item?"active":""} onClick={()=>setPosition(item)}>{item==="ALL"?"All":item}</button>)}</div><div className="pool-tabs" aria-label="Filter by draft status"><button className={poolView==="undrafted"?"active":""} onClick={()=>{setPoolView("undrafted");setSelectedId(null);}}>Undrafted</button><button className={poolView==="drafted"?"active":""} onClick={()=>{setPoolView("drafted");setSelectedId(null);}}>Drafted</button><button className={poolView==="all"?"active":""} onClick={()=>{setPoolView("all");setSelectedId(null);}}>All</button></div></div>
        <div className="player-columns"><span/><button onClick={()=>chooseSort("name")}>Player {sort==="name"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("adp")}>ADP {sort==="adp"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("bye")}>Bye {sort==="bye"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("expected")}>{poolView==="drafted"?"Sale $":poolView==="all"?"Price $":"Live $"} {sort==="expected"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("edge")}>Edge {sort==="edge"?(ascending?"↑":"↓"):""}</button></div>
        <div className="player-list">{available.map(player=>{const sold=player.status==="sold";return <button key={player.id} className={`player-row ${selected?.id===player.id?"selected":""} ${poolView==="all"&&sold?"drafted-row":""}`} onClick={()=>setSelectedId(player.id)}><span className="position-tag">{player.position}</span><span className="player-identity"><strong>{player.name}{player.preference==="target"?" ★":player.preference==="avoid"?" ×":""}</strong><small>· {player.nflTeam??"FA"}{sold&&player.draftedBy?` → ${player.draftedBy}`:""}</small></span><span title={`Yahoo ${player.adpYahoo??"—"} · ESPN ${player.adpEspn??"—"}`}>{player.marketAdp??"—"}</span><span>{player.byeWeek??"—"}</span><strong title={sold?`Sold to ${player.draftedBy??"—"}`:`Pre-draft ${money(player.expectedPrice)}`}>{money(sold?player.salePrice:player.liveExpectedPrice)}</strong><strong className={(player.liveEdge??0)>=0?"positive":"negative"}>{signedMoney(player.liveEdge)}</strong></button>;})}</div>
      </section>
      <section className="decision-pane">
        {focus?<div className="decision-layout">
          <section className="dashboard-panel player-details-panel">
            <div className="panel-title"><h2>Player Details</h2><span>{data.currentNomination?`Now nominated${data.currentNomination.nominator?` · ${data.currentNomination.nominator}`:""}`:"Player preview"}</span></div>
            <div className="player-details-header"><div className="player-bio"><h1>{focus.name}</h1><p>{focus.position} · {focus.nflTeam??"Free agent"} · Bye {focus.byeWeek??"—"} · ADP {focus.marketAdp??"—"}</p></div><div className="details-actions"><button className={`quiet-button ${focus.preference==="target"?"preference-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="target"?"neutral":"target",premium:data.strategy.targetPremium,note:""})}>★ Target</button><button className={`quiet-button ${focus.preference==="avoid"?"avoid-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="avoid"?"neutral":"avoid",premium:0,note:""})}>× Avoid</button>{data.currentNomination?<><button className="quiet-button" disabled={busy} onClick={()=>void act({type:"cancelNomination"})}>Cancel nomination</button><button className="primary-button" disabled={busy} onClick={()=>{setWinner(renegades?.id??data.teams[0]?.id??"");setPrice(String(focus.liveExpectedPrice??1));setSaleOpen(true);}}>Record final sale</button></>:<><select aria-label="Nominated by" value={nominator} onChange={event=>setNominator(event.target.value)}><option value="">Nominated by…</option>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><button className="primary-button" disabled={busy} onClick={()=>void act({type:"nominate",playerId:focus.id,...(nominator?{nominatedByTeamId:nominator}:{})})}>Nominate player</button></>}</div></div>
            <div className="player-decision-cards">
              <article className="player-decision-card projected-card"><span>Projected price</span><strong>{money(focus.liveExpectedPrice)}</strong><p>Pre-draft {money(focus.expectedPrice)} · likely {money(focus.livePriceLow)}–{money(focus.livePriceHigh)}</p></article>
              <article className="player-decision-card buy-card"><span>Buy through</span><strong>{data.currentNomination?money(suggestedCeiling):"Nominate first"}</strong><p>{championshipDecision?championshipDecision.rationale.draftBecause:focus.strategyReasons[0]??need}</p></article>
              <article className="player-decision-card pass-card"><span>Pass above</span><strong>{data.currentNomination?money(suggestedCeiling):"Nominate first"}</strong><p>{championshipDecision?championshipDecision.rationale.dontDraftBecause:"The full pass threshold is calculated after official nomination."}</p></article>
              <article className="player-decision-card alternatives-card"><span>Alternatives if you pass</span>{data.currentNomination?.alternatives.map(player=><button key={player.id} onClick={()=>setSelectedId(player.id)}><b>{player.name}</b><small>{money(player.liveExpectedPrice)}</small></button>)??<p>Officially nominate the player to compare realistic alternatives.</p>}</article>
            </div>
            <div className="horizontal-decision-ladder"><div className="ladder-heading"><strong>Price ladder</strong><span>{championshipDecision?`Realistic market through ${money(championshipDecision.marketHigh)}`:"Official nomination required"}</span></div><div className="ladder-bands">{decisionBands.map(band=>{const ranges=championshipDecision?.tiers.filter(tier=>tier.band===band)??[];return <div key={band} className={`ladder-band tier-${band} ${ranges.length?"":"tier-empty"}`}><span>{bandLabel(band)}</span><strong>{ranges.length?ranges.map(tier=>tier.from===tier.to?money(tier.from):`${money(tier.from)}–${money(tier.to)}`).join(", "):"—"}</strong></div>;})}</div></div>
          </section>
          <section className="dashboard-panel assistant-gm-panel"><div className="panel-title"><h2>Assistant GM</h2><span>Offline guidance · AI connection comes next</span></div><div className="assistant-stream"><div className="gm-message assistant">{data.currentNomination?`${focus.name} projects around ${money(focus.liveExpectedPrice)}. ${championshipDecision?`${Math.round(championshipDecision.support*9)} of 9 tested roster paths favor buying at the expected price.`:"The decision ladder is being prepared."}`:data.recentSales[0]?`After the last sale of ${data.recentSales[0].player} for ${money(data.recentSales[0].price)}, select or nominate a player for an updated decision read.`:`Select a player to begin the draft conversation.`}</div>{gmMessages.map((message,index)=><div key={index} className={`gm-message ${message.role}`}>{message.text}</div>)}</div><form className="gm-input" onSubmit={event=>{event.preventDefault();askAssistantGm();}}><input value={gmQuestion} onChange={event=>setGmQuestion(event.target.value)} placeholder="Ask about this player, your roster, budget, alternatives, or bye weeks…"/><button type="submit" disabled={!gmQuestion.trim()}>Ask</button></form></section>
          <div className="bottom-details-grid">
            <section className="dashboard-panel team-roster-panel"><div className="panel-title roster-panel-title"><h2>Team Roster</h2><div><select aria-label="View owner roster" value={rosterTeam?.id??""} onChange={event=>setRosterTeamId(event.target.value)}>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><span>{rosterTeam?.rosteredCount??0} / 14 filled</span><span><b>{money(rosterTeam?.remainingBudget)}</b> left</span><span><b>{money(rosterTeam?.maxBid)}</b> max bid</span></div></div><div className="roster-table"><div className="roster-table-head"><span>Position</span><span>Player</span><span>Bye</span><span>Paid</span><span>Strength</span><span title="Points Above Replacement">PAR</span></div>{displayedRoster.map(slot=><div className={`roster-table-row ${slot.playerId?"roster-draggable":""} ${dropSlotId===slot.slotId?"roster-drop-target":""}`} key={slot.slotId} draggable={Boolean(slot.playerId)&&!busy} onDragStart={event=>{if(!slot.playerId)return;setDraggedPlayerId(slot.playerId);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",slot.playerId);}} onDragEnd={()=>{setDraggedPlayerId(null);setDropSlotId(null);}} onDragOver={event=>{if(!draggedPlayerId)return;event.preventDefault();event.dataTransfer.dropEffect="move";setDropSlotId(slot.slotId);}} onDragLeave={()=>setDropSlotId(current=>current===slot.slotId?null:current)} onDrop={event=>{event.preventDefault();const playerId=draggedPlayerId||event.dataTransfer.getData("text/plain");setDraggedPlayerId(null);setDropSlotId(null);if(playerId&&rosterTeam)void act({type:"reassignRosterSlot",teamId:rosterTeam.id,playerId,targetSlotId:slot.slotId});}} title={slot.playerId?"Drag this player to another eligible roster slot":"Drop an eligible player here"}><span>{slot.slotType.replaceAll("_","/")}</span><strong>{slot.player??"Open"}</strong><span>{slot.byeWeek??"—"}</span><span>{money(slot.pricePaid)}</span><span className={`roster-strength strength-${slot.strength?.toLowerCase()??"open"}`} title={slot.strength?`${slot.position}${slot.positionRank??"—"}`:"Open roster slot"}>{slot.strength??"Open"}</span><span className={slot.pointsAboveReplacement!=null&&slot.pointsAboveReplacement>0?"positive":""}>{slot.pointsAboveReplacement==null?"—":`${slot.pointsAboveReplacement>=0?"+":""}${slot.pointsAboveReplacement.toFixed(1)}`}</span></div>)}</div></section>
            <section className="dashboard-panel league-details-panel"><div className="panel-title"><h2>League Details</h2><span>{data.currentNomination?.competition.length??0} likely bidders</span></div><div className="market-line"><span>Live JUGG market</span><strong>{data.market.salesCount?`${Math.round((data.market.globalMultiplier-1)*100)}% vs model`:"Waiting for sales"}</strong></div>{data.currentNomination?<div className="competition-list">{data.currentNomination.competition.map((team,index)=><div key={team.id}><span><strong>{team.name}</strong><small>{team.signal??(index===0?`Needs align with ${focus.position}`:"Budget and roster flexibility remain")}</small></span><strong>{money(team.maxBid)} max</strong></div>)}</div>:<p className="empty-copy">Officially nominate the player to identify competing team needs and owner pressure.</p>}{data.currentNomination?.ownerSignal&&<article className="signal-card"><span className="kicker">Owner trend</span><strong>{data.currentNomination.ownerSignal}</strong><small>Historical tendency, not certain intent.</small></article>}</section>
          </div>
        </div>:<div className="empty-decision"><img className="empty-logo" src="/branding/rodman-renegades-logo.png" alt=""/><h1>Choose a player</h1><p>Search or filter the available pool to preview a recommendation.</p></div>}
      </section>
    </div>
    {saleOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSaleOpen(false);}}><section className="sale-modal" role="dialog" aria-modal="true" aria-labelledby="sale-title"><span className="kicker">Final sale</span><h2 id="sale-title">Record {focus.name}</h2><label>Winning owner<select value={winner} onChange={event=>setWinner(event.target.value)}>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner} · {money(team.remainingBudget)} left</option>)}</select></label><label>Sale price<input type="number" min="1" inputMode="numeric" value={price} onChange={event=>setPrice(event.target.value)}/></label><div className="sale-check">{(()=>{const team=data.teams.find(item=>item.id===winner);return team?<><span>Maximum legal bid</span><strong>{money(team.maxBid)}</strong><span>Open slots after sale</span><strong>{team.openSlots-1}</strong></>:null;})()}</div><div className="modal-actions"><button className="quiet-button" onClick={()=>setSaleOpen(false)}>Cancel</button><button className="primary-button" disabled={busy||!winner||!Number(price)} onClick={()=>void act({type:"sale",winnerTeamId:winner,price:Number(price)})}>Confirm sale</button></div></section></div>}
    {resetOpen&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setResetOpen(false);}}><section className="sale-modal reset-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><span className="kicker">Recoverable reset</span><h2 id="reset-title">Reset the 2026 draft?</h2><p>This creates a timestamped backup, restores every budget and roster slot, makes all players available, clears draft history, and clears the shared Google draft board.</p><label className="reset-choice"><input type="checkbox" checked={preservePreferences} onChange={event=>setPreservePreferences(event.target.checked)}/><span>Keep Renegades strategy and player target/avoid preferences</span></label><label>Type <strong>RESET</strong> to confirm<input autoFocus value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)} placeholder="RESET"/></label><div className="modal-actions"><button className="quiet-button" onClick={()=>setResetOpen(false)}>Cancel</button><button className="danger-button" disabled={busy||resetConfirmation!=="RESET"} onClick={()=>void act({type:"resetDraft",confirmation:resetConfirmation,preservePreferences}).then(()=>setResetOpen(false))}>Reset draft</button></div></section></div>}
    {historyOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setHistoryOpen(false);}}><aside className="history-drawer"><div className="drawer-head"><div><span className="kicker">Audit history · {data.recentSales.length} picks</span><h2>Completed sales</h2></div><button onClick={()=>setHistoryOpen(false)}>Close</button></div>{data.recentSales.length?<div className="audit-history-list">{data.recentSales.map(sale=><div className="audit-history-row" key={sale.id}><strong>#{sale.pick}</strong><span><b>{sale.player}</b><small>{sale.team}</small></span><b>{money(sale.price)}</b><button disabled={busy} onClick={()=>{if(window.confirm(`Void ${sale.player} to ${sale.team} for ${money(sale.price)}? The original action will remain in history.`))void act({type:"voidSale",saleId:sale.id});}}>Correct</button></div>)}</div>:<p className="empty-copy">No sales have been recorded.</p>}<p className="drawer-note">Corrections restore the player, roster slot, and budget while preserving the original action in the immutable audit trail.</p></aside></div>}
    {leaderboardOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setLeaderboardOpen(false);}}><aside className="history-drawer leaderboard-drawer"><div className="drawer-head"><div><span className="kicker">Live · shadow model</span><h2>League championship outlook</h2></div><button onClick={()=>setLeaderboardOpen(false)}>Close</button></div><p className="strategy-intro">Recalculates after every sale from each partial roster, remaining budget, and nine neutral completion scenarios. Close ranges should be treated as ties.</p><div className="leaderboard-head"><span>Rank</span><span>Team</span><span>Equity range</span></div>{data.leaderboard.map(row=><div className={`leaderboard-row ${row.name==="Rodman Renegades"?"renegades-row":""}`} key={row.teamId}><strong>#{row.rank}</strong><span><b>{row.name}</b><small>{row.owner}</small></span><span><b>{percent(row.championshipEquity)}</b><small>{percent(row.equityLow)}–{percent(row.equityHigh)}</small></span></div>)}</aside></div>}
    {nominationOrderOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setNominationOrderOpen(false);}}><aside className="history-drawer nomination-order-drawer"><div className="drawer-head"><div><span className="kicker">Rotation and waiver tiebreaker</span><h2>Nomination order</h2></div><button onClick={()=>setNominationOrderOpen(false)}>Close</button></div><p className="strategy-intro">The next active owner is selected automatically. Completed rosters are skipped, and finish order becomes waiver tiebreaker priority.</p><div className="nomination-order-list">{nominationOrderDraft.map((teamId,index)=>{const team=data.nominationOrder.teams.find(item=>item.teamId===teamId)!;return <div className={`nomination-order-row ${data.nominationOrder.nextTeamId===teamId?"next-nominator":""} ${team.completedAt?"completed-owner":""}`} key={teamId}><strong>{index+1}</strong><span><b>{team.owner}</b><small>{team.completedAt?`Draft finished · waiver #${team.waiverPriority}`:data.nominationOrder.nextTeamId===teamId?"Next to nominate":`${team.openSlots} roster spots open`}</small></span><div><button aria-label={`Move ${team.owner} up`} disabled={index===0} onClick={()=>moveNominationOwner(index,-1)}>↑</button><button aria-label={`Move ${team.owner} down`} disabled={index===nominationOrderDraft.length-1} onClick={()=>moveNominationOwner(index,1)}>↓</button></div></div>;})}</div><div className="modal-actions"><button className="quiet-button" onClick={()=>setNominationOrderOpen(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={()=>void act({type:"updateNominationOrder",teamIds:nominationOrderDraft}).then(()=>setNominationOrderOpen(false))}>Save order</button></div></aside></div>}
    {strategyOpen&&strategyDraft&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setStrategyOpen(false);}}><aside className="history-drawer strategy-drawer">
      <div className="drawer-head"><div><span className="kicker">Weighted preferences</span><h2>Renegades Strategy</h2></div><button onClick={()=>setStrategyOpen(false)}>Close</button></div>
      <p className="strategy-intro">Preferences make limited adjustments to your value and recommendation. They never block a player or rewrite the JUGG market prediction.</p>
      <div className="preference-lists"><section><span className="kicker">Preferred players</span>{data.players.filter(player=>player.preference==="target").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="target")&&<small>Use ★ Target from the player view.</small>}</section><section><span className="kicker">Players to avoid</span>{data.players.filter(player=>player.preference==="avoid").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="avoid")&&<small>Use × Avoid from the player view.</small>}</section></div>
      <label>Risk tolerance<select value={strategyDraft.riskTolerance} onChange={event=>setStrategyDraft({...strategyDraft,riskTolerance:event.target.value as Strategy["riskTolerance"]})}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label>
      <label>Bye-week approach<select value={strategyDraft.byeWeekMode} onChange={event=>setStrategyDraft({...strategyDraft,byeWeekMode:event.target.value as Strategy["byeWeekMode"]})}><option value="ignore">Ignore overlap</option><option value="soft">Discourage overlap</option><option value="strict">Strongly discourage overlap</option></select></label>
      <div className="strategy-pair"><label>Players on same bye<input type="number" min="1" max="6" value={strategyDraft.maxSameBye} onChange={event=>setStrategyDraft({...strategyDraft,maxSameBye:Number(event.target.value)})}/></label><label>Default target premium<input type="number" min="0" max="20" value={strategyDraft.targetPremium} onChange={event=>setStrategyDraft({...strategyDraft,targetPremium:Number(event.target.value)})}/></label></div>
      <div className="team-preference-heading"><div><span className="kicker">NFL-team preferences</span><p>Optionally apply a small preference to all players or one position.</p></div><button className="quiet-button" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:[...strategyDraft.teamPreferences,{team:nflTeams[0]??"ARI",position:"ALL",preference:"prefer",adjustment:2,note:""}]})}>Add team preference</button></div>
      <div className="team-preferences">{strategyDraft.teamPreferences.map((rule,index)=><div className="team-rule" key={`${index}:${rule.team}:${rule.position}`}><select aria-label="NFL team" value={rule.team} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,team:event.target.value}:item)})}>{nflTeams.map(team=><option key={team}>{team}</option>)}</select><select aria-label="Position" value={rule.position} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,position:event.target.value as TeamPreference["position"]}:item)})}><option value="ALL">All</option>{positions.slice(1).map(item=><option key={item}>{item}</option>)}</select><select aria-label="Preference" value={rule.preference} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,preference:event.target.value as TeamPreference["preference"]}:item)})}><option value="prefer">Prefer</option><option value="avoid">Avoid</option></select><input aria-label="Dollar adjustment" type="number" min="1" max="5" value={rule.adjustment} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,adjustment:Number(event.target.value)}:item)})}/><button aria-label="Remove team preference" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.filter((_,itemIndex)=>itemIndex!==index)})}>×</button></div>)}</div>
      <label>Situations you like<textarea value={situationsText} onChange={event=>setSituationsText(event.target.value)} placeholder={"One per line, for example:\nYoung WR with established target share\nMobile quarterback"}/></label>
      <label>Strategy notes<textarea value={strategyDraft.notes} onChange={event=>setStrategyDraft({...strategyDraft,notes:event.target.value})} placeholder="Anything else the recommendation system should keep in mind."/></label>
      <div className="modal-actions"><button className="quiet-button" onClick={()=>setStrategyOpen(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={()=>void act({type:"updateStrategy",strategy:{...strategyDraft,situations:situationsText.split("\n").map(value=>value.trim()).filter(Boolean)}}).then(()=>setStrategyOpen(false))}>Save strategy</button></div>
    </aside></div>}
  </main>;
}
