"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Player={id:string;name:string;position:string;nflTeam:string|null;status:string;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;productionValue:number|null;strategyValue:number|null;edge:number|null;liveEdge:number|null;adpEspn:number|null;adpYahoo:number|null;marketAdp:number|null;byeWeek:number|null;preference:"target"|"avoid"|null;preferencePremium:number|null;strategyReasons:string[];riskFlags:string[]};
type Team={id:string;name:string;owner:string;remainingBudget:number;openSlots:number;rosteredCount:number;maxBid:number};
type Sale={id:string;pick:number;player:string;team:string;price:number};
type Nomination=Player&{playerId:string;nominator:string|null;ownerSignal:string|null;competition:{id:string;name:string;maxBid:number;signal:string|null}[];alternatives:Player[]};
type TeamPreference={team:string;position:"ALL"|"QB"|"RB"|"WR"|"TE"|"K"|"DEF";preference:"prefer"|"avoid";adjustment:number;note:string};
type Strategy={buildStyle:"balanced"|"stars_and_scrubs"|"value_first";riskTolerance:"conservative"|"balanced"|"aggressive";byeWeekMode:"ignore"|"soft"|"strict";maxSameBye:number;targetPremium:number;situations:string[];teamPreferences:TeamPreference[];notes:string};
type DraftRoomData={draft:{status:string;stateVersion:number;recoveryIssues:string[]};players:Player[];teams:Team[];renegades:Team|null;roster:{slotType:string;ordinal:number;player:string|null;position:string|null}[];currentNomination:Nomination|null;recentSales:Sale[];strategy:Strategy;market:{salesCount:number;globalMultiplier:number};sheetSync:{configured:boolean;pending:number;failed:number;succeeded:number;lastError:string|null};localSaved:boolean};
type SortKey="expected"|"edge"|"adp"|"bye"|"name";

const positions=["ALL","QB","RB","WR","TE","K","DEF"];
const money=(value:number|null|undefined)=>value==null?"—":`$${value}`;

export function DraftRoom(){
  const [data,setData]=useState<DraftRoomData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [position,setPosition]=useState("ALL"),[sort,setSort]=useState<SortKey>("expected"),[ascending,setAscending]=useState(false),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null);
  const [nominator,setNominator]=useState(""),[winner,setWinner]=useState(""),[price,setPrice]=useState(""),[saleOpen,setSaleOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
  const [resetOpen,setResetOpen]=useState(false),[resetConfirmation,setResetConfirmation]=useState(""),[preservePreferences,setPreservePreferences]=useState(true);
  const [strategyOpen,setStrategyOpen]=useState(false),[strategyDraft,setStrategyDraft]=useState<Strategy|null>(null),[situationsText,setSituationsText]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/draft",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"The draft could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{const focus=(event:KeyboardEvent)=>{if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"){event.preventDefault();document.getElementById("player-search")?.focus();}};window.addEventListener("keydown",focus);return()=>window.removeEventListener("keydown",focus);},[]);
  async function act(action:object){setBusy(true);setError("");try{const response=await fetch("/api/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setSaleOpen(false);setPrice("");}catch(reason){setError(reason instanceof Error?reason.message:"The action was not saved.");}finally{setBusy(false);}}
  const available=useMemo(()=>{if(!data)return[];const filtered=data.players.filter(player=>player.status==="available"&&(position==="ALL"||player.position===position)&&player.name.toLowerCase().includes(query.toLowerCase()));const direction=ascending?1:-1;return filtered.sort((a,b)=>{if(sort==="name")return a.name.localeCompare(b.name)*direction;const av=sort==="edge"?a.liveEdge:sort==="adp"?a.marketAdp:sort==="bye"?a.byeWeek:a.liveExpectedPrice,bv=sort==="edge"?b.liveEdge:sort==="adp"?b.marketAdp:sort==="bye"?b.byeWeek:b.liveExpectedPrice;return ((av??9999)-(bv??9999))*direction;});},[ascending,data,position,query,sort]);
  function chooseSort(key:SortKey){if(sort===key)setAscending(value=>!value);else{setSort(key);setAscending(key==="name"||key==="adp"||key==="bye");}}
  const selected=data?.players.find(player=>player.id===selectedId)??available[0]??null;
  const focus=data?.currentNomination??selected;
  const renegades=data?.renegades;
  const need=useMemo(()=>{if(!data)return"";const open=data.roster.filter(slot=>!slot.player);const premium=open.find(slot=>["WR","RB","WR_RB","WR_RB_TE"].includes(slot.slotType));return premium?`${premium.slotType.replaceAll("_","/")} is the next roster priority.`:"Protect flexibility across the remaining open slots.";},[data]);
  const nflTeams=useMemo(()=>[...new Set(data?.players.map(player=>player.nflTeam).filter((team):team is string=>Boolean(team)))].sort(),[data]);
  if(!data)return <main className="loading"><div className="load-mark">R</div><p>{error||"Opening your draft room…"}</p><button onClick={()=>void load()}>Try again</button></main>;
  const suggestedCeiling=focus?Math.max(1,Math.round(focus.strategyValue??focus.productionValue??focus.liveExpectedPrice??1)):null;
  return <main className="draft-app">
    <header className="app-bar"><div className="wordmark"><span>R</span> Renegade Draft Room</div><div className="save-state"><i/>Local state saved</div><div className="save-state" title={data.sheetSync.lastError??undefined}><i className={data.sheetSync.failed?"sync-error":data.sheetSync.pending?"sync-pending":""}/>{!data.sheetSync.configured?"Draft board setup needed":data.sheetSync.failed?"Draft board retry needed":data.sheetSync.pending?"Draft board pending":"Draft board synced"}</div>{data.sheetSync.configured&&(data.sheetSync.failed>0||data.sheetSync.pending>0)&&<button className="quiet-button" disabled={busy} onClick={()=>void act({type:"retrySync"})}>Retry sync</button>}<div className="app-spacer"/><div className="draft-meta">2026 JUGG · Version {data.draft.stateVersion}</div><button className="quiet-button" onClick={()=>{setStrategyDraft(data.strategy);setSituationsText(data.strategy.situations.join("\n"));setStrategyOpen(true);}}>Renegades Strategy</button><button className="quiet-button" onClick={()=>setHistoryOpen(true)}>Full history</button><button className="quiet-button" onClick={()=>{setResetConfirmation("");setPreservePreferences(true);setResetOpen(true);}}>Reset draft</button></header>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}
    {data.draft.recoveryIssues.length>0&&<div className="error-banner" role="alert">Recovery audit found a state mismatch. Draft actions are paused.</div>}
    {data.draft.status==="setup"&&<section className="setup-overlay"><div><span className="kicker">2026 draft is prepared</span><h1>Ready when the room is.</h1><p>294 players, 10 owners, budgets, rosters, and model outputs are loaded locally. Starting the draft creates the first auditable event.</p><button className="primary-button" disabled={busy} onClick={()=>void act({type:"start"})}>Start the 2026 draft</button></div></section>}
    <div className="workspace">
      <section className="player-pane">
        <div className="player-tools"><label className="search-box"><span>Search</span><input id="player-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name  /"/></label><div className="position-tabs" aria-label="Filter by position">{positions.map(item=><button key={item} className={position===item?"active":""} onClick={()=>setPosition(item)}>{item==="ALL"?"All":item}</button>)}</div></div>
        <div className="player-columns"><span/><button onClick={()=>chooseSort("name")}>Player {sort==="name"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("adp")}>ADP {sort==="adp"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("bye")}>Bye {sort==="bye"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("expected")}>Live $ {sort==="expected"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("edge")}>Edge {sort==="edge"?(ascending?"↑":"↓"):""}</button></div>
        <div className="player-list">{available.map(player=><button key={player.id} className={`player-row ${selected?.id===player.id?"selected":""}`} onClick={()=>setSelectedId(player.id)}><span className="position-tag">{player.position}</span><span className="player-identity"><strong>{player.name}{player.preference==="target"?" ★":player.preference==="avoid"?" ×":""}</strong><small>{player.nflTeam??"FA"}</small></span><span title={`Yahoo ${player.adpYahoo??"—"} · ESPN ${player.adpEspn??"—"}`}>{player.marketAdp??"—"}</span><span>{player.byeWeek??"—"}</span><strong title={`Pre-draft ${money(player.expectedPrice)}`}>{money(player.liveExpectedPrice)}</strong><strong className={(player.liveEdge??0)>=0?"positive":"negative"}>{player.liveEdge==null?"—":`${player.liveEdge>=0?"+":""}$${player.liveEdge}`}</strong></button>)}</div>
      </section>
      <section className="decision-pane">
        {focus?<>
          <div className="nomination-band"><div className="player-lead"><span className="kicker">{data.currentNomination?`Now nominated${data.currentNomination.nominator?` · ${data.currentNomination.nominator}`:""}`:"Player preview"}</span><h1>{focus.name}</h1><p>{focus.position} · {focus.nflTeam??"Free agent"} · Bye {focus.byeWeek??"—"} · ADP {focus.marketAdp??"—"}</p></div><div className="headline-metric"><span>Live expected</span><strong>{money(focus.liveExpectedPrice)}</strong><small>pre-draft {money(focus.expectedPrice)} · {money(focus.livePriceLow)}–{focus.livePriceHigh??"—"}</small></div><div className="headline-metric"><span>Renegades value</span><strong className="positive">{money(focus.strategyValue)}</strong><small className={(focus.liveEdge??0)>0?"positive":""}>{(focus.liveEdge??0)>0?"Worth pursuing":"Stay disciplined"}</small></div><div className="decision-call"><span>{data.currentNomination?"Recommendation":"Strategy read"}</span><strong>{data.currentNomination?`Buy up to ${money(suggestedCeiling)}.`:`${focus.liveEdge==null?"—":`${focus.liveEdge>=0?"+":""}$${focus.liveEdge}`} live edge`}</strong><small>{focus.strategyReasons[0]??need}</small></div></div>
          <div className="decision-body">
            <div className="guidance-column">
              <div className="team-heading"><div><span className="kicker">Your team</span><h2>Rodman Renegades</h2></div><div className="budget"><strong>{money(renegades?.remainingBudget)}</strong><small>{renegades?.rosteredCount} / 14 filled</small></div></div>
              <div className="guidance-grid"><article><span className="kicker">Roster need</span><p><strong>{need}</strong> You can spend up to {money(renegades?.maxBid)} while preserving one dollar for every other open slot.</p></article><article className="why-card"><span className="kicker">Why {focus.name.split(" ").at(-1)}</span><strong className="positive">{focus.liveEdge==null?"Value pending":`${focus.liveEdge>=0?"+":""}$${focus.liveEdge} live edge`}</strong><p>{focus.strategyReasons.join(" · ")||"Production value compared with the live JUGG market."}</p></article></div>
              <div className="roster-strip">{data.roster.slice(0,9).map(slot=><div key={`${slot.slotType}:${slot.ordinal}`}><span>{slot.slotType.replaceAll("_","/")}</span><strong>{slot.player??"Open"}</strong></div>)}</div>
              <div className="action-row"><button className={`quiet-button ${focus.preference==="target"?"preference-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="target"?"neutral":"target",premium:data.strategy.targetPremium,note:""})}>★ Target</button><button className={`quiet-button ${focus.preference==="avoid"?"avoid-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="avoid"?"neutral":"avoid",premium:0,note:""})}>× Avoid</button>{data.currentNomination?<><button className="quiet-button" disabled={busy} onClick={()=>void act({type:"cancelNomination"})}>Cancel nomination</button><button className="primary-button" disabled={busy} onClick={()=>{setWinner(renegades?.id??data.teams[0]?.id??"");setPrice(String(focus.liveExpectedPrice??1));setSaleOpen(true);}}>Record final sale</button></>:<><select aria-label="Nominated by" value={nominator} onChange={event=>setNominator(event.target.value)}><option value="">Nominated by…</option>{data.teams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><button className="primary-button" disabled={busy} onClick={()=>void act({type:"nominate",playerId:focus.id,...(nominator?{nominatedByTeamId:nominator}:{})})}>Nominate player</button></>}</div>
            </div>
            <aside className="intelligence-column">
              <div className="section-heading"><h2>Room pressure</h2><span>{data.currentNomination?.competition.length??0} likely bidders</span></div><div className="market-line"><span>Live JUGG market</span><strong>{data.market.salesCount?`${Math.round((data.market.globalMultiplier-1)*100)}% vs model`:"Waiting for sales"}</strong></div>
              {data.currentNomination?<div className="competition-list">{data.currentNomination.competition.map((team,index)=><div key={team.id}><span><strong>{team.name}</strong><small>{team.signal??(index===0?"Budget + roster flexibility":"Can remain involved")}</small></span><strong>{money(team.maxBid)}</strong></div>)}</div>:<p className="empty-copy">Nominate the player to calculate likely competition and useful owner signals.</p>}
              {data.currentNomination?.ownerSignal&&<article className="signal-card"><span className="kicker">Useful signal</span><strong>{data.currentNomination.ownerSignal}</strong><small>Historical tendency, not certain intent.</small></article>}
              <div className="section-heading alternatives-heading"><h2>If the price runs away</h2><span>Next best</span></div>
              <div className="alternatives">{data.currentNomination?.alternatives.map(player=><button key={player.id} onClick={()=>setSelectedId(player.id)}><span><strong>{player.name}</strong><small>{player.position} · {player.nflTeam}</small></span><strong>{money(player.liveExpectedPrice)}</strong></button>)??<p className="empty-copy">Comparable alternatives will appear after nomination.</p>}</div>
            </aside>
          </div>
        </>:<div className="empty-decision"><span>R</span><h1>Choose a player</h1><p>Search or filter the available pool to preview a recommendation.</p></div>}
      </section>
    </div>
    <section className="recent-strip"><div className="recent-title"><span className="kicker">Last 5 picks</span><button onClick={()=>setHistoryOpen(true)}>View all</button></div>{data.recentSales.length?data.recentSales.map(sale=><div className="recent-pick" key={sale.id}><span>#{sale.pick}</span><strong>{sale.player}</strong><small>{sale.team}</small><b>{money(sale.price)}</b><button disabled={busy} onClick={()=>{if(window.confirm(`Void ${sale.player} to ${sale.team} for ${money(sale.price)}? The original action will remain in history.`))void act({type:"voidSale",saleId:sale.id});}}>Correct</button></div>):<div className="no-picks">No completed sales yet.</div>}</section>
    {saleOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSaleOpen(false);}}><section className="sale-modal" role="dialog" aria-modal="true" aria-labelledby="sale-title"><span className="kicker">Final sale</span><h2 id="sale-title">Record {focus.name}</h2><label>Winning team<select value={winner} onChange={event=>setWinner(event.target.value)}>{data.teams.map(team=><option key={team.id} value={team.id}>{team.name} · {money(team.remainingBudget)} left</option>)}</select></label><label>Sale price<input type="number" min="1" inputMode="numeric" value={price} onChange={event=>setPrice(event.target.value)}/></label><div className="sale-check">{(()=>{const team=data.teams.find(item=>item.id===winner);return team?<><span>Maximum legal bid</span><strong>{money(team.maxBid)}</strong><span>Open slots after sale</span><strong>{team.openSlots-1}</strong></>:null;})()}</div><div className="modal-actions"><button className="quiet-button" onClick={()=>setSaleOpen(false)}>Cancel</button><button className="primary-button" disabled={busy||!winner||!Number(price)} onClick={()=>void act({type:"sale",winnerTeamId:winner,price:Number(price)})}>Confirm sale</button></div></section></div>}
    {resetOpen&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setResetOpen(false);}}><section className="sale-modal reset-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><span className="kicker">Recoverable reset</span><h2 id="reset-title">Reset the 2026 draft?</h2><p>This creates a timestamped backup, restores every budget and roster slot, makes all players available, clears draft history, and clears the shared Google draft board.</p><label className="reset-choice"><input type="checkbox" checked={preservePreferences} onChange={event=>setPreservePreferences(event.target.checked)}/><span>Keep Renegades strategy and player target/avoid preferences</span></label><label>Type <strong>RESET</strong> to confirm<input autoFocus value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)} placeholder="RESET"/></label><div className="modal-actions"><button className="quiet-button" onClick={()=>setResetOpen(false)}>Cancel</button><button className="danger-button" disabled={busy||resetConfirmation!=="RESET"} onClick={()=>void act({type:"resetDraft",confirmation:resetConfirmation,preservePreferences}).then(()=>setResetOpen(false))}>Reset draft</button></div></section></div>}
    {historyOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setHistoryOpen(false);}}><aside className="history-drawer"><div className="drawer-head"><div><span className="kicker">Audit history</span><h2>Completed sales</h2></div><button onClick={()=>setHistoryOpen(false)}>Close</button></div>{data.recentSales.length?data.recentSales.map(sale=><div className="drawer-sale" key={sale.id}><span>Pick #{sale.pick}</span><strong>{sale.player}</strong><small>{sale.team}</small><b>{money(sale.price)}</b></div>):<p className="empty-copy">No sales have been recorded.</p>}<p className="drawer-note">The full event-by-event audit trail will remain immutable. Corrections append a compensating event.</p></aside></div>}
    {strategyOpen&&strategyDraft&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setStrategyOpen(false);}}><aside className="history-drawer strategy-drawer">
      <div className="drawer-head"><div><span className="kicker">Weighted preferences</span><h2>Renegades Strategy</h2></div><button onClick={()=>setStrategyOpen(false)}>Close</button></div>
      <p className="strategy-intro">Preferences make limited adjustments to your value and recommendation. They never block a player or rewrite the JUGG market prediction.</p>
      <div className="preference-lists"><section><span className="kicker">Preferred players</span>{data.players.filter(player=>player.preference==="target").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="target")&&<small>Use ★ Target from the player view.</small>}</section><section><span className="kicker">Players to avoid</span>{data.players.filter(player=>player.preference==="avoid").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="avoid")&&<small>Use × Avoid from the player view.</small>}</section></div>
      <label>Roster construction<select value={strategyDraft.buildStyle} onChange={event=>setStrategyDraft({...strategyDraft,buildStyle:event.target.value as Strategy["buildStyle"]})}><option value="balanced">Balanced</option><option value="stars_and_scrubs">Stars and scrubs</option><option value="value_first">Value first</option></select></label>
      <label>Risk tolerance<select value={strategyDraft.riskTolerance} onChange={event=>setStrategyDraft({...strategyDraft,riskTolerance:event.target.value as Strategy["riskTolerance"]})}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label>
      <label>Bye-week approach<select value={strategyDraft.byeWeekMode} onChange={event=>setStrategyDraft({...strategyDraft,byeWeekMode:event.target.value as Strategy["byeWeekMode"]})}><option value="ignore">Ignore overlap</option><option value="soft">Discourage overlap</option><option value="strict">Strongly discourage overlap</option></select></label>
      <div className="strategy-pair"><label>Players on same bye<input type="number" min="1" max="6" value={strategyDraft.maxSameBye} onChange={event=>setStrategyDraft({...strategyDraft,maxSameBye:Number(event.target.value)})}/></label><label>Default target premium<input type="number" min="0" max="20" value={strategyDraft.targetPremium} onChange={event=>setStrategyDraft({...strategyDraft,targetPremium:Number(event.target.value)})}/></label></div>
      <div className="team-preference-heading"><div><span className="kicker">NFL-team preferences</span><p>Optionally apply a small preference to all players or one position.</p></div><button className="quiet-button" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:[...strategyDraft.teamPreferences,{team:nflTeams[0]??"ARI",position:"ALL",preference:"prefer",adjustment:2,note:""}]})}>Add team preference</button></div>
      <div className="team-preferences">{strategyDraft.teamPreferences.map((rule,index)=><div className="team-rule" key={`${index}:${rule.team}:${rule.position}`}><select aria-label="NFL team" value={rule.team} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,team:event.target.value}:item)})}>{nflTeams.map(team=><option key={team}>{team}</option>)}</select><select aria-label="Position" value={rule.position} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,position:event.target.value as TeamPreference["position"]}:item)})}><option value="ALL">All</option>{positions.slice(1).map(item=><option key={item}>{item}</option>)}</select><select aria-label="Preference" value={rule.preference} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,preference:event.target.value as TeamPreference["preference"]}:item)})}><option value="prefer">Prefer</option><option value="avoid">Avoid</option></select><input aria-label="Dollar adjustment" type="number" min="1" max="5" value={rule.adjustment} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,adjustment:Number(event.target.value)}:item)})}/><button aria-label="Remove team preference" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.filter((_,itemIndex)=>itemIndex!==index)})}>×</button></div>)}</div>
      <label>Situations you like<textarea value={situationsText} onChange={event=>setSituationsText(event.target.value)} placeholder={"One per line, for example:\nYoung WR with established target share\nMobile quarterback"}/></label>
      <label>Strategy notes<textarea value={strategyDraft.notes} onChange={event=>setStrategyDraft({...strategyDraft,notes:event.target.value})} placeholder="Anything else the recommendation system should keep in mind."/></label>
      <div className="modal-actions"><button className="quiet-button" onClick={()=>setStrategyOpen(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={()=>void act({type:"updateStrategy",strategy:{...strategyDraft,situations:situationsText.split("\n").map(value=>value.trim()).filter(Boolean)}}).then(()=>setStrategyOpen(false))}>Save strategy</button></div>
    </aside></div>}
  </main>;
}
