"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type StatLine={season:number;games:number|null;fantasy_points:number;points_per_game?:number;stats:Record<string,number>;source:string};
type DraftImpact={price:number;band:DecisionBand;label:"Great Add"|"Good Add"|"Neutral"|"Poor Add"|"Bad Add";expectedEquityDelta:number;scenarioSupport:number;role:string;summary:string};
type Player={id:string;name:string;position:string;nflTeam:string|null;status:string;salePrice:number|null;draftedBy:string|null;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;productionValue:number|null;strategyValue:number|null;edge:number|null;liveEdge:number|null;decisionCeiling:number|null;decisionEdge:number|null;draftImpact:DraftImpact|null;adpEspn:number|null;adpYahoo:number|null;marketAdp:number|null;byeWeek:number|null;preference:"target"|"avoid"|null;preferencePremium:number|null;strategyReasons:string[];riskFlags:string[];projectedPoints:number;positionRank:number|null;replacementPoints:number|null;pointsAboveReplacement:number|null;productionLabel:"Elite"|"Premium"|"Starter"|"Depth"|"Replacement";productionTier:number|null;productionTierSize:number|null;productionTierHigh:number|null;productionTierLow:number|null;auctionTier:number|null;auctionTierSize:number|null;auctionTierHigh:number|null;auctionTierLow:number|null;lastSeasonStatLine:StatLine|null;projectedStatLine:StatLine|null};
type Team={id:string;name:string;owner:string;remainingBudget:number;openSlots:number;rosteredCount:number;maxBid:number};
type Sale={id:string;pick:number;player:string;team:string;price:number};
type DecisionBand="strong_pursue"|"lean_pursue"|"neutral"|"lean_pass"|"strong_pass";
type ChampionshipDecision={price:number;band:DecisionBand;medianDelta:number;support:number;equityLow:number;equityHigh:number;recommendedMax:number|null;baselineRecommendedMax:number|null;preferenceAdjustment:number;evaluatedMax:number;marketHigh:number;stretchCeiling:number;extremeCeiling:number;tiers:{from:number;to:number;band:DecisionBand}[];tierContext:{productionTier:number|null;productionTierRemaining:number;auctionTier:number|null;auctionTierRemaining:number;nextProductionTierPlayer:string|null;nextProductionTier:number|null};rationale:{draftBecause:string;dontDraftBecause:string};modelStatus:"shadow";explanation:string};
type DecisionPlan={recommendedCeiling:number;committedCeiling:number;adjustmentReason:string|null;createdAt:string;updatedAt:string};
type Nomination=Player&{nominationId:string;playerId:string;nominator:string|null;ownerSignal:string|null;competition:{id:string;name:string;maxBid:number;signal:string|null}[];alternatives:Player[];championshipDecision:ChampionshipDecision|null;decisionPlan:DecisionPlan};
type TeamPreference={team:string;position:"ALL"|"QB"|"RB"|"WR"|"TE"|"K"|"DEF";preference:"prefer"|"avoid";adjustment:number;note:string};
type Strategy={buildStyle:"balanced"|"stars_and_scrubs"|"value_first";riskTolerance:"conservative"|"balanced"|"aggressive";byeWeekMode:"ignore"|"soft"|"strict";maxSameBye:number;targetPremium:number;situations:string[];teamPreferences:TeamPreference[];notes:string};
type LeaderboardRow={rank:number;teamId:string;name:string;owner:string;championshipEquity:number;equityLow:number;equityHigh:number;projectedLineupPoints:number};
type RosterSlot={slotId:string;teamId:string;slotType:string;ordinal:number;eligiblePositions:string[];playerId:string|null;player:string|null;position:string|null;byeWeek:number|null;pricePaid:number|null;positionRank:number|null;pointsAboveReplacement:number|null;productionLabel:"Elite"|"Premium"|"Starter"|"Depth"|"Replacement"|null};
type NominationOrderTeam={teamId:string;ordinal:number;team:string;owner:string;openSlots:number;completedAt:string|null;waiverPriority:number|null};
type UpcomingTarget={rank:number;playerId:string;name:string;position:string;role:string;targetPrice:number;walkawayCeiling:number;expectedEquityDelta:number;scenarioSupport:number;productionTier:number|null;tierRemaining:number;tierDropPoints:number;replacementPlayer:string|null;replacementPrice:number|null;why:string;conditionalPlan:string;strategyReasons:string[]};
type WhatChanged={snapshotId:string;triggerType:string;headline:string;reasons:string[];createdAt:string};
type DraftRoomData={draft:{status:string;stateVersion:number;recoveryIssues:string[]};players:Player[];teams:Team[];renegades:Team|null;roster:RosterSlot[];teamRosters:Record<string,RosterSlot[]>;nominationOrder:{teams:NominationOrderTeam[];nextTeamId:string|null};currentNomination:Nomination|null;leaderboard:LeaderboardRow[];recentSales:Sale[];strategy:Strategy;market:{salesCount:number;globalMultiplier:number};upcomingTargets:UpcomingTarget[];whatChanged:WhatChanged|null;discipline:{count:number;dollarsAbovePlan:number};sheetSync:{configured:boolean;pending:number;failed:number;succeeded:number;lastError:string|null};localSaved:boolean};
type SortKey="expected"|"draftImpact"|"adp"|"bye"|"name"|"projectedPoints"|"xpar"|"predraft";
type PoolView="undrafted"|"drafted"|"all";

const positions=["ALL","QB","RB","WR","TE","K","DEF"];
const positionFilters=["ALL","QB","RB","WR","TE","RB/WR","RB/WR/TE","K","DEF"];
const decisionBands:DecisionBand[]=["strong_pursue","lean_pursue","neutral","lean_pass","strong_pass"];
const rosterImpactLabels:Record<DecisionBand,string>={strong_pursue:"Great",lean_pursue:"Good",neutral:"Neutral",lean_pass:"Poor",strong_pass:"Bad"};
const money=(value:number|null|undefined)=>value==null?"—":`$${value}`;
const signedMoney=(value:number|null|undefined)=>value==null?"—":`${value>=0?"+":"-"}$${Math.abs(value)}`;
const percent=(value:number|null|undefined)=>value==null?"—":`${(value*100).toFixed(1)}%`;
const signedPercent=(value:number|null|undefined)=>value==null?"—":`${value>=0?"+":""}${(value*100).toFixed(1)}%`;
const bandLabel=(value:DecisionBand)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
type StatColumn={key:string;label:string};
const statColumns:Record<string,StatColumn[]>={
  QB:[{key:"passing_completions",label:"CMP"},{key:"passing_attempts",label:"ATT"},{key:"completion_percentage",label:"CMP%"},{key:"passing_yards",label:"PASS YDS"},{key:"passing_tds",label:"PASS TD"},{key:"passing_interceptions",label:"INT"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"}],
  RB:[{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"yards_per_carry",label:"Y/A"},{key:"rushing_tds",label:"RUSH TD"},{key:"targets",label:"TGT"},{key:"receptions",label:"REC"},{key:"receiving_yards",label:"REC YDS"},{key:"yards_per_reception",label:"Y/R"},{key:"receiving_tds",label:"REC TD"},{key:"fumbles_lost",label:"FUM"}],
  WR:[{key:"targets",label:"TGT"},{key:"receptions",label:"REC"},{key:"receiving_yards",label:"REC YDS"},{key:"yards_per_reception",label:"Y/R"},{key:"receiving_tds",label:"REC TD"},{key:"rushing_attempts",label:"CAR"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"}],
  TE:[{key:"targets",label:"TGT"},{key:"receptions",label:"REC"},{key:"receiving_yards",label:"REC YDS"},{key:"yards_per_reception",label:"Y/R"},{key:"receiving_tds",label:"REC TD"},{key:"rushing_yards",label:"RUSH YDS"},{key:"rushing_tds",label:"RUSH TD"},{key:"fumbles_lost",label:"FUM"}],
  K:[{key:"field_goals_made",label:"FG"},{key:"field_goals_attempted",label:"FGA"},{key:"field_goal_percentage",label:"FG%"},{key:"extra_points_made",label:"XP"}],
  DEF:[{key:"sacks",label:"SACK"},{key:"interceptions",label:"INT"},{key:"fumble_recoveries",label:"FR"},{key:"defensive_tds",label:"DEF TD"},{key:"safeties",label:"SFTY"},{key:"special_teams_tds",label:"ST TD"}],
};
function statValue(line:StatLine|null,key:string){if(!line)return"—";const stats=line.stats;let value:number|undefined;if(key==="fantasy_points")value=line.fantasy_points;else if(key==="completion_percentage")value=stats.passing_attempts?100*(stats.passing_completions??0)/stats.passing_attempts:undefined;else if(key==="yards_per_carry")value=stats.rushing_attempts?(stats.rushing_yards??0)/stats.rushing_attempts:undefined;else if(key==="yards_per_reception")value=stats.receptions?(stats.receiving_yards??0)/stats.receptions:undefined;else if(key==="field_goal_percentage")value=stats.field_goals_attempted?100*(stats.field_goals_made??0)/stats.field_goals_attempted:undefined;else value=stats[key];if(value==null)return"—";if(key.endsWith("percentage"))return value.toFixed(1);return Number.isInteger(value)?value.toLocaleString():value.toFixed(1);}
function PlayerStatTable({player}:{player:Player}){const columns=statColumns[player.position]??[];const rows:[string,StatLine|null][]=[["Actual",player.lastSeasonStatLine],["Projected",player.projectedStatLine]];return <div className="season-stats"><div className="season-stats-scroll"><table><thead><tr><th>Season</th><th>GP</th>{columns.map(column=><th key={column.key}>{column.label}</th>)}<th>FANTASY PTS</th></tr></thead><tbody>{rows.map(([label,line])=><tr key={label} className={label==="Projected"?"projected-stat-row":""}><td title={line?.source}>{label==="Projected"?`x${line?.season??2026}`:line?.season??2025}</td><td>{line?.games??"—"}</td>{columns.map(column=><td key={column.key}>{statValue(line,column.key)}</td>)}<td><strong>{statValue(line,"fantasy_points")}</strong></td></tr>)}</tbody></table></div></div>}

export function DraftRoom(){
  const [data,setData]=useState<DraftRoomData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const [position,setPosition]=useState("ALL"),[sort,setSort]=useState<SortKey>("expected"),[ascending,setAscending]=useState(false),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState<string|null>(null);
  const [leftRosterOpen,setLeftRosterOpen]=useState(false);
  const [poolView,setPoolView]=useState<PoolView>("undrafted");
  const [nominator,setNominator]=useState(""),[winner,setWinner]=useState(""),[price,setPrice]=useState(""),[saleOpen,setSaleOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false),[ceilingOverrideReason,setCeilingOverrideReason]=useState("");
  const [resetOpen,setResetOpen]=useState(false),[resetConfirmation,setResetConfirmation]=useState(""),[preservePreferences,setPreservePreferences]=useState(true);
  const [leaderboardOpen,setLeaderboardOpen]=useState(false);
  const [targetsOpen,setTargetsOpen]=useState(false),[ceilingOpen,setCeilingOpen]=useState(false),[ceilingDraft,setCeilingDraft]=useState(""),[ceilingReason,setCeilingReason]=useState("");
  const [impactOpen,setImpactOpen]=useState(false),[impactPrice,setImpactPrice]=useState("");
  const [scarcityOpen,setScarcityOpen]=useState(false);
  const [priceDetailsOpen,setPriceDetailsOpen]=useState(false),[productionDetailsOpen,setProductionDetailsOpen]=useState(false);
  const [nominationOrderOpen,setNominationOrderOpen]=useState(false),[nominationOrderDraft,setNominationOrderDraft]=useState<string[]>([]);
  const [strategyOpen,setStrategyOpen]=useState(false),[strategyDraft,setStrategyDraft]=useState<Strategy|null>(null),[situationsText,setSituationsText]=useState("");
  const [gmQuestion,setGmQuestion]=useState(""),[gmMessages,setGmMessages]=useState<{role:"user"|"assistant";text:string;status?:"streaming"|"complete"|"error"|"stale"}[]>([]),[gmBusy,setGmBusy]=useState(false),[gmStatus,setGmStatus]=useState("Grounded mock provider");
  const lastGmSnapshot=useRef<string|null>(null);
  const assistantStreamRef=useRef<HTMLDivElement|null>(null);
  const [rosterTeamId,setRosterTeamId]=useState(""),[draggedPlayerId,setDraggedPlayerId]=useState<string|null>(null),[dropSlotId,setDropSlotId]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch("/api/draft",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"The draft could not be loaded.");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[load]);
  useEffect(()=>{if(data&&!data.currentNomination)setNominator(data.nominationOrder.nextTeamId??"");},[data?.currentNomination?.id,data?.nominationOrder.nextTeamId]);
  useEffect(()=>{const focus=(event:KeyboardEvent)=>{if(event.key==="/"&&document.activeElement?.tagName!=="INPUT"){event.preventDefault();document.getElementById("player-search")?.focus();}};window.addEventListener("keydown",focus);return()=>window.removeEventListener("keydown",focus);},[]);
  useEffect(()=>{const frame=window.requestAnimationFrame(()=>{const stream=assistantStreamRef.current;if(stream)stream.scrollTop=stream.scrollHeight;});return()=>window.cancelAnimationFrame(frame);},[gmMessages]);
  async function act(action:object){setBusy(true);setError("");try{const response=await fetch("/api/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const body=await response.json();if(!response.ok)throw new Error(body.message);setData(body);setSaleOpen(false);setCeilingOpen(false);setPrice("");setCeilingOverrideReason("");}catch(reason){setError(reason instanceof Error?reason.message:"The action was not saved.");}finally{setBusy(false);}}
  const available=useMemo(()=>{if(!data)return[];const inPool=(player:Player)=>poolView==="all"?player.status!=="removed":poolView==="drafted"?player.status==="sold":player.status!=="sold"&&player.status!=="removed";const matchesPosition=(player:Player)=>position==="ALL"||(position==="RB/WR"?["RB","WR"].includes(player.position):position==="RB/WR/TE"?["RB","WR","TE"].includes(player.position):player.position===position);const displayPrice=(player:Player)=>player.status==="sold"?player.salePrice:player.liveExpectedPrice;const impactScore:Record<DecisionBand,number>={strong_pursue:5,lean_pursue:4,neutral:3,lean_pass:2,strong_pass:1};const sortValue=(player:Player)=>sort==="draftImpact"?(player.draftImpact?impactScore[player.draftImpact.band]:null):sort==="adp"?player.marketAdp:sort==="bye"?player.byeWeek:sort==="projectedPoints"?player.projectedPoints:sort==="xpar"?player.pointsAboveReplacement:sort==="predraft"?player.expectedPrice:displayPrice(player);const filtered=data.players.filter(player=>inPool(player)&&matchesPosition(player)&&player.name.toLowerCase().includes(query.toLowerCase()));const direction=ascending?1:-1;return filtered.sort((a,b)=>{if(sort==="name")return a.name.localeCompare(b.name)*direction;const av=sortValue(a),bv=sortValue(b);if(av==null&&bv==null)return 0;if(av==null)return 1;if(bv==null)return-1;return(av-bv)*direction;});},[ascending,data,poolView,position,query,sort]);
  function chooseSort(key:SortKey){if(sort===key)setAscending(value=>!value);else{setSort(key);setAscending(["name","adp","bye"].includes(key));}}
  function moveNominationOwner(index:number,direction:-1|1){setNominationOrderDraft(order=>{const next=[...order],target=index+direction;if(target<0||target>=next.length)return order;[next[index],next[target]]=[next[target]!,next[index]!];return next;});}
  async function askAssistantGm(options?:{trigger?:"official_nomination"|"sale"|"correction";question?:string}){const question=options?.question??gmQuestion.trim();if((!question&&!options?.trigger)||!focus||gmBusy)return;const conversationHistory=gmMessages.filter(message=>message.text.trim()).slice(-8).map(message=>({role:message.role,text:message.text.slice(0,600)}));if(question)setGmQuestion("");setGmBusy(true);setGmStatus("Streaming grounded explanation…");setGmMessages(messages=>[...messages,...(question?[{role:"user" as const,text:question}]:[]),{role:"assistant",text:"",status:"streaming" as const}]);try{const response=await fetch("/api/assistant-gm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({trigger:options?.trigger??"user_question",...(question?{question}:{}),focusPlayerId:focus.id,conversationHistory})});if(!response.ok||!response.body)throw new Error("unavailable");const reader=response.body.getReader(),decoder=new TextDecoder();let buffer="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==="delta")setGmMessages(messages=>messages.map((message,index)=>index===messages.length-1?{...message,text:message.text+event.text}:message));if(event.type==="complete"){setGmMessages(messages=>messages.map((message,index)=>index===messages.length-1?{...message,status:"complete"}:message));setGmStatus("Grounded · current draft state");}if(event.type==="error"){const stale=event.code==="STALE",withheld=event.code==="UNGROUNDED";setGmMessages(messages=>messages.map((message,index)=>index===messages.length-1?{...message,text:stale?"The draft advanced while I was answering. Ask again for the current state.":withheld?"That answer was withheld because it did not pass the grounding check. Please retry; the AI connection is still available.":"AI guidance is unavailable. The deterministic cards remain authoritative and fully usable offline.",status:stale?"stale":"error"}:message));setGmStatus(stale?"Stale response discarded":withheld?"Answer withheld · connection available":"Offline fallback active");}}}}catch{setGmMessages(messages=>messages.map((message,index)=>index===messages.length-1?{...message,text:"AI guidance is unavailable. Use the deterministic recommendation, price ladder, and Upcoming Targets; draft actions are unaffected.",status:"error"}:message));setGmStatus("Offline fallback active");}finally{setGmBusy(false);}}
  const selected=data?.players.find(player=>player.id===selectedId)??available[0]??null;
  const focus=data?.currentNomination??selected;
  const renegades=data?.renegades;
  useEffect(()=>{const change=data?.whatChanged;if(!change)return;if(lastGmSnapshot.current===null){lastGmSnapshot.current=change.snapshotId;return;}if(lastGmSnapshot.current===change.snapshotId)return;lastGmSnapshot.current=change.snapshotId;const trigger=change.triggerType==="nominate"?"official_nomination":change.triggerType==="sale"?"sale":change.triggerType==="voidSale"?"correction":null;if(trigger)void askAssistantGm({trigger});},[data?.whatChanged?.snapshotId]);
  const rosterTeam=data?.teams.find(team=>team.id===(rosterTeamId||data.renegades?.id))??data?.renegades??data?.teams[0]??null;
  const displayedRoster=rosterTeam?data?.teamRosters[rosterTeam.id]??[]:[];
  const ownerTeams=useMemo(()=>[...(data?.teams??[])].sort((a,b)=>a.owner.localeCompare(b.owner,undefined,{sensitivity:"base"})),[data]);
  const nflTeams=useMemo(()=>[...new Set(data?.players.map(player=>player.nflTeam).filter((team):team is string=>Boolean(team)))].sort(),[data]);
  if(!data)return <main className="loading"><img className="loading-logo" src="/branding/rodman-renegades-logo.png" alt="Rodman Renegades"/><p>{error||"Opening your draft room…"}</p><button onClick={()=>void load()}>Try again</button></main>;
  const championshipDecision=data.currentNomination?.championshipDecision??null;
  const focusTarget=data.upcomingTargets.find(target=>target.playerId===focus?.id)??null;
  const focusImpact=focus?.draftImpact??null;
  const suggestedCeiling=championshipDecision?.recommendedMax??focusTarget?.walkawayCeiling??null;
  const plannedCeiling=data.currentNomination?.decisionPlan?.committedCeiling??suggestedCeiling;
  const fallbackName=data.currentNomination?.alternatives[0]?.name??focusTarget?.replacementPlayer??null;
  const fallbackPrice=data.currentNomination?.alternatives[0]?.liveExpectedPrice??focusTarget?.replacementPrice??null;
  const comparableAlternatives=focus?data.players.filter(player=>player.id!==focus.id&&(player.status==="available"||player.status==="nominated")&&player.position===focus.position&&player.projectedPoints>=focus.projectedPoints-Math.max(6,focus.projectedPoints*.1)&&(player.liveExpectedPrice??player.expectedPrice??999)<=(renegades?.maxBid??0)).sort((a,b)=>b.projectedPoints-a.projectedPoints):[];
  const comparableNames=comparableAlternatives.map(player=>player.name).join(", ");
  const scarcityLabel=!focus?"—":focus.productionLabel==="Replacement"||comparableAlternatives.length>=6?"Highly replaceable":comparableAlternatives.length>=3?"Comparable options":comparableAlternatives.length>=1?"Thin alternatives":"Unique production";
  const outcomeSupport=championshipDecision?.support??focusImpact?.scenarioSupport??focusTarget?.scenarioSupport??null;
  const outcomeDelta=championshipDecision?.medianDelta??focusImpact?.expectedEquityDelta??focusTarget?.expectedEquityDelta??null;
  const rosterImpactLabel=focusImpact?.label??(championshipDecision?`${rosterImpactLabels[championshipDecision.band]}${championshipDecision.band==="neutral"?"":" Add"}`:"Not yet rated");
  const rosterImpactPrice=focusImpact?.price??championshipDecision?.price??focus?.liveExpectedPrice??null;
  const reconsiderationTriggered=Boolean(data.currentNomination&&renegades&&winner===renegades.id&&Number(price)>(plannedCeiling??Number.MAX_SAFE_INTEGER));
  const postPurchaseBudget=reconsiderationTriggered&&renegades?renegades.remainingBudget-Number(price):null;
  const postPurchaseMaxBid=reconsiderationTriggered&&renegades?Math.max(0,(postPurchaseBudget??0)-Math.max(0,renegades.openSlots-2)):null;
  const constrainedTargets=postPurchaseMaxBid==null?[]:data.upcomingTargets.filter(target=>target.targetPrice>postPurchaseMaxBid).slice(0,3);
  const impactAmount=Number(impactPrice),impactBudget=renegades&&impactAmount?renegades.remainingBudget-impactAmount:null;
  const impactMaxBid=renegades&&impactBudget!=null?Math.max(0,impactBudget-Math.max(0,renegades.openSlots-2)):null;
  const impactConstrainedTargets=impactMaxBid==null?[]:data.upcomingTargets.filter(target=>target.playerId!==focus?.id&&target.targetPrice>impactMaxBid).slice(0,5);
  return <main className="draft-app">
    <header className="app-bar"><div className="wordmark"><img src="/branding/rodman-renegades-logo.png" alt="Rodman Renegades"/> <span>Renegade Draft Room</span></div><div className="save-state"><i/>Local state saved</div><div className="save-state" title={data.sheetSync.lastError??undefined}><i className={data.sheetSync.failed?"sync-error":data.sheetSync.pending?"sync-pending":""}/>{!data.sheetSync.configured?"Draft board setup needed":data.sheetSync.failed?"Draft board retry needed":data.sheetSync.pending?"Draft board pending":"Draft board synced"}</div>{data.sheetSync.configured&&(data.sheetSync.failed>0||data.sheetSync.pending>0)&&<button className="quiet-button" disabled={busy} onClick={()=>void act({type:"retrySync"})}>Retry sync</button>}<div className="app-spacer"/><div className="max-bid-indicator" title="Your remaining budget minus $1 for every roster spot that would remain after this purchase"><span>Max bid</span><strong>{money(renegades?.maxBid)}</strong></div><div className="draft-meta">2026 JUGG · Version {data.draft.stateVersion}</div><button className="quiet-button targets-button" onClick={()=>setTargetsOpen(true)}>Upcoming targets ({data.upcomingTargets.length})</button><button className="quiet-button" onClick={()=>setLeaderboardOpen(true)}>League Outlook</button><button className="quiet-button" onClick={()=>{setNominationOrderDraft(data.nominationOrder.teams.map(team=>team.teamId));setNominationOrderOpen(true);}}>Nomination order</button><button className="quiet-button" onClick={()=>{setStrategyDraft(data.strategy);setSituationsText(data.strategy.situations.join("\n"));setStrategyOpen(true);}}>Renegades Strategy</button><button className="quiet-button" onClick={()=>setHistoryOpen(true)}>Draft history{data.recentSales.length?` (${data.recentSales.length})`:""}</button><button className="quiet-button" onClick={()=>{setResetConfirmation("");setPreservePreferences(true);setResetOpen(true);}}>Reset draft</button></header>
    {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}
    {data.draft.recoveryIssues.length>0&&<div className="error-banner" role="alert">Recovery audit found a state mismatch. Draft actions are paused.</div>}
    {data.draft.status==="setup"&&<section className="setup-overlay"><div><span className="kicker">2026 draft is prepared</span><h1>Ready when the room is.</h1><p>294 players, 10 owners, budgets, rosters, and model outputs are loaded locally. Starting the draft creates the first auditable event.</p><button className="primary-button" disabled={busy} onClick={()=>void act({type:"start"})}>Start the 2026 draft</button></div></section>}
    <div className="workspace">
      <section className="player-pane">
        <div className="player-tools"><label className="search-box"><span>Search</span><input id="player-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name  /"/></label><div className="position-tabs" aria-label="Filter by position">{positionFilters.map(item=><button key={item} className={position===item?"active":""} onClick={()=>setPosition(item)}>{item==="ALL"?"All":item}</button>)}</div><div className="pool-tabs" aria-label="Filter by draft status"><button className={poolView==="undrafted"?"active":""} onClick={()=>{setPoolView("undrafted");setSelectedId(null);}}>Undrafted</button><button className={poolView==="drafted"?"active":""} onClick={()=>{setPoolView("drafted");setSelectedId(null);}}>Drafted</button><button className={poolView==="all"?"active":""} onClick={()=>{setPoolView("all");setSelectedId(null);}}>All</button></div></div>
        <div className="player-columns"><span/><button onClick={()=>chooseSort("name")}>Player {sort==="name"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("bye")}>Bye {sort==="bye"?(ascending?"↑":"↓"):""}</button><button title="Projected fantasy points" onClick={()=>chooseSort("projectedPoints")}>xPTS {sort==="projectedPoints"?(ascending?"↑":"↓"):""}</button><button title="Production strength based on points above replacement" onClick={()=>chooseSort("xpar")}>Tier {sort==="xpar"?(ascending?"↑":"↓"):""}</button><button title="Frozen pre-draft projected price" onClick={()=>chooseSort("predraft")}>Draft $ {sort==="predraft"?(ascending?"↑":"↓"):""}</button><button onClick={()=>chooseSort("expected")}>Live $ {sort==="expected"?(ascending?"↑":"↓"):""}</button><button title="Buy-versus-pass roster impact at the live expected price" onClick={()=>chooseSort("draftImpact")}>Roster Impact {sort==="draftImpact"?(ascending?"↑":"↓"):""}</button></div>
        <div className="player-list">{available.map(player=>{const sold=player.status==="sold";const tierClass=`prod-label-${player.productionLabel.toLowerCase()}`;return <button key={player.id} className={`player-row ${selected?.id===player.id?"selected":""} ${poolView==="all"&&sold?"drafted-row":""}`} onClick={()=>setSelectedId(player.id)}><span className="position-tag">{player.position}</span><span className="player-identity"><strong>{player.name}{player.preference==="target"?" ★":player.preference==="avoid"?" ×":""}</strong><small>· {player.nflTeam??"FA"}{sold&&player.draftedBy?` → ${player.draftedBy}`:""}</small></span><span>{player.byeWeek??"—"}</span><span>{player.projectedPoints?.toFixed(1)??"—"}</span><span className={`production-tier-badge ${tierClass}`} title={`${player.pointsAboveReplacement==null?"—":player.pointsAboveReplacement.toFixed(1)} projected points above replacement`}>{player.productionLabel}</span><strong>{money(player.expectedPrice)}</strong><strong title={sold?`Sold to ${player.draftedBy??"—"}`:`Pre-draft ${money(player.expectedPrice)}`}>{money(sold?player.salePrice:player.liveExpectedPrice)}</strong><strong className={`draft-impact impact-${player.draftImpact?.band??"unavailable"}`} title={player.draftImpact?.summary??(sold?"Roster impact is evaluated before a player is sold.":"Roster impact is unavailable.")}>{player.draftImpact?.label.replace(" Add","")??"—"}</strong></button>;})}</div>
        <section className={`player-roster-drawer ${leftRosterOpen?"open":""}`}><button className="player-roster-toggle" aria-expanded={leftRosterOpen} onClick={()=>setLeftRosterOpen(open=>!open)}><span><strong>Team Roster</strong><small>{rosterTeam?.owner??"Select owner"} · {rosterTeam?.rosteredCount??0} / 14 filled</small></span><b aria-hidden="true">{leftRosterOpen?"⌄":"⌃"}</b></button>{leftRosterOpen&&<div className="player-roster-content"><div className="player-roster-controls"><select aria-label="View owner roster" value={rosterTeam?.id??""} onChange={event=>setRosterTeamId(event.target.value)}>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><span><b>{money(rosterTeam?.remainingBudget)}</b> left</span><span><b>{money(rosterTeam?.maxBid)}</b> max bid</span></div><div className="roster-table"><div className="roster-table-head"><span>Position</span><span>Player</span><span>Bye</span><span>Paid</span><span>Tier</span><span title="Points Above Replacement">PAR</span></div>{displayedRoster.map(slot=><div className={`roster-table-row ${slot.playerId?"roster-draggable":""} ${dropSlotId===slot.slotId?"roster-drop-target":""}`} key={slot.slotId} draggable={Boolean(slot.playerId)&&!busy} onDragStart={event=>{if(!slot.playerId)return;setDraggedPlayerId(slot.playerId);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",slot.playerId);}} onDragEnd={()=>{setDraggedPlayerId(null);setDropSlotId(null);}} onDragOver={event=>{if(!draggedPlayerId)return;event.preventDefault();event.dataTransfer.dropEffect="move";setDropSlotId(slot.slotId);}} onDragLeave={()=>setDropSlotId(current=>current===slot.slotId?null:current)} onDrop={event=>{event.preventDefault();const playerId=draggedPlayerId||event.dataTransfer.getData("text/plain");setDraggedPlayerId(null);setDropSlotId(null);if(playerId&&rosterTeam)void act({type:"reassignRosterSlot",teamId:rosterTeam.id,playerId,targetSlotId:slot.slotId});}} title={slot.playerId?"Drag this player to another eligible roster slot":"Drop an eligible player here"}><span>{slot.slotType.replaceAll("_","/")}</span><strong>{slot.player??""}</strong><span>{slot.byeWeek??"—"}</span><span>{money(slot.pricePaid)}</span>{slot.productionLabel?<span className={`production-tier-badge roster-tier-badge prod-label-${slot.productionLabel.toLowerCase()}`} title={`${slot.position}${slot.positionRank??"—"}`}>{slot.productionLabel}</span>:<span/>}<span className={slot.pointsAboveReplacement!=null&&slot.pointsAboveReplacement>0?"positive":""}>{slot.pointsAboveReplacement==null?"—":`${slot.pointsAboveReplacement>=0?"+":""}${slot.pointsAboveReplacement.toFixed(1)}`}</span></div>)}</div></div>}</section>
      </section>
      <section className="decision-pane">
        {focus?<div className="decision-layout">
          {data.whatChanged&&<section className="what-changed-banner"><div><span>What changed</span><strong>{data.whatChanged.headline}</strong></div><p>{data.whatChanged.reasons.join(" ")}</p></section>}
          <section className="dashboard-panel player-details-panel">
            <div className="panel-title"><h2>Player Details</h2><span>{data.currentNomination?`Now nominated${data.currentNomination.nominator?` · ${data.currentNomination.nominator}`:""}`:"Player preview"}</span></div>
            <div className="player-details-header"><div className="player-bio"><h1>{focus.name}</h1><p>{focus.position} · {focus.nflTeam??"Free agent"} · Bye {focus.byeWeek??"—"} · ADP {focus.marketAdp??"—"}</p></div><div className="details-actions"><button className={`quiet-button ${focus.preference==="target"?"preference-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="target"?"neutral":"target",premium:data.strategy.targetPremium,note:""})}>★ Target</button><button className={`quiet-button ${focus.preference==="avoid"?"avoid-active":""}`} disabled={busy} onClick={()=>void act({type:"playerPreference",playerId:focus.id,preference:focus.preference==="avoid"?"neutral":"avoid",premium:0,note:""})}>× Avoid</button>{data.currentNomination?<><button className="quiet-button" disabled={busy} onClick={()=>void act({type:"cancelNomination"})}>Cancel nomination</button><button className="primary-button" disabled={busy} onClick={()=>{setWinner(renegades?.id??data.teams[0]?.id??"");setPrice(String(focus.liveExpectedPrice??1));setSaleOpen(true);}}>Record final sale</button></>:<><select aria-label="Nominated by" value={nominator} onChange={event=>setNominator(event.target.value)}><option value="">Nominated by…</option>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner}</option>)}</select><button className="primary-button" disabled={busy} onClick={()=>void act({type:"nominate",playerId:focus.id,...(nominator?{nominatedByTeamId:nominator}:{})})}>Nominate player</button></>}</div></div>
            <div className="primary-decision-grid">
              <button type="button" className="primary-decision-card decision-summary-card market-cost-card" onClick={()=>setPriceDetailsOpen(true)}><span>1 · Live Price</span><strong>{money(focus.liveExpectedPrice)}</strong><p>Likely range {money(focus.livePriceLow)}–{money(focus.livePriceHigh)}</p><p className="tile-secondary-line">Pre-draft price {money(focus.expectedPrice)}</p><div className="tile-open-indicator" aria-hidden="true">↗</div></button>
              <button type="button" className="primary-decision-card decision-summary-card production-advantage-card" onClick={()=>setProductionDetailsOpen(true)}><span>2 · xPAR</span><strong>{focus.pointsAboveReplacement==null?"—":`${focus.pointsAboveReplacement>=0?"+":""}${focus.pointsAboveReplacement.toFixed(1)} · ${focus.productionLabel}`}</strong><p>Replacement baseline {focus.replacementPoints==null?"—":`${focus.replacementPoints.toFixed(1)} pts`}</p><p className="tile-secondary-line">{focus.projectedPoints.toFixed(1)} projected pts · {focus.position}{focus.positionRank??"—"}</p><div className="tile-open-indicator" aria-hidden="true">↗</div></button>
              <button type="button" className="primary-decision-card decision-summary-card scarcity-card" title={comparableNames?`Comparable options: ${comparableNames}`:"No other comparable players remain"} onClick={()=>setScarcityOpen(true)}><span>3 · Scarcity</span><strong>{scarcityLabel}</strong><p>{comparableAlternatives.length} comparable option{comparableAlternatives.length===1?"":"s"} remain</p><p className="tile-secondary-line">{fallbackName?`Closest: ${fallbackName} · ${money(fallbackPrice)}`:"No close fallback available"}</p><div className="tile-open-indicator" aria-hidden="true">↗</div></button>
              <button type="button" className="primary-decision-card decision-summary-card outcome-card roster-impact-card" onClick={()=>{setImpactPrice(String(Math.min(renegades?.maxBid??999,(plannedCeiling??focus.liveExpectedPrice??1)+1)));setImpactOpen(true);}}><span>4 · Roster Impact</span><strong>{rosterImpactLabel}</strong><p>{outcomeSupport!=null?`${Math.round(outcomeSupport*9)} of 9 paths improve at ${money(rosterImpactPrice)}`:"Nominate to test all 9 roster paths"}</p><p className="tile-secondary-line">Walk-away {plannedCeiling==null?"set after nomination":money(plannedCeiling)}</p><div className="tile-open-indicator" aria-hidden="true">↗</div></button>
            </div>
            <section className="price-ladder-card" aria-label={championshipDecision?`Price ladder, market modeled through ${money(championshipDecision.marketHigh)}`:"Price ladder requires an official nomination"}><div className="compact-impact-ladder">{decisionBands.map(band=>{const ranges=championshipDecision?.tiers.filter(tier=>tier.band===band)??[];return <div key={band} className={`compact-impact-row impact-row-${band} ${ranges.length?"":"impact-row-empty"}`}><span>{rosterImpactLabels[band]}</span><strong>{ranges.length?ranges.map(tier=>tier.from===tier.to?money(tier.from):`${money(tier.from)}–${money(tier.to)}`).join(", "):"—"}</strong></div>;})}</div></section>
            <PlayerStatTable player={focus}/>
          </section>
          <div className="assistant-roadmap-row"><section className="dashboard-panel assistant-gm-panel"><div className="panel-title"><h2>Assistant GM</h2><span>{gmStatus}</span></div><div className="assistant-chat-column"><div ref={assistantStreamRef} className="assistant-stream" aria-live="polite"><div className="gm-message assistant">{data.currentNomination?`${focus.name} projects around ${money(focus.liveExpectedPrice)}. ${championshipDecision?`${Math.round(championshipDecision.support*9)} of 9 tested roster paths favor buying at the expected price.`:"The decision ladder is being prepared."}`:data.recentSales[0]?`After the last sale of ${data.recentSales[0].player} for ${money(data.recentSales[0].price)}, select or nominate a player for an updated decision read.`:`Select a player to begin the draft conversation.`}</div>{gmMessages.map((message,index)=><div key={index} className={`gm-message ${message.role} ${message.status??""}`}>{message.text}{message.status==="streaming"&&<span className="stream-cursor"> ▌</span>}</div>)}</div><form className="gm-input" onSubmit={event=>{event.preventDefault();void askAssistantGm();}}><input value={gmQuestion} maxLength={1000} onChange={event=>setGmQuestion(event.target.value)} placeholder="Ask about this player, roster, budget, alternatives, owners, or nominations…"/><button type="submit" disabled={!gmQuestion.trim()||gmBusy}>{gmBusy?"Answering…":"Ask"}</button></form></div></section><section className="dashboard-panel draft-roadmap-panel" aria-label="Draft outlook roadmap"><div className="panel-title"><h2>Draft Outlook</h2><span>Roadmap</span></div><div className="draft-roadmap-list">{data.upcomingTargets.map(target=><article key={target.playerId}><b>{target.rank}</b><span><strong>{target.name}</strong><small>{target.role}</small></span><span><small>Target</small><strong>{money(target.targetPrice)}</strong><small>Walk {money(target.walkawayCeiling)}</small></span></article>)}{!data.upcomingTargets.length&&<p className="empty-copy">No legal target path is currently available.</p>}</div></section></div>
        </div>:<div className="empty-decision"><img className="empty-logo" src="/branding/rodman-renegades-logo.png" alt=""/><h1>Choose a player</h1><p>Search or filter the available pool to preview a recommendation.</p></div>}
      </section>
    </div>
    {saleOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSaleOpen(false);}}><section className="sale-modal" role="dialog" aria-modal="true" aria-labelledby="sale-title"><span className="kicker">Final sale</span><h2 id="sale-title">Record {focus.name}</h2><label>Winning owner<select value={winner} onChange={event=>setWinner(event.target.value)}>{ownerTeams.map(team=><option key={team.id} value={team.id}>{team.owner} · {money(team.remainingBudget)} left</option>)}</select></label><label>Sale price<input type="number" min="1" inputMode="numeric" value={price} onChange={event=>setPrice(event.target.value)}/></label><div className="sale-check">{(()=>{const team=data.teams.find(item=>item.id===winner);return team?<><span>Walk-away price</span><strong>{winner===renegades?.id?money(plannedCeiling):"—"}</strong><span>Maximum legal bid</span><strong>{money(team.maxBid)}</strong><span>Open slots after sale</span><strong>{team.openSlots-1}</strong></>:null;})()}</div>{reconsiderationTriggered&&<div className="override-warning"><strong>This is {money(Number(price)-(plannedCeiling??0))} above the walk-away price.</strong><p>This is allowed. After the purchase you would have {money(postPurchaseBudget)} left and a later maximum bid of about {money(postPurchaseMaxBid)}.{constrainedTargets.length?` Targets put out of immediate reach: ${constrainedTargets.map(target=>target.name).join(", ")}.`:" The current listed targets remain within that later maximum."}</p><label>Optional note about what changed<textarea value={ceilingOverrideReason} onChange={event=>setCeilingOverrideReason(event.target.value)} placeholder="Room conditions, scarcity, roster fit, or another reason for revising the plan"/></label></div>}<div className="modal-actions"><button className="quiet-button" onClick={()=>setSaleOpen(false)}>Cancel</button><button className="primary-button" disabled={busy||!winner||!Number(price)} onClick={()=>void act({type:"sale",winnerTeamId:winner,price:Number(price),...(ceilingOverrideReason.trim()?{ceilingOverrideReason:ceilingOverrideReason.trim()}:{})})}>Confirm sale</button></div></section></div>}
    {priceDetailsOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setPriceDetailsOpen(false);}}><section className="sale-modal decision-detail-modal" role="dialog" aria-modal="true" aria-labelledby="price-details-title"><span className="kicker">Price context</span><h2 id="price-details-title">{focus.name}&apos;s price outlook</h2><div className="decision-detail-list"><span>Live expected price</span><strong>{money(focus.liveExpectedPrice)}</strong><span>Likely range</span><strong>{money(focus.livePriceLow)}–{money(focus.livePriceHigh)}</strong><span>Pre-draft price</span><strong>{money(focus.expectedPrice)}</strong><span>Change from pre-draft</span><strong>{signedMoney((focus.liveExpectedPrice??0)-(focus.expectedPrice??0))}</strong></div><div className="modal-actions"><button className="quiet-button" onClick={()=>setPriceDetailsOpen(false)}>Close</button></div></section></div>}
    {productionDetailsOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setProductionDetailsOpen(false);}}><section className="sale-modal decision-detail-modal" role="dialog" aria-modal="true" aria-labelledby="production-details-title"><span className="kicker">Production context</span><h2 id="production-details-title">{focus.name}&apos;s projected advantage</h2><div className="decision-detail-list"><span>Production class</span><strong>{focus.productionLabel}</strong><span>Projected points</span><strong>{focus.projectedPoints.toFixed(1)}</strong><span>Replacement baseline</span><strong>{focus.replacementPoints==null?"—":focus.replacementPoints.toFixed(1)}</strong><span>Points above replacement</span><strong>{focus.pointsAboveReplacement==null?"—":`${focus.pointsAboveReplacement>=0?"+":""}${focus.pointsAboveReplacement.toFixed(1)}`}</strong></div><div className="modal-actions"><button className="quiet-button" onClick={()=>setProductionDetailsOpen(false)}>Close</button></div></section></div>}
    {impactOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setImpactOpen(false);}}><section className="sale-modal impact-modal" role="dialog" aria-modal="true" aria-labelledby="impact-title"><span className="kicker">Roster impact details</span><h2 id="impact-title">{focus.name}: {rosterImpactLabel}</h2><p className="impact-intro">{outcomeSupport!=null?`At ${money(rosterImpactPrice)}, buying creates a better projected final roster in ${Math.round(outcomeSupport*9)} of 9 tested draft paths.`:"Officially nominate this player to test all nine roster-completion paths and establish a walk-away price."}</p>{plannedCeiling!=null&&<><div className="decision-detail-list"><span>Walk-away price</span><strong>{money(plannedCeiling)}</strong><span>Scenario support</span><strong>{Math.round((outcomeSupport??0)*9)} of 9</strong><span>Projected outcome shift</span><strong>{signedPercent(outcomeDelta)}</strong></div><label>Possible winning price<input type="number" min="1" max={renegades?.maxBid} value={impactPrice} onChange={event=>setImpactPrice(event.target.value)}/></label>{impactAmount>0&&<div className={`impact-result ${impactAmount>plannedCeiling?"impact-over":"impact-within"}`}><strong>{impactAmount>plannedCeiling?`${money(impactAmount-plannedCeiling)} above the walk-away price`:`Within the recommended plan by ${money(plannedCeiling-impactAmount)}`}</strong><div><span>Budget afterward</span><b>{money(impactBudget)}</b><span>Later maximum bid</span><b>{money(impactMaxBid)}</b><span>Open slots afterward</span><b>{Math.max(0,(renegades?.openSlots??1)-1)}</b></div>{impactAmount>plannedCeiling&&<><p>{impactConstrainedTargets.length?`Targets moved beyond the later max bid: ${impactConstrainedTargets.map(target=>target.name).join(", ")}.`:"The currently listed upcoming targets remain within the later maximum bid."}</p><p>{fallbackName?`The clearest current fallback is ${fallbackName} around ${money(fallbackPrice)}.`:"No close fallback is currently identified."}</p></>}</div>}</>}<div className="modal-actions"><button className="quiet-button" onClick={()=>setImpactOpen(false)}>Close</button>{plannedCeiling!=null&&data.currentNomination&&<button className="primary-button" onClick={()=>{setImpactOpen(false);setCeilingDraft(String(impactAmount||plannedCeiling));setCeilingReason("");setCeilingOpen(true);}}>Use as new walk-away</button>}</div></section></div>}
    {scarcityOpen&&focus&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setScarcityOpen(false);}}><section className="sale-modal scarcity-modal" role="dialog" aria-modal="true" aria-labelledby="scarcity-title"><span className="kicker">Comparable production</span><h2 id="scarcity-title">Alternatives to {focus.name}</h2><p className="impact-intro">Available {focus.position}s with comparable projected production, ordered by projected points.</p><div className="scarcity-list">{comparableAlternatives.map(player=><button key={player.id} onClick={()=>{setSelectedId(player.id);setScarcityOpen(false);}}><span><strong>{player.name}</strong><small>{player.nflTeam??"FA"} · {player.projectedPoints.toFixed(1)} projected points</small></span><b>{money(player.liveExpectedPrice)}</b></button>)}</div>{!comparableAlternatives.length&&<p className="empty-copy">No other comparable players remain available and affordable.</p>}<div className="modal-actions"><button className="quiet-button" onClick={()=>setScarcityOpen(false)}>Close</button></div></section></div>}
    {ceilingOpen&&data.currentNomination&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setCeilingOpen(false);}}><section className="sale-modal ceiling-modal" role="dialog" aria-modal="true" aria-labelledby="ceiling-title"><span className="kicker">Decision checkpoint</span><h2 id="ceiling-title">Adjust {data.currentNomination.name}&apos;s walk-away price?</h2><p>The current model supports the plan through {money(data.currentNomination.decisionPlan.recommendedCeiling)}. This is the recommended stopping point—not a legal bidding limit.</p><label>Walk-away price<input type="number" min="1" max={renegades?.maxBid} value={ceilingDraft} onChange={event=>setCeilingDraft(event.target.value)}/></label><label>Optional reason for the adjustment<textarea value={ceilingReason} onChange={event=>setCeilingReason(event.target.value)} placeholder="What changed in the room or in your plan?"/></label><div className="modal-actions"><button className="quiet-button" onClick={()=>setCeilingOpen(false)}>Keep current walk-away</button><button className="primary-button" disabled={busy||!Number(ceilingDraft)} onClick={()=>void act({type:"commitCeiling",nominationId:data.currentNomination!.nominationId,ceiling:Number(ceilingDraft),...(ceilingReason.trim()?{reason:ceilingReason.trim()}:{})})}>Save walk-away price</button></div></section></div>}
    {targetsOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setTargetsOpen(false);}}><aside className="history-drawer targets-drawer"><div className="drawer-head"><div><span className="kicker">Adaptive draft roadmap</span><h2>Upcoming Targets</h2></div><button onClick={()=>setTargetsOpen(false)}>Close</button></div><p className="strategy-intro">Ranked from the current roster, budgets, available players, production tiers, prices, replacement paths, championship scenarios, and your saved strategy. Recalculates after every action.</p><div className="discipline-summary"><span>Purchases above walk-away</span><strong>{data.discipline.count}</strong><span>Dollars above initial plans</span><strong>{money(data.discipline.dollarsAbovePlan)}</strong></div><div className="targets-list">{data.upcomingTargets.map(target=><article key={target.playerId} className="target-roadmap-card"><div className="target-rank">{target.rank}</div><div className="target-main"><div><strong>{target.name}</strong><span>{target.position} · Production Tier {target.productionTier??"—"} · {target.tierRemaining} left</span></div><p>{target.role}</p><small>{target.why}</small><div className="conditional-plan">{target.conditionalPlan}</div></div><div className="target-prices"><span>Target</span><strong>{money(target.targetPrice)}</strong><span>Walk away</span><strong>{money(target.walkawayCeiling)}</strong><small>{target.replacementPlayer?`Fallback: ${target.replacementPlayer} ${money(target.replacementPrice)}`:"Preserve flexibility"}</small></div></article>)}</div>{!data.upcomingTargets.length&&<p className="empty-copy">No legal target path is currently available.</p>}</aside></div>}
    {resetOpen&&<div className="modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setResetOpen(false);}}><section className="sale-modal reset-modal" role="dialog" aria-modal="true" aria-labelledby="reset-title"><span className="kicker">Recoverable reset</span><h2 id="reset-title">Reset the 2026 draft?</h2><p>This creates a timestamped backup, restores every budget and roster slot, makes all players available, clears draft history, and clears the shared Google draft board.</p><label className="reset-choice"><input type="checkbox" checked={preservePreferences} onChange={event=>setPreservePreferences(event.target.checked)}/><span>Keep Renegades strategy and player target/avoid preferences</span></label><label>Type <strong>RESET</strong> to confirm<input autoFocus value={resetConfirmation} onChange={event=>setResetConfirmation(event.target.value)} placeholder="RESET"/></label><div className="modal-actions"><button className="quiet-button" onClick={()=>setResetOpen(false)}>Cancel</button><button className="danger-button" disabled={busy||resetConfirmation!=="RESET"} onClick={()=>void act({type:"resetDraft",confirmation:resetConfirmation,preservePreferences}).then(()=>setResetOpen(false))}>Reset draft</button></div></section></div>}
    {historyOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setHistoryOpen(false);}}><aside className="history-drawer"><div className="drawer-head"><div><span className="kicker">Audit history · {data.recentSales.length} picks</span><h2>Completed sales</h2></div><button onClick={()=>setHistoryOpen(false)}>Close</button></div>{data.recentSales.length?<div className="audit-history-list">{data.recentSales.map(sale=><div className="audit-history-row" key={sale.id}><strong>#{sale.pick}</strong><span><b>{sale.player}</b><small>{sale.team}</small></span><b>{money(sale.price)}</b><button disabled={busy} onClick={()=>{if(window.confirm(`Undo the pick of ${sale.player} by ${sale.team} for ${money(sale.price)}? The original action will remain in history.`))void act({type:"voidSale",saleId:sale.id});}}>Undo pick</button></div>)}</div>:<p className="empty-copy">No sales have been recorded.</p>}<p className="drawer-note">Corrections restore the player, roster slot, and budget while preserving the original action in the immutable audit trail.</p></aside></div>}
    {leaderboardOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setLeaderboardOpen(false);}}><aside className="history-drawer leaderboard-drawer"><div className="drawer-head"><div><span className="kicker">Live · shadow model</span><h2>League Outlook</h2></div><button onClick={()=>setLeaderboardOpen(false)}>Close</button></div><p className="strategy-intro">Recalculates after every sale from each partial roster, remaining budget, and nine neutral completion scenarios. Close ranges should be treated as ties.</p><div className="leaderboard-head"><span>Rank</span><span>Player</span><span>Equity range</span></div>{data.leaderboard.map(row=><div className={`leaderboard-row ${row.name==="Rodman Renegades"?"renegades-row":""}`} key={row.teamId}><strong>#{row.rank}</strong><span><b>{row.owner}</b></span><span><b>{percent(row.championshipEquity)}</b><small>{percent(row.equityLow)}–{percent(row.equityHigh)}</small></span></div>)}</aside></div>}
    {nominationOrderOpen&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setNominationOrderOpen(false);}}><aside className="history-drawer nomination-order-drawer"><div className="drawer-head"><div><span className="kicker">Rotation and waiver tiebreaker</span><h2>Nomination order</h2></div><button onClick={()=>setNominationOrderOpen(false)}>Close</button></div><p className="strategy-intro">The next active owner is selected automatically. Completed rosters are skipped, and finish order becomes waiver tiebreaker priority.</p><div className="nomination-order-list">{nominationOrderDraft.map((teamId,index)=>{const team=data.nominationOrder.teams.find(item=>item.teamId===teamId)!;return <div className={`nomination-order-row ${data.nominationOrder.nextTeamId===teamId?"next-nominator":""} ${team.completedAt?"completed-owner":""}`} key={teamId}><strong>{index+1}</strong><span><b>{team.owner}</b><small>{team.completedAt?`Draft finished · waiver #${team.waiverPriority}`:data.nominationOrder.nextTeamId===teamId?"Next to nominate":`${team.openSlots} roster spots open`}</small></span><div><button aria-label={`Move ${team.owner} up`} disabled={index===0} onClick={()=>moveNominationOwner(index,-1)}>↑</button><button aria-label={`Move ${team.owner} down`} disabled={index===nominationOrderDraft.length-1} onClick={()=>moveNominationOwner(index,1)}>↓</button></div></div>;})}</div><div className="modal-actions"><button className="quiet-button" onClick={()=>setNominationOrderOpen(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={()=>void act({type:"updateNominationOrder",teamIds:nominationOrderDraft}).then(()=>setNominationOrderOpen(false))}>Save order</button></div></aside></div>}
    {strategyOpen&&strategyDraft&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setStrategyOpen(false);}}><aside className="history-drawer strategy-drawer">
      <div className="drawer-head"><div><span className="kicker">Weighted preferences</span><h2>Renegades Strategy</h2></div><button onClick={()=>setStrategyOpen(false)}>Close</button></div>
      <p className="strategy-intro">Preferences make limited adjustments to your value and recommendation. They never block a player or rewrite the JUGG market prediction.</p>
      <div className="preference-lists"><section><span className="kicker">Preferred players</span>{data.players.filter(player=>player.preference==="target").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="target")&&<small>Use ★ Target from the player view.</small>}</section><section><span className="kicker">Players to avoid</span>{data.players.filter(player=>player.preference==="avoid").map(player=><div key={player.id}><span>{player.name}</span><button onClick={()=>void act({type:"playerPreference",playerId:player.id,preference:"neutral",premium:0,note:""})}>Remove</button></div>)}{!data.players.some(player=>player.preference==="avoid")&&<small>Use × Avoid from the player view.</small>}</section></div>
      <label>Risk tolerance<select value={strategyDraft.riskTolerance} onChange={event=>setStrategyDraft({...strategyDraft,riskTolerance:event.target.value as Strategy["riskTolerance"]})}><option value="conservative">Conservative</option><option value="balanced">Balanced</option><option value="aggressive">Aggressive</option></select></label>
      <label>Bye-week approach<select value={strategyDraft.byeWeekMode} onChange={event=>setStrategyDraft({...strategyDraft,byeWeekMode:event.target.value as Strategy["byeWeekMode"]})}><option value="ignore">Ignore overlap</option><option value="soft">Discourage overlap</option><option value="strict">Strongly discourage overlap</option></select></label>
      <div className="strategy-pair"><label>Players on same bye<input type="number" min="1" max="6" value={strategyDraft.maxSameBye} onChange={event=>setStrategyDraft({...strategyDraft,maxSameBye:Number(event.target.value)})}/></label><label>Default target premium<input type="number" min="0" max="20" value={strategyDraft.targetPremium} onChange={event=>setStrategyDraft({...strategyDraft,targetPremium:Number(event.target.value)})}/></label></div>
      <div className="team-preference-heading"><div><span className="kicker">NFL-team preferences</span><p>Optionally apply a small preference to all players or one position.</p></div><button className="quiet-button" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:[...strategyDraft.teamPreferences,{team:nflTeams[0]??"ARI",position:"ALL",preference:"prefer",adjustment:2,note:""}]})}>Add team preference</button></div>
      <div className="team-preferences">{strategyDraft.teamPreferences.map((rule,index)=><div className="team-rule" key={`${index}:${rule.team}:${rule.position}`}><select aria-label="NFL team" value={rule.team} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,team:event.target.value}:item)})}>{nflTeams.map(team=><option key={team}>{team}</option>)}</select><select aria-label="Position" value={rule.position} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,position:event.target.value as TeamPreference["position"]}:item)})}><option value="ALL">All</option>{positions.slice(1).map(item=><option key={item}>{item}</option>)}</select><select aria-label="Preference" value={rule.preference} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,preference:event.target.value as TeamPreference["preference"]}:item)})}><option value="prefer">Prefer</option><option value="avoid">Avoid</option></select><input aria-label="Dollar adjustment" type="number" min="1" max="5" value={rule.adjustment} onChange={event=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.map((item,itemIndex)=>itemIndex===index?{...item,adjustment:Number(event.target.value)}:item)})}/><button aria-label="Remove team preference" onClick={()=>setStrategyDraft({...strategyDraft,teamPreferences:strategyDraft.teamPreferences.filter((_,itemIndex)=>itemIndex!==index)})}>×</button></div>)}</div>
      <label>Situations you like<textarea value={situationsText} onChange={event=>setSituationsText(event.target.value)} placeholder={"One per line, for example:\nYoung WR with established target share\nMobile quarterback"}/></label>
      <label>Strategy notes<textarea value={strategyDraft.notes} onChange={event=>setStrategyDraft({...strategyDraft,notes:event.target.value})} placeholder="Anything else the recommendation system should keep in mind."/></label>
      <div className="modal-actions"><button className="quiet-button" onClick={()=>setStrategyOpen(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={()=>void act({type:"updateStrategy",strategy:{...strategyDraft,situations:situationsText.split("\n").map(value=>value.trim()).filter(Boolean)}}).then(()=>setStrategyOpen(false))}>Save strategy</button></div>
    </aside></div>}
  </main>;
}
