import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import { DraftService, DomainError, type Position } from "../src/domain/DraftService.js";
import { initializeFromArtifacts } from "../src/domain/importDraftArtifacts.js";
import { draftRoadmap, liveLeaderboard, nominationDecision, type DecisionPlayer, type DecisionTeam } from "../src/domain/liveDecisionEngine.js";

type Scenario={id:string;family:"historical_price"|"2026_market";seed:number;season?:number;order:"expected"|"reverse"|"random"|"rb_early"|"wr_early";priceFactor:number;noise:number;winnerPolicy:"balanced"|"top_heavy"|"depth"|"late_budget"|"early_budget"};
type Rng=()=>number;
type BoardRow=Record<string,any>;
type HistoricalSale={internal_player_id:string;owner:string;salary:number;season:number;source_row:number};
type ActionSnapshot={sale:number;stateVersion:number;playerId:string;player:string;position:Position;nominator:string;winner:string;price:number;expectedPrice:number;range:[number,number];productionLabel:string;scarcityLabel:string;alternatives:string[];draftImpact:string|null;walkaway:number|null;bands:any[];fallbacks:string[];upcomingTargets:string[];renegades:{budget:number;openSlots:number;maxBid:number};leagueBudgets:number[];likelyCompetition:string[];leaderboardLeader:string;renegadesRank:number;latencyMs:number;warnings:string[]};

const ROOT=process.cwd(), DRAFT_ID="simulation-draft";
const ACTIVE_DB=resolve(ROOT,".local/renegade-draft-room.sqlite");
const fixedTime=(index:number)=>new Date(Date.UTC(2026,7,25,20,0,index)).toISOString();
const hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function rng(seed:number):Rng{let state=seed>>>0;return()=>{state=(state*1664525+1013904223)>>>0;return state/4294967296;};}
function shuffle<T>(rows:T[],random:Rng){const out=[...rows];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j]!,out[i]!];}return out;}
function label(row:BoardRow,maximum:number){const x=Number(row.points_above_replacement??0);if(x<=0||maximum<=0)return"Replacement";const share=x/maximum;return share>=.75?"Elite":share>=.5?"Premium":share>=.25?"Starter":"Depth";}
function legalPositionNeeds(service:DraftService,teamId:string):Set<Position>{
  const rows=service.db.prepare("SELECT eligible_positions_json FROM roster_slots WHERE team_id=? AND player_id IS NULL").all(teamId) as {eligible_positions_json:string}[];
  return new Set(rows.flatMap(row=>JSON.parse(row.eligible_positions_json) as Position[]));
}
function legalWinners(service:DraftService,player:BoardRow,teams:any[]){
  const viable=(team:any)=>{const counts=Object.fromEntries(["QB","RB","WR","TE","K","DEF"].map(position=>[position,(service.db.prepare("SELECT COUNT(*) count FROM roster_slots rs JOIN players p ON p.id=rs.player_id WHERE rs.team_id=? AND p.position=?").get(team.id,position) as any).count])) as Record<string,number>;counts[player.position]=(counts[player.position]??0)+1;const missingFixed=Math.max(0,1-counts.QB)+Math.max(0,2-counts.WR)+Math.max(0,1-counts.RB)+Math.max(0,1-counts.TE)+Math.max(0,1-counts.K)+Math.max(0,1-counts.DEF);const missingWrRb=Math.max(0,4-(counts.WR+counts.RB));const missingSkill=Math.max(0,6-(counts.WR+counts.RB+counts.TE));return Math.max(missingFixed,missingWrRb+Math.max(0,1-counts.QB)+Math.max(0,1-counts.K)+Math.max(0,1-counts.DEF),missingSkill+Math.max(0,1-counts.QB)+Math.max(0,1-counts.K)+Math.max(0,1-counts.DEF))<=team.openSlots-1;};
  return teams.filter(team=>team.openSlots>0&&legalPositionNeeds(service,team.id).has(player.position)&&team.budget-(team.openSlots-1)>=1&&viable(team));
}
function state(service:DraftService,board:Map<string,BoardRow>){
  const teamRows=service.db.prepare("SELECT t.id,t.display_name name,o.display_name owner,s.remaining_budget budget,s.open_slot_count openSlots FROM teams t JOIN owners o ON o.id=t.owner_id JOIN team_draft_state s ON s.team_id=t.id WHERE t.draft_id=? ORDER BY t.id").all(DRAFT_ID) as any[];
  const rosterRows=service.db.prepare("SELECT rs.team_id teamId,rs.player_id playerId FROM roster_slots rs JOIN teams t ON t.id=rs.team_id WHERE t.draft_id=? AND rs.player_id IS NOT NULL").all(DRAFT_ID) as any[];
  const toPlayer=(id:string):DecisionPlayer=>{const row=board.get(id)!;return{id,name:row.player_name,position:row.position,projectedPoints:Number(row.projected_points??0),expectedPrice:Number(row.expected_jugg_price??1),priceLow:Number(row.price_range_low??1),priceHigh:Number(row.price_range_high??1),productionTier:row.production_tier,auctionTier:row.auction_tier,pointsAboveReplacement:row.points_above_replacement,replacementPoints:row.replacement_points,strategyValue:row.production_value};};
  const teams:DecisionTeam[]=teamRows.map(team=>({id:team.id,name:team.name,owner:team.owner,remainingBudget:team.budget,openSlots:team.openSlots,roster:rosterRows.filter(row=>row.teamId===team.id).map(row=>toPlayer(row.playerId))}));
  const availableIds=(service.db.prepare("SELECT player_id id FROM draft_player_pool WHERE draft_id=? AND status IN ('available','nominated')").all(DRAFT_ID) as {id:string}[]).map(row=>row.id);
  return {teams,available:availableIds.map(toPlayer),renegades:teams.find(team=>team.name==="Rodman Renegades")!};
}
function chooseWinner(service:DraftService,player:BoardRow,teams:any[],scenario:Scenario,index:number,random:Rng){
  const legal=legalWinners(service,player,teams);
  if(!legal.length)throw new Error(`no legal winner for ${player.player_name}`);
  const scored=legal.map(team=>{const count=(service.db.prepare("SELECT COUNT(*) count FROM roster_slots rs JOIN players p ON p.id=rs.player_id WHERE rs.team_id=? AND p.position=?").get(team.id,player.position) as any).count;let score=-count*5+random();if(scenario.winnerPolicy==="top_heavy")score+=index<35?8/(team.openSlots+1):0;if(scenario.winnerPolicy==="depth")score+=team.openSlots/8;if(scenario.winnerPolicy==="late_budget")score+=team.budget/200;if(scenario.winnerPolicy==="early_budget")score+=index<70?team.budget/60:0;return{team,score};}).sort((a,b)=>b.score-a.score||a.team.id.localeCompare(b.team.id));
  return scored[0]!.team;
}
function salePrice(row:BoardRow,winner:any,scenario:Scenario,index:number,random:Rng){let factor=scenario.priceFactor;if(scenario.id.includes("rb-inflation")&&row.position==="RB"&&index<55)factor+=.25;if(scenario.id.includes("wr-inflation")&&row.position==="WR"&&index<55)factor+=.25;if(scenario.id.includes("elite-pressure")&&Number(row.expected_jugg_price)>=50)factor+=.2;const sampled=Number(row.expected_jugg_price??1)*factor+(random()-.5)*2*scenario.noise;return Math.max(1,Math.min(Math.round(sampled),winner.budget-(winner.openSlots-1)));}
function orderedPlayers(rows:BoardRow[],scenario:Scenario,random:Rng){let ordered=[...rows];if(scenario.order==="expected")ordered.sort((a,b)=>Number(b.expected_jugg_price)-Number(a.expected_jugg_price));if(scenario.order==="reverse")ordered.sort((a,b)=>Number(a.expected_jugg_price)-Number(b.expected_jugg_price));if(scenario.order==="random")ordered=shuffle(ordered,random);if(scenario.order==="rb_early")ordered.sort((a,b)=>(a.position==="RB"?-1:0)-(b.position==="RB"?-1:0)||Number(b.expected_jugg_price)-Number(a.expected_jugg_price));if(scenario.order==="wr_early")ordered.sort((a,b)=>(a.position==="WR"?-1:0)-(b.position==="WR"?-1:0)||Number(b.expected_jugg_price)-Number(a.expected_jugg_price));return ordered;}
function completeOrder(rows:BoardRow[],scenario:Scenario,random:Rng,historical:HistoricalSale[]){
  if(scenario.family!=="historical_price")return orderedPlayers(rows,scenario,random);
  const board=new Map(rows.map(row=>[row.internal_player_id,row]));
  let compatible=historical.filter(sale=>sale.season===scenario.season&&board.has(sale.internal_player_id));
  compatible=scenario.order==="random"?shuffle(compatible,random):[...compatible].sort((a,b)=>b.salary-a.salary||a.source_row-b.source_row);
  const used=new Set(compatible.map(sale=>sale.internal_player_id));
  return [...compatible.map(sale=>board.get(sale.internal_player_id)!),...orderedPlayers(rows.filter(row=>!used.has(row.internal_player_id)),scenario,random)];
}
function applyOutbox(service:DraftService,mode:"noop"|"recording"|"pending"|"failing",recorded:string[]){const rows=service.db.prepare("SELECT id,operation_key operationKey FROM sync_outbox WHERE status='pending'").all() as any[];if(mode==="pending")return;if(mode==="failing"){for(const row of rows)service.db.prepare("UPDATE sync_outbox SET status='failed',attempt_count=attempt_count+1,last_error='simulated unavailable' WHERE id=?").run(row.id);return;}for(const row of rows){if(mode==="recording")recorded.push(row.operationKey);service.db.prepare("UPDATE sync_outbox SET status='succeeded',attempt_count=attempt_count+1,succeeded_at=? WHERE id=?").run(fixedTime(0),row.id);}}
function runScenario(scenario:Scenario,boardRows:BoardRow[],paths:any,buildId:string){
  const random=rng(scenario.seed),temp=mkdtempSync(join(tmpdir(),`renegade-sim-${scenario.id}-`)),dbPath=join(temp,"draft.sqlite");if(resolve(dbPath)===ACTIVE_DB)throw new Error("simulation resolved to active database");
  const service=DraftService.open(dbPath,join(ROOT,"db/migrations/001_initial.sql"));const recorded:string[]=[];let snapshots:ActionSnapshot[]=[];const warnings:string[]=[];
  try{
    initializeFromArtifacts(service,{draftId:DRAFT_ID,season:2026,name:`Simulation ${scenario.id}`,decisionBoardPath:paths.board,ownerProfilesPath:paths.owners,teamNames:{"George Rodman":"Rodman Renegades"}});
    service.startDraft({draftId:DRAFT_ID,expectedVersion:0,idempotencyKey:`${scenario.id}:start`,occurredAt:fixedTime(0)});applyOutbox(service,"noop",recorded);
    const board=new Map(boardRows.map(row=>[row.internal_player_id,row]));const maxima=Object.fromEntries(["QB","RB","WR","TE","K","DEF"].map(pos=>[pos,Math.max(...boardRows.filter(row=>row.position===pos).map(row=>Number(row.points_above_replacement??0)))]));const historicalByPlayer=new Map((paths.historical as HistoricalSale[]).filter(sale=>sale.season===scenario.season).map(sale=>[sale.internal_player_id,sale]));const replayedHistoricalIds=new Set<string>();const order=completeOrder(boardRows,scenario,random,paths.historical);
    const historicalEvidence={seasonSales:(paths.historical as HistoricalSale[]).filter(sale=>sale.season===scenario.season).length,compatiblePlayers:[...historicalByPlayer.keys()].filter(id=>board.has(id)).length,actualPricesUsed:0,actualBuyersPreserved:0,buyersSubstitutedForLegality:0};
    for(let index=0;index<140;index++){
      const started=performance.now();let row=order[index]!;let view=state(service,board);const teamsDb=service.db.prepare("SELECT t.id,t.display_name name,o.display_name owner,s.remaining_budget budget,s.open_slot_count openSlots FROM teams t JOIN owners o ON o.id=t.owner_id JOIN team_draft_state s ON s.team_id=t.id WHERE t.draft_id=? ORDER BY t.id").all(DRAFT_ID) as any[];let winner:any=null;for(let candidateIndex=index;candidateIndex<order.length;candidateIndex++){const candidate=order[candidateIndex]!;try{const legal=legalWinners(service,candidate,teamsDb);if(!legal.length)throw new Error(`no legal winner for ${candidate.player_name}`);const historical=historicalByPlayer.get(candidate.internal_player_id);const historicalLegal=historical&&scenario.family==="historical_price"?legal.filter(team=>historical.salary<=team.budget-(team.openSlots-1)):[];const actual=historicalLegal.find(team=>team.owner===historical?.owner);winner=actual??historicalLegal[0]??chooseWinner(service,candidate,teamsDb,scenario,index,random);if(historicalLegal.length){replayedHistoricalIds.add(candidate.internal_player_id);if(actual)historicalEvidence.actualBuyersPreserved++;else historicalEvidence.buyersSubstitutedForLegality++;}row=candidate;[order[index],order[candidateIndex]]=[order[candidateIndex]!,order[index]!];break;}catch(error){if(!(error instanceof Error)||!error.message.startsWith("no legal winner"))throw error;}}if(!winner)throw new Error("no remaining player can preserve legal roster completion");const nominator=teamsDb[index%teamsDb.length]!;
      service.openNomination({draftId:DRAFT_ID,expectedVersion:index*2+1,idempotencyKey:`${scenario.id}:nom:${index}`,occurredAt:fixedTime(index*2+1),playerId:row.internal_player_id,nominatedByTeamId:nominator.id});
      view=state(service,board);const maxBid=view.renegades.remainingBudget-(view.renegades.openSlots-1);const decision=index<12||index%10===0?nominationDecision(view.teams,view.renegades.id,view.available,row.internal_player_id,maxBid):null;const roadmap=index<12||index%10===0?draftRoadmap(view.teams,view.renegades.id,view.available,maxBid):{targets:[],impacts:[]};const leaders=liveLeaderboard(view.teams,view.available);const impact=roadmap.impacts.find(item=>item.playerId===row.internal_player_id);const tierPeers=view.available.filter(p=>p.position===row.position&&p.productionTier===row.production_tier&&p.id!==row.internal_player_id&&p.expectedPrice<=maxBid).sort((a,b)=>b.projectedPoints-a.projectedPoints).slice(0,4);const scarcity=tierPeers.length===0?"Unique production":tierPeers.length<=2?"Thin alternatives":tierPeers.length<=5?"Comparable options":"Highly replaceable";
      const historical=historicalByPlayer.get(row.internal_player_id);const useHistorical=replayedHistoricalIds.has(row.internal_player_id);const price=useHistorical?historical!.salary:salePrice(row,winner,scenario,index,random);if(useHistorical)historicalEvidence.actualPricesUsed++;service.recordSale({draftId:DRAFT_ID,expectedVersion:index*2+2,idempotencyKey:`${scenario.id}:sale:${index}`,occurredAt:fixedTime(index*2+2),winnerTeamId:winner.id,price});applyOutbox(service,index===20?"failing":index===21?"recording":index===40?"pending":"noop",recorded);
      const after=state(service,board),renRank=leaders.find(item=>item.teamId===view.renegades.id)?.rank??0;snapshots.push({sale:index+1,stateVersion:index*2+3,playerId:row.internal_player_id,player:row.player_name,position:row.position,nominator:nominator.name,winner:winner.name,price,expectedPrice:Number(row.expected_jugg_price),range:[Number(row.price_range_low),Number(row.price_range_high)],productionLabel:label(row,maxima[row.position]),scarcityLabel:scarcity,alternatives:tierPeers.map(p=>p.name),draftImpact:impact?.label??null,walkaway:decision?.recommendedMax??null,bands:decision?.tiers??[],fallbacks:tierPeers.map(p=>p.name),upcomingTargets:roadmap.targets.map(item=>item.name),renegades:{budget:after.renegades.remainingBudget,openSlots:after.renegades.openSlots,maxBid:after.renegades.remainingBudget-Math.max(0,after.renegades.openSlots-1)},leagueBudgets:after.teams.map(team=>team.remainingBudget),likelyCompetition:view.teams.filter(team=>team.id!==view.renegades.id&&team.openSlots>0&&team.remainingBudget-(team.openSlots-1)>=Math.max(1,Number(row.price_range_low))).map(team=>team.name),leaderboardLeader:leaders[0]?.name??"",renegadesRank:renRank,latencyMs:Number((performance.now()-started).toFixed(2)),warnings:[]});
    }
    const finalState=state(service,board),audit=service.recoveryAudit(DRAFT_ID);const totals=service.db.prepare("SELECT SUM(remaining_budget) budget,SUM(open_slot_count) slots,SUM(rostered_player_count) rostered FROM team_draft_state").get() as any;const outbox=service.db.prepare("SELECT status,COUNT(*) count FROM sync_outbox GROUP BY status").all();const fingerprint=hash(JSON.stringify({teams:finalState.teams.map(t=>({id:t.id,budget:t.remainingBudget,open:t.openSlots,players:t.roster.map(p=>p.id).sort()})),audit,totals}));
    service.db.close();const reopened=DraftService.open(dbPath,join(ROOT,"db/migrations/001_initial.sql"));const recoveryAudit=reopened.recoveryAudit(DRAFT_ID),reopenedFingerprint=hash(JSON.stringify({teams:(reopened.db.prepare("SELECT t.id,s.remaining_budget budget,s.open_slot_count openSlots FROM teams t JOIN team_draft_state s ON s.team_id=t.id ORDER BY t.id").all()),sales:reopened.db.prepare("SELECT player_id,winner_team_id,price FROM sales WHERE voided_event_id IS NULL ORDER BY recorded_at").all()}));reopened.db.close();
    const bandOrder:any={strong_pursue:0,lean_pursue:1,neutral:2,lean_pass:3,strong_pass:4};const monotonic=snapshots.every(s=>s.bands.every((b:any,i:number)=>i===0||bandOrder[b.band]>=bandOrder[s.bands[i-1]?.band]));const fallbackValid=snapshots.every(s=>s.fallbacks.every(name=>s.alternatives.includes(name)));
    return {id:scenario.id,family:scenario.family,seed:scenario.seed,season:scenario.season??2026,classification:scenario.family==="historical_price"?"compatible actual historical prices and buyers replayed through a generated nomination order; remaining slots simulated":"fully simulated 2026 draft",historicalEvidence:scenario.family==="historical_price"?historicalEvidence:null,sales:snapshots.length,completed:snapshots.length===140,legal:audit.length===0&&totals.slots===0&&totals.rostered===140,budgetConservation:totals.budget===2000-snapshots.reduce((sum,row)=>sum+row.price,0),recoveryEquivalent:recoveryAudit.length===0,deterministicFingerprint:fingerprint,reopenedFingerprint,outbox,recordedSyncOperations:recorded.length,checks:{priceBandMonotonic:monotonic,fallbackValidity:fallbackValid},latency:{medianMs:[...snapshots].sort((a,b)=>a.latencyMs-b.latencyMs)[Math.floor(snapshots.length/2)]?.latencyMs,maxMs:Math.max(...snapshots.map(s=>s.latencyMs))},warnings,actions:snapshots};
  }catch(error){try{service.db.close();}catch{}return{id:scenario.id,family:scenario.family,seed:scenario.seed,season:scenario.season??2026,completed:false,legal:false,error:error instanceof Error?(error.stack??`${error.name}: ${error.message}`):String(error),warnings,actions:snapshots};}finally{rmSync(temp,{recursive:true,force:true});}
}

const production=JSON.parse(readFileSync("data/processed/production_value_model/latest.json","utf8")),owners=JSON.parse(readFileSync("data/processed/owner_tendencies/latest.json","utf8")),historyPointer=JSON.parse(readFileSync("data/processed/auction_history_matches/latest.json","utf8"));const boardPayload=JSON.parse(readFileSync(production.decision_board_json,"utf8")),historicalPayload=JSON.parse(readFileSync(historyPointer.artifact,"utf8"));const git=(()=>{try{return execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim();}catch{return"unknown";}})();
const seedOffset=Number(process.env.SIM_SEED_OFFSET??0),runLabel=process.env.SIM_RUN_LABEL??"baseline",publishLatest=process.env.SIM_PUBLISH_LATEST!=="false";
const scenarios:Scenario[]=[];for(const season of [2021,2022,2023,2024,2025])for(const [i,order] of (["expected","random"] as const).entries())scenarios.push({id:`historical-${season}-${order}`,family:"historical_price",season,seed:season*10+i+seedOffset,order,priceFactor:1,noise:4,winnerPolicy:"balanced"});
scenarios.push(
 {id:"2026-near-expected",family:"2026_market",seed:601+seedOffset,order:"expected",priceFactor:1,noise:1,winnerPolicy:"balanced"},{id:"2026-modeled-ranges",family:"2026_market",seed:602+seedOffset,order:"random",priceFactor:1,noise:6,winnerPolicy:"balanced"},{id:"2026-aggressive",family:"2026_market",seed:603+seedOffset,order:"expected",priceFactor:1.2,noise:4,winnerPolicy:"top_heavy"},{id:"2026-conservative",family:"2026_market",seed:604+seedOffset,order:"reverse",priceFactor:.8,noise:3,winnerPolicy:"depth"},{id:"2026-rb-inflation",family:"2026_market",seed:605+seedOffset,order:"rb_early",priceFactor:1,noise:3,winnerPolicy:"balanced"},{id:"2026-wr-inflation",family:"2026_market",seed:606+seedOffset,order:"wr_early",priceFactor:1,noise:3,winnerPolicy:"balanced"},{id:"2026-elite-pressure",family:"2026_market",seed:607+seedOffset,order:"expected",priceFactor:1,noise:5,winnerPolicy:"top_heavy"},{id:"2026-late-budgets",family:"2026_market",seed:608+seedOffset,order:"reverse",priceFactor:.9,noise:2,winnerPolicy:"late_budget"},{id:"2026-early-exhaustion",family:"2026_market",seed:609+seedOffset,order:"expected",priceFactor:1.15,noise:5,winnerPolicy:"early_budget"},{id:"2026-depth",family:"2026_market",seed:610+seedOffset,order:"random",priceFactor:.95,noise:4,winnerPolicy:"depth"},{id:"2026-randomized",family:"2026_market",seed:611+seedOffset,order:"random",priceFactor:1,noise:8,winnerPolicy:"balanced"});
const selected=process.env.SIM_SCENARIO?scenarios.filter(s=>s.id===process.env.SIM_SCENARIO):scenarios;if(!selected.length)throw new Error(`Unknown SIM_SCENARIO ${process.env.SIM_SCENARIO}`);const config={schemaVersion:2,runLabel,seeds:selected.map(s=>s.seed),artifactBuildIds:{production:production.build_id,owners:owners.build_id,auctionHistory:historyPointer.build_id},git,assumptions:{owners:10,budget:200,slots:14,minimumBid:1,historicalNominationOrder:"generated price-descending or seeded-random order; exact chronology unavailable",historicalPriceUse:"actual JUGG price for current-pool-compatible historical players; all unmatched records and buyer substitutions reported",sync:"local recording/failure states only; no network adapter invoked",decisionCapture:"full packet for first 12 and every tenth nomination; state/accounting captured for every sale"}};const buildId=hash(JSON.stringify(config)).slice(0,16);const results=selected.map((scenario,index)=>{process.stdout.write(`[${index+1}/${selected.length}] ${scenario.id}\n`);return runScenario(scenario,boardPayload.players,{board:production.decision_board_json,owners:owners.artifact,historical:historicalPayload.sales},buildId);});
const summary={runs:results.length,completed:results.filter(r=>r.completed).length,legal:results.filter(r=>r.legal).length,failures:results.filter(r=>!r.completed).map(r=>({id:r.id,error:(r as any).error})),checks:{priceBandMonotonic:results.every(r=>(r as any).checks?.priceBandMonotonic!==false),fallbackValidity:results.every(r=>(r as any).checks?.fallbackValidity!==false),recoveryEquivalent:results.every(r=>(r as any).recoveryEquivalent!==false)},limitations:["Exact historical nomination order is unavailable; historical prices are replayed through explicitly generated orders.","Only historical players compatible with the current 2026 pool can enter a full current-roster simulation; coverage and buyer substitutions are reported by season.","Championship values are shadow rankings, not calibrated title probabilities."]};
const output={metadata:{buildId,createdAt:"2026-08-25T00:00:00.000Z",...config},summary,scenarios:results};const outDir=join(ROOT,"data/processed/draft_simulations",buildId);mkdirSync(outDir,{recursive:true});writeFileSync(join(outDir,"baseline.json"),JSON.stringify(output,null,2)+"\n");if(publishLatest)writeFileSync(join(ROOT,"data/processed/draft_simulations/latest.json"),JSON.stringify({schema_version:1,build_id:buildId,artifact:`data/processed/draft_simulations/${buildId}/baseline.json`},null,2)+"\n");process.stdout.write(JSON.stringify({buildId,publishedLatest:publishLatest,...summary},null,2)+"\n");if(summary.completed!==results.length||summary.legal!==results.length)process.exitCode=1;
