import Link from "next/link";
import type { Metadata } from "next";
import { readDraftRoom } from "../../src/server/draftStore";
import { ResearchControls } from "./ResearchControls";
import { ResearchWriteup } from "../../src/ui/research/ResearchWriteup";
import styles from "./research.module.css";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Renegade Research"};

type ResearchSource={url:string;sourceTitle:string;sentiment:"positive"|"negative"|"neutral";summary:string;rationale:string;risks:string[]};
type PlayerInjury={status:string|null;statusShort:string|null;injuryType:string|null;comment:string|null;updatedAt:string|null;probabilityOfPlaying:string|null;practiceReportInjuryType:string|null;practice:string[];irWeeks:number[]};
type PlayerNews={id:string;title:string;description:string|null;impact:string|null;author:string|null;createdAt:string|null;url:string|null};
type SituationSignal={key:string;tone:"positive"|"negative"|"neutral";text:string;priority:number};
type ProjectedStatLine={stats?:Record<string,number|null>|null}|null;
type ResearchPlayer={id:string;name:string;position:string;nflTeam:string|null;previousNflTeam:string|null;byeWeek:number|null;birthDate:string|null;positionRank:number|null;expectedPrice:number|null;priceLow:number|null;priceHigh:number|null;liveExpectedPrice:number|null;livePriceLow:number|null;livePriceHigh:number|null;injury:PlayerInjury|null;recentNews:PlayerNews[];fantasyAnalysis:ResearchSource[];situationSignals:SituationSignal[];projectedStatLine:ProjectedStatLine;analystConsensus:{derivedAction:"target"|"avoid"|null;override:"target"|"avoid"|"off"|null;tags:string[];derivedTags:string[];tagOverrides:Partial<Record<"sleeper"|"breakout"|"value"|"bust",boolean>>;positiveCount:number;negativeCount:number;independentOpinionCount:number;pros:string[];cons:string[];commonCase:string|null;mainConcern:string|null;aiSummary:{cardSummary?:string|null;fullWriteup:string|null;prosSummary:string|null;consSummary:string|null}|null}};
type PlayerList={id:string;title:string;description:string;players:{player:ResearchPlayer;reason:string}[]};

function anchor(player:ResearchPlayer){return `player-${player.id.replaceAll(":","-")}`;}
function actionLabel(player:ResearchPlayer){const {derivedAction,override}=player.analystConsensus,action=override==="off"?null:override??derivedAction;return action?`${action[0]!.toUpperCase()}${action.slice(1)}`:override==="off"?"Hidden":"Unclassified";}
function xPrice(player:ResearchPlayer){const price=player.liveExpectedPrice??player.expectedPrice;return price==null?"—":`$${Math.round(price)}`;}
function priceRange(player:ResearchPlayer){const low=player.livePriceLow??player.priceLow,high=player.livePriceHigh??player.priceHigh;return low==null||high==null?null:`$${Math.round(low)}–$${Math.round(high)}`;}
function playerAge(birthDate:string|null){if(!birthDate)return null;const born=new Date(`${birthDate}T00:00:00Z`),today=new Date();let age=today.getUTCFullYear()-born.getUTCFullYear();if(today.getUTCMonth()<born.getUTCMonth()||(today.getUTCMonth()===born.getUTCMonth()&&today.getUTCDate()<born.getUTCDate()))age--;return age;}
function contextDate(value:string|null){if(!value)return null;const parsed=new Date(`${value.replace(" ","T")}${value.includes("Z")||value.includes("+")?"":"Z"}`);return Number.isNaN(parsed.valueOf())?value:parsed.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});}
function injurySummary(injury:PlayerInjury){const probability=injury.probabilityOfPlaying==null?null:Number(injury.probabilityOfPlaying),probabilityLabel=probability==null||Number.isNaN(probability)?null:`${Math.round((probability<=1?probability*100:probability)*10)/10}% probability of playing`;return [injury.status,injury.injuryType??injury.practiceReportInjuryType,injury.comment,probabilityLabel,injury.practice.length?`Practice: ${injury.practice.join(" / ")}`:null,injury.irWeeks.length?`IR weeks: ${injury.irWeeks.join(", ")}`:null].filter(Boolean).join(" · ");}
function stat(player:ResearchPlayer,key:string){return Number(player.projectedStatLine?.stats?.[key]??0);}
function hasSignal(player:ResearchPlayer,key:string,tone:"positive"|"negative"){return player.situationSignals.some(signal=>signal.key===key&&signal.tone===tone);}
function playerLists(allPlayers:ResearchPlayer[],writeupPlayers:ResearchPlayer[]):PlayerList[]{
  const eligible=new Set(writeupPlayers.map(player=>player.id)),available=allPlayers.filter(player=>eligible.has(player.id));
  const teamPlayers=new Map<string,ResearchPlayer[]>();
  for(const player of allPlayers)if(player.nflTeam){const rows=teamPlayers.get(player.nflTeam)??[];rows.push(player);teamPlayers.set(player.nflTeam,rows);}
  const teamMetrics=new Map<string,{rushAttempts:number;passAttempts:number;runRate:number;passRate:number;projectedReceptions:number;rbAttempts:number}>();
  for(const [team,rows] of teamPlayers){const quarterback=[...rows].filter(player=>player.position==="QB").sort((a,b)=>(a.positionRank??999)-(b.positionRank??999))[0],passAttempts=quarterback?stat(quarterback,"passing_attempts"):0,rushAttempts=rows.reduce((sum,player)=>sum+stat(player,"rushing_attempts"),0),projectedReceptions=rows.filter(player=>["RB","WR","TE"].includes(player.position)).reduce((sum,player)=>sum+stat(player,"receptions"),0),total=Math.max(1,passAttempts+rushAttempts);teamMetrics.set(team,{rushAttempts,passAttempts,runRate:rushAttempts/total,passRate:passAttempts/total,projectedReceptions,rbAttempts:rows.filter(player=>player.position==="RB").reduce((sum,player)=>sum+stat(player,"rushing_attempts"),0)});}
  const oriented=[...teamMetrics.entries()].filter(([,metric])=>metric.passAttempts>0&&metric.rushAttempts>0),runCutoff=[...oriented].map(([,metric])=>metric.runRate).sort((a,b)=>b-a)[Math.max(0,Math.ceil(oriented.length*.25)-1)]??1,passCutoff=[...oriented].map(([,metric])=>metric.passRate).sort((a,b)=>b-a)[Math.max(0,Math.ceil(oriented.length*.25)-1)]??1;
  const sorted=(rows:{player:ResearchPlayer;reason:string}[])=>rows.sort((a,b)=>(a.player.positionRank??999)-(b.player.positionRank??999)||a.player.name.localeCompare(b.player.name));
  const bellCow=sorted(available.filter(player=>player.position==="RB").flatMap(player=>{const team=player.nflTeam?teamMetrics.get(player.nflTeam):null,carries=stat(player,"rushing_attempts"),share=team&&team.rbAttempts?carries/team.rbAttempts:0,role=hasSignal(player,"workload_role","positive");return role||(carries>=190&&share>=.58)?[{player,reason:role?`Research supports a lead or bell-cow workload; projected for ${Math.round(carries)} carries.`:`Projected for ${Math.round(carries)} carries and ${Math.round(share*100)}% of team RB attempts.`}]:[];}));
  const handcuffs=sorted(available.filter(player=>player.position==="RB").flatMap(player=>{const signal=player.situationSignals.find(item=>item.key==="backfield_role"&&item.tone==="negative");return signal?[{player,reason:signal.text}]:[];}));
  const highTarget=sorted(available.filter(player=>player.position==="WR"&&(player.positionRank??999)<=48).flatMap(player=>{const team=player.nflTeam?teamMetrics.get(player.nflTeam):null,receptions=stat(player,"receptions"),share=team&&team.projectedReceptions?receptions/team.projectedReceptions:0,priorElite=hasSignal(player,"target_volume","positive");return priorElite||(receptions>=70&&share>=.23)?[{player,reason:priorElite?`Top-12 WR target volume last season with ${Math.round(receptions)} receptions projected.`:`Projected for ${Math.round(receptions)} receptions, about ${Math.round(share*100)}% of team catches.`}]:[];}));
  const goodQbReceivers=sorted(available.filter(player=>player.position==="WR"&&(player.positionRank??999)<=36&&hasSignal(player,"quarterback_quality","positive")).map(player=>({player,reason:player.situationSignals.find(item=>item.key==="quarterback_quality"&&item.tone==="positive")!.text})));
  const runTeamRbs=sorted(available.filter(player=>player.position==="RB"&&(player.positionRank??999)<=24).flatMap(player=>{const metric=player.nflTeam?teamMetrics.get(player.nflTeam):null;return metric&&metric.runRate>=runCutoff?[{player,reason:`Top-quarter projected run tendency (${Math.round(metric.runRate*100)}% of modeled plays are rushes).`}]:[];}));
  const passTeamWrs=sorted(available.filter(player=>player.position==="WR"&&(player.positionRank??999)<=36).flatMap(player=>{const metric=player.nflTeam?teamMetrics.get(player.nflTeam):null;return metric&&metric.passRate>=passCutoff?[{player,reason:`Top-quarter projected pass tendency (${Math.round(metric.passRate*100)}% of modeled plays are passes).`}]:[];}));
  const changedForBetter=sorted(available.filter(player=>["RB","WR","TE"].includes(player.position)).flatMap(player=>{const summary=player.analystConsensus.aiSummary,text=`${summary?.cardSummary??""} ${summary?.fullWriteup??""}`,changed=Boolean(player.previousNflTeam&&player.nflTeam&&player.previousNflTeam!==player.nflTeam),better=/(?:better|improved|upgrade|upgraded|elite|top-eight|efficient|stronger).{0,45}(?:quarterback|passing|offense|offensive|environment)|(?:quarterback|passing|offense|offensive|environment).{0,45}(?:better|improved|upgrade|upgraded|elite|top-eight|efficient|stronger)/i.test(text)||hasSignal(player,"quarterback_quality","positive");return changed&&better?[{player,reason:`Moved from ${player.previousNflTeam} to ${player.nflTeam}; research supports the quarterback or offensive environment as an upgrade.`}]:[];}));
  return [{id:"bell-cow-backs",title:"Bell-cow and lead backs",description:"Backs with explicit lead-workload research or at least 190 projected carries and 58% of their team’s projected RB attempts.",players:bellCow},{id:"handcuff-backs",title:"Primary RB handcuffs",description:"Backups identified in the stored 2026 handcuff rankings who could gain substantial value if the starter misses time.",players:handcuffs},{id:"high-target-wrs",title:"High-target wide receivers",description:"Top-48 receivers with top-12 target volume last season or a large projected share of their team’s catches.",players:highTarget},{id:"good-qb-wrs",title:"Quality WRs with strong quarterbacks",description:"Top-36 receivers paired with a top-eight projected fantasy quarterback.",players:goodQbReceivers},{id:"run-team-rbs",title:"Quality RBs on run-oriented teams",description:"Top-24 backs on teams in the highest quarter of projected rushing tendency.",players:runTeamRbs},{id:"pass-team-wrs",title:"Quality WRs on pass-oriented teams",description:"Top-36 receivers on teams in the highest quarter of projected passing tendency.",players:passTeamWrs},{id:"better-new-team",title:"Changed teams into a better situation",description:"Players whose refreshed research describes a team change and an improved quarterback or offensive environment.",players:changedForBetter}];
}

export default function ResearchWikiPage(){
  const data=readDraftRoom();
  const allPlayers=data.players as ResearchPlayer[];
  const players=allPlayers.filter(player=>player.analystConsensus.aiSummary?.fullWriteup).sort((a,b)=>a.name.localeCompare(b.name));
  const lists=playerLists(allPlayers,players);
  const groups=["QB","RB","WR","TE","K","DEF"].map(position=>({position,players:players.filter(player=>player.position===position).sort((a,b)=>(a.positionRank??Number.MAX_SAFE_INTEGER)-(b.positionRank??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name))})).filter(group=>group.players.length);
  const generatedAt=data.researchStatus.lastSummaryGeneratedAt?new Date(data.researchStatus.lastSummaryGeneratedAt).toLocaleString("en-US",{dateStyle:"long",timeStyle:"short"}):"Unknown";
  return <main className={styles.wiki}>
    <header className={styles.header}>
      <div><small>RENEGADE DRAFT ROOM</small><h1>Fantasy Research Wiki</h1><p>{players.length} full player writeups · Updated {generatedAt} · Available offline</p></div>
      <Link href="/board">← Draft board</Link>
    </header>
    <nav className={styles.jumpNav} aria-label="Research sections"><a href="#player-lists">Player lists</a><a href="#index">Player index</a>{groups.map(group=><a key={group.position} href={`#position-${group.position.toLowerCase()}`}>{group.position} <span>{group.players.length}</span></a>)}</nav>
    <section className={styles.intro}><strong>How to use this wiki</strong><p>Use your browser’s Find command to search for any player, analyst, risk, or theme. Target and Avoid identify actionable research direction; no selected action means neutral or unresolved. Sleeper, Breakout, Value, and Bust describe the argument. Full writeups preserve price, role, injury, and format caveats from the retained research.</p></section>
    <section className={styles.playerLists} id="player-lists"><div className={styles.sectionHeading}><h2>Player lists</h2><a href="#index">Jump to full index ↓</a></div><p className={styles.listMethod}>These lists combine current projections, rankings, team context, and retained research. They update automatically with the wiki data; they do not create Target or Avoid flags.</p><div className={styles.listGrid}>{lists.map(list=><article id={list.id} key={list.id}><header><h3>{list.title}</h3><span>{list.players.length}</span></header><p>{list.description}</p>{list.players.length?<ul>{list.players.map(({player,reason})=><li key={player.id}><div><a href={`#${anchor(player)}`}>{player.name}</a><small>{player.position}{player.positionRank??"—"} · {player.nflTeam??"FA"} · {xPrice(player)}</small></div><p>{reason}</p><a className={styles.writeupLink} href={`#${anchor(player)}`}>Full writeup ↓</a></li>)}</ul>:<em>No current players meet this rule.</em>}</article>)}</div></section>
    <section className={styles.index} id="index"><h2>Player index</h2><div>{players.map(player=><a href={`#${anchor(player)}`} key={player.id}><span>{player.name}</span><small>{player.position} · {actionLabel(player)}</small></a>)}</div></section>
    {groups.map(group=><section className={styles.positionSection} id={`position-${group.position.toLowerCase()}`} key={group.position}>
      <div className={styles.sectionHeading}><h2>{group.position} full writeups</h2><a href="#index">Back to index ↑</a></div>
      {group.players.map(player=>{const consensus=player.analystConsensus,summary=consensus.aiSummary!,range=priceRange(player),pros=summary.prosSummary??consensus.commonCase??"No clear upside case is captured in the current research.",cons=summary.consSummary??consensus.mainConcern??"No specific downside case is captured in the current research.";const sources=[...new Map(player.fantasyAnalysis.map(source=>[source.url,source])).values()];return <ResearchWriteup key={player.id} id={anchor(player)} name={player.name} positionPrice={`${player.position}${player.positionRank??"—"} - ${xPrice(player)}${range?` (${range})`:""}`} playerMeta={`${player.nflTeam??"Free agent"}${player.byeWeek?` · Bye ${player.byeWeek}`:""}${playerAge(player.birthDate)!=null?` · Age ${playerAge(player.birthDate)}`:""}`} controls={<ResearchControls playerId={player.id} derivedAction={consensus.derivedAction} override={consensus.override} tags={consensus.tags} derivedTags={consensus.derivedTags} tagOverrides={consensus.tagOverrides}/>} positiveCount={consensus.positiveCount} negativeCount={consensus.negativeCount} independentOpinionCount={consensus.independentOpinionCount} pros={pros} cons={cons} fullWriteup={summary.fullWriteup!} context={player.injury?<div className={`${styles.contextCallout} ${styles.injuryCallout}`}><strong>Injury:</strong> <span>{injurySummary(player.injury)}</span>{contextDate(player.injury.updatedAt)&&<small>FantasyPros · Updated {contextDate(player.injury.updatedAt)}</small>}</div>:null} sources={sources.map(source=>({url:source.url,title:source.sourceTitle}))} indexHref="#index"/>;})}
    </section>)}
  </main>;
}
