import { assistantContextSchema, ASSISTANT_CONTEXT_VERSION, type AssistantContext, conversationTurnSchema } from "./contracts";
import { activeSeason } from "../activeSeason";
import type { z } from "zod";

type View=ReturnType<typeof import("../draftStore").readDraftRoom>;
const ref=(player:any)=>({id:String(player.id??player.playerId),name:String(player.name),position:String(player.position),nflTeam:player.nflTeam??null,byeWeek:player.byeWeek??null});
function bands(decision:any){
  if(!decision?.tiers?.length)return null;
  const labels:Record<string,"Great"|"Good"|"Neutral"|"Poor"|"Bad">={strong_pursue:"Great",lean_pursue:"Good",neutral:"Neutral",lean_pass:"Poor",strong_pass:"Bad"};
  const result=(decision?.tiers??[]).map((tier:any)=>({label:labels[tier.band]!,from:tier.from,to:tier.to}));
  for(const label of ["Great","Good","Neutral","Poor","Bad"] as const)if(!result.some((row:any)=>row.label===label))result.push({label,from:0,to:0});
  return result.sort((a:any,b:any)=>["Great","Good","Neutral","Poor","Bad"].indexOf(a.label)-["Great","Good","Neutral","Poor","Bad"].indexOf(b.label)).slice(0,5);
}
type ConversationTurn=z.infer<typeof conversationTurnSchema>;
export function buildAssistantContext(view:View,input:{trigger:AssistantContext["trigger"];question?:string|null;focusPlayerId?:string|null;conversationHistory?:ConversationTurn[]}):AssistantContext{
  const focus=view.currentNomination??view.players.find((p:any)=>p.id===input.focusPlayerId)??null,decision=view.currentNomination?.championshipDecision??null;
  const renegades=view.renegades,slots=renegades?view.teamRosters[renegades.id]??[]:[];
  const roster=slots.filter((s:any)=>s.playerId).map((s:any)=>ref({id:s.playerId,name:s.player,position:s.position,nflTeam:null,byeWeek:s.byeWeek}));
  const needs=[...new Set(slots.filter((s:any)=>!s.playerId).map((s:any)=>s.slotType))] as string[];
  const leagueTeams=view.teams.map((team:any)=>{const teamSlots=view.teamRosters[team.id]??[];return{teamId:team.id,team:team.name,owner:team.owner,roster:teamSlots.filter((s:any)=>s.playerId).map((s:any)=>ref({id:s.playerId,name:s.player,position:s.position,nflTeam:null,byeWeek:s.byeWeek})),needs:[...new Set(teamSlots.filter((s:any)=>!s.playerId).map((s:any)=>s.slotType))] as string[],remainingBudget:team.remainingBudget,openSlots:team.openSlots,maximumLegalBid:team.maxBid};});
  const outlook=view.leaderboard.find((r:any)=>r.name==="Rodman Renegades");
  const userConversation=(input.conversationHistory??[]).filter(turn=>turn.role==="user").map(turn=>turn.text).join(" "),hypotheticalSource=`${userConversation} ${input.question??""}`;
  const hypotheticalPrices=[...new Set([...hypotheticalSource.matchAll(/\$(\d{1,3})\b|\b(?:pay|went to|go to|at|bid)\s+\$?(\d{1,3})\b/gi)].map(match=>Number(match[1]??match[2])).filter(value=>Number.isInteger(value)&&value>=1&&value<=999))].slice(0,10);
  const packet={schemaVersion:ASSISTANT_CONTEXT_VERSION,draftId:activeSeason.draftId,stateVersion:view.draft.stateVersion,trigger:input.trigger,generatedAt:new Date().toISOString(),
    focus:focus?{player:ref(focus),adp:focus.marketAdp??null,riskFlags:focus.riskFlags??[],freshness:{label:"pre-draft artifacts plus current local draft state",provenance:["SQLite draft state","accepted deterministic decision packet"]},prices:{currency:"USD" as const,preDraftExpected:focus.expectedPrice??null,liveExpected:focus.liveExpectedPrice??null,modeledLow:focus.livePriceLow??null,modeledHigh:focus.livePriceHigh??null,roomMovement:focus.liveExpectedPrice!=null&&focus.expectedPrice!=null?focus.liveExpectedPrice-focus.expectedPrice:null},priceBands:bands(decision),walkAway:focus.decisionPlan?.committedCeiling??focus.decisionCeiling??null,production:{projectedPoints:focus.projectedPoints,xpar:focus.pointsAboveReplacement??null,label:focus.productionLabel,scarcity:focus.productionTierRemaining===1?"Unique production":(focus.alternatives?.length??0)>1?"Comparable options":"Thin alternatives",fallback:focus.alternatives?.[0]?.name??null},recommendation:{band:decision?.band??focus.draftImpact?.band??"preview_only",scenarioSupport:decision?`${Math.round(decision.support*9)} of 9 tested paths`:focus.draftImpact?`${Math.round(focus.draftImpact.scenarioSupport*9)} of 9 tested paths`:"not calculated",rationale:decision?.explanation??focus.draftImpact?.summary??"Official nomination is required for the full decision ladder.",shadowModel:true as const,shadowStatus:"relative shadow signal; not a calibrated title probability"}}:null,
    renegades:renegades?{roster,needs,remainingBudget:renegades.remainingBudget,openSlots:renegades.openSlots,maximumLegalBid:renegades.maxBid}:null,leagueTeams,
    alternatives:(view.currentNomination?.alternatives??[]).map((p:any)=>({player:ref(p),liveExpected:p.liveExpectedPrice??null,walkAway:p.decisionCeiling??null,costOfWaiting:`Waiting preserves budget but risks losing ${focus?.productionLabel??"this production level"}.`})),
    competitors:(view.currentNomination?.competition??[]).map((c:any)=>({owner:c.name,maximumLegalBid:c.maxBid,rosterFit:"Can legally compete at the expected price",tendency:c.signal??null,uncertainty:c.signal?"Historical tendency is limited evidence, not intent.":"No supported owner tendency is available."})),nominationContext:{isRenegadesTurn:Boolean(renegades&&view.nominationOrder.nextTeamId===renegades.id),nextNominator:view.nominationOrder.teams.find((team:any)=>team.teamId===view.nominationOrder.nextTeamId)?.owner??null},
    upcomingTargets:view.upcomingTargets.map((t:any)=>({player:ref(view.players.find((p:any)=>p.id===t.playerId)??t),targetPrice:t.targetPrice,walkAway:t.walkawayCeiling,fallback:t.replacementPlayer,conditionalPlan:t.conditionalPlan})),recentSales:view.recentSales.slice(0,8).map((s:any)=>({player:s.player,team:s.team,price:s.price})),market:{salesCount:view.market.salesCount,pressure:`Live room multiplier ${view.market.globalMultiplier.toFixed(3)} after ${view.market.salesCount} sales.`},whatChanged:view.whatChanged?{headline:view.whatChanged.headline,reasons:view.whatChanged.reasons}:null,leagueOutlook:outlook?{rank:outlook.rank,rankRange:`#${outlook.rank} with overlapping ranges treated as close`,shadowStatus:"relative shadow rank only; not a title probability"}:null,preferences:{structuredAdjustments:focus?.strategyReasons??[],untrustedNotes:[...view.strategy.situations,view.strategy.notes].filter(Boolean),bounded:true as const},missingOrStale:[...(focus?.byeWeek==null?["focused player bye week missing"]:[]),...(view.currentNomination?[]:["no official nomination; full price ladder and competitors may be unavailable"])],userQuestion:input.question?.trim()||null,conversationHistory:(input.conversationHistory??[]).slice(-8),userInputs:{hypotheticalPrices,authoritative:false as const}};
  return assistantContextSchema.parse(packet);
}
